Solve bug constraints test for new cloud (implementing dummy connector). Modify test 40 delete file. Modify builders to add connectors in 2 folders
git-svn-id: http://compss.bsc.es/svn/compss/framework/trunk@2526 9ab3861e-6c05-4e1b-b5ef-99af60850597

diff --git a/tests/sources/basic/40-deleteFileJava/result b/tests/sources/basic/40-deleteFileJava/result
--- a/tests/sources/basic/40-deleteFileJava/result
+++ b/tests/sources/basic/40-deleteFileJava/result
@@ -1,14 +1,34 @@
 #!/bin/bash
 
-  #Obtain parameters
+  # Obtain parameters
   output_file=$1 
   target_log_folder=$2
   basedir=$3
+  
   # Log files
   runtime_log="${target_log_folder}/runtime.log"
-
+  
   #----------------------------------------------------------------------------------
   # Check output standard out status
+  if [ -f ${output_log} ]; then
+     result_expected="------------------------------------------------------------"
+     test_result=$(tail -1 ${output_file})
+     if [ "${result_expected}" != "${test_result}" ]; then
+        echo "SOME ERROR WAS FOUND. CHECK ERRORS ABOVE." | tee -a ${output_file}
+        exit 1
+     fi
+  else
+     echo "SOME ERROR WAS FOUND. CHECK ERRORS ABOVE." | tee -a ${output_file}
+     exit 1
+  fi
+  # Check that ErrorManager has not generated any ERROR or FATAL message.
+  if $(cat "${output_file}" "${runtime_log}" | tr '\n' ' ' | grep -E -q "[ERRMGR].*(ERROR|FATAL):.*.*Shutting"); then
+    echo "ERROR: ERRMGR RAISED A FATAL ERROR. TEST FAILED." | tee -a ${output_file}
+    exit 1
+  fi
+  
+  #----------------------------------------------------------------------------------
+  # Check executions
   if [ -f ${basedir}/counter_IN ]; then
         echo "ERROR WAS FOUND. counter_IN FILE STILL EXISTS." | tee -a ${output_file}
         exit 1
@@ -21,12 +41,7 @@
   else
      echo "FILE HAS BEEN REMOVED." | tee -a ${output_file}     
   fi
-  # Check that ErrorManager has not generated any ERROR or FATAL message.
-  if $(cat "${output_file}" "${runtime_log}" | tr '\n' ' ' | grep -E -q "[ERRMGR].*(ERROR|FATAL):.*.*Shutting"); then
-    echo "ERROR: ERRMGR RAISED A FATAL ERROR. TEST FAILED." | tee -a ${output_file}
-    exit 1
-  fi
 
   #---------------------------------------------------------------------------------- 
-  
+  # Everything ok
   exit 0
