add barbora installer and cfg

diff --git a/builders/scs/commons/buildSC_aux b/builders/scs/commons/buildSC_aux
--- a/builders/scs/commons/buildSC_aux
+++ b/builders/scs/commons/buildSC_aux
@@ -84,6 +84,7 @@
   extrae_with_impi=${12}
   impi_version=${13}
   autoparallel=${14}
+  c_binding=${15}
 
   SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
   TMP_DIR=${SCRIPT_DIR}/tmp
@@ -302,17 +303,20 @@
     exit $ev
   fi
   # - C binding
-  echo "- Deploying c-binding files"
-  cd "${TMP_DIR}"/compss/programming_model/bindings/c || exit 1
-  ./install "${targetDir}"/Bindings/c true
-  ev=$?
-  if [ $ev -ne 0 ]; then
-    echo "ERROR: Failed to install C-binding"
-    exit $ev
+  if [ "${c_binding}" == "true" ]; then
+    echo "- Deploying c-binding files"
+    cd "${TMP_DIR}"/compss/programming_model/bindings/c || exit 1
+    ./install "${targetDir}"/Bindings/c true
+    ev=$?
+    if [ $ev -ne 0 ]; then
+      echo "ERROR: Failed to install C-binding"
+      exit $ev
+    fi
+    mkdir -p "${targetDir}"/Runtime/scripts/system/c/
+    cp "${targetDir}"/Bindings/c/bin/* "${targetDir}"/Runtime/scripts/system/c
+    cp ./compss_build_app "${targetDir}"/Runtime/scripts/user/
   fi
-  mkdir -p "${targetDir}"/Runtime/scripts/system/c/
-  cp "${targetDir}"/Bindings/c/bin/* "${targetDir}"/Runtime/scripts/system/c
-  cp ./compss_build_app "${targetDir}"/Runtime/scripts/user/
+
   # - Python binding
   echo "- Deploying python-binding files"
   if [ "$unload_modules_before_python" != "ignore" ]; then
