Update builder scripts
git-svn-id: http://compss.bsc.es/svn/compss/framework/trunk@2308 9ab3861e-6c05-4e1b-b5ef-99af60850597

diff --git a/builders/scs/commons/buildSC_aux b/builders/scs/commons/buildSC_aux
--- a/builders/scs/commons/buildSC_aux
+++ b/builders/scs/commons/buildSC_aux
@@ -1,49 +1,62 @@
 #!/bin/bash
  
   #############################################################
-  # Name: buildMN_aux
-  # Description: SCRIPT FOR LOCAL COMPSs BUILD in MareNostrum
-  # Parameters: <targetDir> Base Target Installation folder
+  # Name: buildSC_aux
+  # Description: SCRIPT FOR LOCAL COMPSs BUILD in SuperComputers
+  # Parameters: <targetDir>           Base Target Installation folder
+  #             <modules>             Modules needed to perform installation
+  #             <additionalExports>   Additional exports to perform installation
+  #             <extrae_with_openmpi> Extrae with openmpi enabled
+  #             <openmpi_version>     OpenMPI module version
+  #             <extrae_with_impi>    Extrae with impi enabled
+  #             <impì_version>        IMPI module version
   #
   # ATTENTION: DO NOT EXECUTE THIS FILE. IT IS AUTOMATICALLY 
-  #            EXECUTED FROM buildMN script
+  #            EXECUTED FROM buildSC script
   #############################################################
 
   usage() {
     echo "Incorrect number of parameters"
-    echo " Usage: buildMN_aux <FullTargetPath>"
+    echo " Usage: buildSC_aux <FullTargetPath> <modules> <additionalExports> <extrae_with_openmpi> <openmpi_version> <extrae_with_impi> <impi_version>"
     echo " "
     exit 1
   }
-
 
   ####################
   # MAIN
   ####################
   # Get parameters
-  if [ $# -ne 1 ]; then
+  if [ $# -ne 7 ]; then
     usage
   fi
 
   # SET SCRIPT VARIABLES
   targetDir=$1
+  modules=$2
+  additionalExports=$3
+  extrae_with_openmpi=$4
+  openmpi_version=$5
+  extrae_with_impi=$6
+  impi_version=$7
+
   scriptDir=$(dirname $0)
   tmpDir=${scriptDir}/tmp
   
-  echo "- MN script Dir = ${scriptDir}"
-  echo "- MN tmp Dir    = ${tmpDir}"
-  echo "- MN target Dir = ${targetDir}"
+  echo "- SC script Dir = ${scriptDir}"
+  echo "- SC tmp Dir    = ${tmpDir}"
+  echo "- SC target Dir = ${targetDir}"
 
   # Load needed modules on MN
-  echo "- Load modules on MN account"
-  module load python/2.7.2 java boost
-  export BOOST_CPPFLAGS=-I$BOOST_INCLUDE 
+  echo "- Load modules on SC account"
+  module load ${modules}
   if [ $? -ne 0 ]; then
     echo "ERROR: Cannot load required modules"
     exit 1
   fi
-  export PATH=/apps/CEPBATOOLS/deps/libxml2/2.9.4/bin:$PATH
-  
+
+  # Load additional exports
+  ${additionalExports}
+
   # CREATE TARGET FOLDER
   echo "- Create target folder"
   rm -rf ${targetDir}
@@ -64,6 +77,7 @@
 
   # RUNTIME DEPLOYMENT
   echo "- Copy Runtime deployment files"
+
   #Doc
   echo "--- Copy docs"
   find ${tmpDir}/doc/ -name *.html | xargs rm -rf
@@ -73,45 +87,56 @@
   cp ${tmpDir}/NOTICE ${targetDir}
   cp ${tmpDir}/README ${targetDir}
   cp ${tmpDir}/RELEASE_NOTES ${targetDir}
+
   #Dependencies
   echo "--- Copy dependencies"
   cp -r ${tmpDir}/dependencies/JAVA_GAT ${targetDir}/Dependencies/
   cp -r ${tmpDir}/files/paraver ${targetDir}/Dependencies/
   cd ${tmpDir}/dependencies/extrae
+
+  echo "---- Install extrae ----"
   # Sequential installation
   ./install ${targetDir}/Dependencies/extrae false
   if [ $? -ne 0 ]; then
     echo "ERROR: Failed to install extrae sequential dependency"
     exit 1
   fi
+
   # OpenMPI
-  module load openmpi
-  ./install ${targetDir}/Dependencies/extrae-openmpi true
-  if [ $? -ne 0 ]; then
-    echo "ERROR: Failed to install extrae openmpi dependency"
-    exit 1
+  if [ "${extrae_with_openmpi}" == "true" ]; then
+    module load openmpi${openmpi_version}
+    ./install ${targetDir}/Dependencies/extrae-openmpi true
+    if [ $? -ne 0 ]; then
+      echo "ERROR: Failed to install extrae openmpi dependency"
+      exit 1
+    fi
+    module unload openmpi
   fi
+
   # IMPI
-  module unload openmpi
-  module load impi
-  ./install ${targetDir}/Dependencies/extrae-impi true
-  if [ $? -ne 0 ]; then
-    echo "ERROR: Failed to install extrae impi dependency"
-    exit 1
+  if [ "${extrae_with_impi}" == "true" ]; then  
+    module load impi${impi_version}
+    ./install ${targetDir}/Dependencies/extrae-impi true
+    if [ $? -ne 0 ]; then
+      echo "ERROR: Failed to install extrae impi dependency"
+      exit 1
+    fi
+    module unload impi
   fi
   cd ${scriptDir}
-  #Config
+
+  # Config
   echo "--- Copy configuration"
   find ${tmpDir}/compss/runtime/config -name src | xargs rm -rf
   find ${tmpDir}/compss/runtime/config -name target | xargs rm -rf
   find ${tmpDir}/compss/runtime/config -name pom.xml | xargs rm -rf
   cp -r ${tmpDir}/compss/runtime/config/* ${targetDir}/Runtime/configuration/
 
-  #Scripts
+  # Scripts
   echo "--- Copy scripts"
   cp -r ${tmpDir}/compss/runtime/scripts/* ${targetDir}/Runtime/scripts/
 
-  #Adaptors
+  # Adaptors
   echo "--- Copy adaptors"
   find ${tmpDir}/compss/runtime/adaptors -name pom.xml | xargs rm -rf
   rm -r ${tmpDir}/compss/runtime/adaptors/commons
@@ -138,7 +163,7 @@
     fi
   done
 
-  #Schedulers
+  # Schedulers
   echo "--- Copy schedulers"
   rm -r ${tmpDir}/compss/runtime/scheduler/commons
   schedulers=$(find ${tmpDir}/compss/runtime/scheduler/ -name "*.jar")
@@ -146,14 +171,14 @@
     cp $scheduler ${targetDir}/Runtime/scheduler/
   done
 
-  #Connectors
+  # Connectors
   echo "--- Copy connectors"
   connectors=$(find ${tmpDir}/compss/runtime/resources/ -name "*.jar")
   for conn in $connectors; do
     cp -f $conn ${targetDir}/Runtime/connectors/
   done
 
-  #Engine
+  # Engine
   echo "--- Copy engine"
   cp ${tmpDir}/compss/runtime/compss-engine.jar ${targetDir}/Runtime/
  
@@ -170,7 +195,7 @@
   cp ${tmpDir}/compss/tools/monitor/target/classes/server.xml ${targetDir}/Tools/monitor/apache-tomcat/conf/
   cp ${tmpDir}/compss/tools/monitor/target/classes/log4j.properties ${targetDir}/Tools/monitor/
 
-  #BINDINGS DEPLOYMENT
+  # BINDINGS DEPLOYMENT
   echo "- Deploying bindings-common files"
   cd ${tmpDir}/compss/programming_model/bindings/bindings-common
   ./install_common ${targetDir}/Bindings/bindings-common
