Constraints bugfixes. Contraints test update (fully enabled). Add inferred types to classes
git-svn-id: http://compss.bsc.es/svn/compss/framework/trunk@2118 9ab3861e-6c05-4e1b-b5ef-99af60850597

diff --git a/tests/sources/basic/05-constraintsTest/result_cloudManager b/tests/sources/basic/05-constraintsTest/result_cloudManager
--- a/tests/sources/basic/05-constraintsTest/result_cloudManager
+++ b/tests/sources/basic/05-constraintsTest/result_cloudManager
@@ -27,5 +27,14 @@
   fi
 
   #----------------------------------------------------------------------------------
-  #Compute result status  
+  #Compute result status
+  test_result_cloudmanager=$(cat ${output_file} | grep "\[LOG\] \* CloudManager test passed")
+  
+  #Report result status
+  if [ -z "${test_result_cloudmanager}" ]; then
+    echo "SOME ERROR WAS FOUND. CHECK ERRORS ABOVE." | tee -a ${output_file}
+    exit 2
+  fi
+  
   exit 0
+  
diff --git a/tests/sources/basic/05-constraintsTest/result_resourceManager_Available b/tests/sources/basic/05-constraintsTest/result_resourceManager_Available
--- a/tests/sources/basic/05-constraintsTest/result_resourceManager_Available
+++ b/tests/sources/basic/05-constraintsTest/result_resourceManager_Available
@@ -27,5 +27,13 @@
   fi
 
   #----------------------------------------------------------------------------------
-  #Compute result status  
+  #Compute result status
+  test_result_available_resources=$(cat ${output_file} | grep "\[LOG\] \* Available Resources test passed")
+  
+  #Report result status
+  if [ -z "${test_result_available_resources}" ]; then
+    echo "SOME ERROR WAS FOUND. CHECK ERRORS ABOVE." | tee -a ${output_file}
+    exit 2
+  fi
+  
   exit 0
