Add fixed implementation of nmmb
git-svn-id: http://compss.bsc.es/svn/compss/framework/trunk@2820 9ab3861e-6c05-4e1b-b5ef-99af60850597

diff --git a/tests/sources/devel_mpi/nmmb/deploy b/tests/sources/devel_mpi/nmmb/deploy
--- a/tests/sources/devel_mpi/nmmb/deploy
+++ b/tests/sources/devel_mpi/nmmb/deploy
@@ -1,15 +1,42 @@
 #!/bin/bash -e
-  
-  #Obtain parameter
-  source_base_dir=$1
-  target_base_dir=$2
-  
-  # Copy files
-  cp -f ${source_base_dir}/target/nmmb.jar ${target_base_dir}/nmmb.jar
-
-  cp -f ${source_base_dir}/project.xml ${target_base_dir}/project.xml                  
-  cp -f ${source_base_dir}/resources.xml ${target_base_dir}/resources.xml
-  
-  cp -f ${source_base_dir}/execution ${target_base_dir}/execution
-  cp -f ${source_base_dir}/result ${target_base_dir}/result 
  
+  usage() {
+    echo "Usage: $0 <targetMachine> <targetUser> <targetDir>"
+    echo "Example: $0 mn1.bsc.es bsc19533 /home/bsc19/bsc19533/nmmb/nmmb-bsc-ctm-v2.0/"
+    echo " "
+  }
+
+  # Get arguments
+  if [ $# -ne 3 ]; then
+    echo "Invalid arguments"
+    usage
+    exit 1
+  fi 
+  targetMachine=$1
+  targetUser=$2
+  targetDir=$3
+
+  # Clean and compile locally
+  mvn clean package
+
+  # Clean target machine
+  ssh ${targetUser}@${targetMachine} "rm -rf ${targetDir}/JOB"
+  ssh ${targetUser}@${targetMachine} "rm -rf ${targetDir}/nmmb.jar"
+  ssh ${targetUser}@${targetMachine} "rm -rf ${targetDir}/PREPROC"
+  ssh ${targetUser}@${targetMachine} "rm -rf ${targetDir}/POSTPROC"
+ 
+  # Deploy files
+  scp nmmb.jar ${targetUser}@${targetMachine}:${targetDir}
+  scp -r JOB ${targetUser}@${targetMachine}:${targetDir}
+  scp -r PREPROC ${targetUser}@${targetMachine}:${targetDir}
+  scp -r POSTPROC ${targetUser}@${targetMachine}:${targetDir} 
+
+  # Create symlinks
+  ssh ${targetUser}@${targetMachine} "ln -s ${targetDir}/DATA/STATIC/geodata ${targetDir}/PREPROC/geodata"
+  ssh ${targetUser}@${targetMachine} "ln -s ${targetDir}/DATA/STATIC/GTOPO30 ${targetDir}/PREPROC/GTOPO30"
+  ssh ${targetUser}@${targetMachine} "ln -s ${targetDir}/OUTPUT/GLOB/output ${targetDir}/PREPROC/output"
+
+  # END
+  echo "SUCCESS"
+  exit
+
