fix problematic grep in 1_tracing_hook_eval_python result evaluation

diff --git a/tests/sources/local/tools/1_tracing_hook_eval_python/result b/tests/sources/local/tools/1_tracing_hook_eval_python/result
--- a/tests/sources/local/tools/1_tracing_hook_eval_python/result
+++ b/tests/sources/local/tools/1_tracing_hook_eval_python/result
@@ -73,8 +73,9 @@
   fi
   # Check that ErrorManager has not generated any ERROR or FATAL message.
   if [ -f "${runtime_log_disabled}" ]; then
-    if cat "${output_file_disabled}" "${runtime_log_disabled}" | tr '\n' ' ' | grep -E -q "[ERRMGR].*(ERROR|FATAL):.*.*Shutting"; then
-      echo "ERROR: ERRMGR RAISED A FATAL ERROR. TEST FAILED." | tee -a "${output_file_disabled}"
+    err=$(cat "${output_file_disabled}" "${runtime_log_disabled}" | tr '\n' ' ' | grep -E "[ERRMGR].*(ERROR|FATAL):.*.*Shutting" || true)
+    if [ "${err}" != "" ]; then
+      echo "ERROR: ERRMGR RAISED A FATAL ERROR. TEST FAILED.\n Err: ${err}" | tee -a "${output_file_disabled}"
       exit 1
     fi
   else
