Capture ssh exit value

diff --git a/builders/scs/archer/buildArcher_aux b/builders/scs/archer/buildArcher_aux
--- a/builders/scs/archer/buildArcher_aux
+++ b/builders/scs/archer/buildArcher_aux
@@ -26,7 +26,7 @@
 
   # SET SCRIPT VARIABLES
   targetDir=$1
-  scriptDir=$(dirname $0)
+  SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
 
   # DEFINE MODULES
   modules="packages-archer PrgEnv-cray/5.2.56 java/jdk1.8.0_51 boost/1.55 python-compute/2.7.6 gcc/7.2.0"
@@ -47,6 +47,11 @@
 
   # CALL buildSC_aux
   "${SCRIPT_DIR}"/buildSC_aux "${targetDir}" "${modules}" "${unload_before_python}" "${py2_modules}" "${py3_modules}" "${py3_other_modules}" "${additionalExports}" "${additional_module_use_folder}" "${queues_cfg}" "${extrae_with_openmpi}" "${openmpi_version}" "${extrae_with_impi}" "${impi_version}" "${autoparallel}"
+  ev=$?
 
-  # END
+  # End
+  if [ $ev -ne 0 ]; then
+    echo "ERROR: Exception in auxiliar script"
+    exit $ev
+  fi
   exit 0
diff --git a/builders/scs/commons/buildSC b/builders/scs/commons/buildSC
--- a/builders/scs/commons/buildSC
+++ b/builders/scs/commons/buildSC
@@ -148,6 +148,11 @@
   SCauxScriptName=$(basename "${SCauxScript}")
   # shellcheck disable=2029
   ssh -t -t -o StrictHostKeyChecking=no -o BatchMode=yes -o ChallengeResponseAuthentication=no "${SCuser}"@"${SCloginNode}" "${PRELOAD_ENV} ${SCTMP_DIR}/${SCauxScriptName} ${SCtargetDir}"
+  ev=$?
+  if [ $ev -ne 0 ]; then
+    echo "ERROR: Exception raised executing auxiliar script"
+    exit 1
+  fi
 
   # ERASE TMP FILES
   echo "- Erase tmp files"
diff --git a/builders/scs/tx/buildTX_aux b/builders/scs/tx/buildTX_aux
--- a/builders/scs/tx/buildTX_aux
+++ b/builders/scs/tx/buildTX_aux
@@ -45,12 +45,21 @@
   impi_version=""
   autoparallel="false"
 
-  . /etc/profile.d/modules.sh  # Source
+  # shellcheck source=/etc/profile.d/modules.sh
+  # shellcheck disable=SC1091
+  source /etc/profile.d/modules.sh  # Source
 
   echo "- The module command has been loaded by sourcing /etc/profile.d/modules.sh"
 
   # CALL buildSC_aux
-  . "${SCRIPT_DIR}"/buildSC_aux "${targetDir}" "${modules}" "${unload_before_python}" "${py2_modules}" "${py3_modules}" "${py3_other_modules}" "${additionalExports}" "${additional_module_use_folder}" "${queues_cfg}" "${extrae_with_openmpi}" "${openmpi_version}" "${extrae_with_impi}" "${impi_version}" "${autoparallel}"
+  # shellcheck source=../commons/buildSC_aux
+  # shellcheck disable=SC1091
+  source "${SCRIPT_DIR}"/buildSC_aux "${targetDir}" "${modules}" "${unload_before_python}" "${py2_modules}" "${py3_modules}" "${py3_other_modules}" "${additionalExports}" "${additional_module_use_folder}" "${queues_cfg}" "${extrae_with_openmpi}" "${openmpi_version}" "${extrae_with_impi}" "${impi_version}" "${autoparallel}"
+  ev=$?
 
-  # END
+  # End
+  if [ $ev -ne 0 ]; then
+    echo "ERROR: Exception in auxiliar script"
+    exit $ev
+  fi
   exit 0
