Add parameter check on gengraph script
git-svn-id: http://compss.bsc.es/svn/compss/framework/trunk@3381 9ab3861e-6c05-4e1b-b5ef-99af60850597

Former-commit-id: d79e4215920c6157a6e2082a09d4e602256066ec

diff --git a/compss/runtime/scripts/user/gengraph b/compss/runtime/scripts/user/gengraph
--- a/compss/runtime/scripts/user/gengraph
+++ b/compss/runtime/scripts/user/gengraph
@@ -24,12 +24,20 @@
     fi
   }
 
+  usage() {
+    echo "ERROR: Incorrect number of parameters"
+    echo "Usage: $(dirname $0) <dotFile>"
+    exit 1
+  }
 
   ###################################
   # MAIN CODE
   ###################################
 
   # Get input dot file
+  if [ $# -ne 1 ]; then
+    usage
+  fi
   dotGraph=$1
 
   # Check dot version
