Add Action log by Scheduler. Add more things to test 48
git-svn-id: http://compss.bsc.es/svn/compss/framework/trunk@2693 9ab3861e-6c05-4e1b-b5ef-99af60850597

diff --git a/tests/sources/basic/48-schedulers/execution b/tests/sources/basic/48-schedulers/execution
--- a/tests/sources/basic/48-schedulers/execution
+++ b/tests/sources/basic/48-schedulers/execution
@@ -11,6 +11,15 @@
   # Global exit variable
   exitValue=0
   
+  # Compute folder for tests in terms of retryNum
+  NUM_TESTS=2
+  testNum=$(((retryNum - 1)*NUM_TESTS + 1))
+  
+  # Select number of tasks width and depth
+  TASK_WIDTH=6
+  TASK_DEPTH=2
+  INIT_VALUE=1
+  
   #----------------------------------------------------------------------------------
   # Generate Project.xml according to system
   sed -i '/<InstallDir>/c<InstallDir>'${IT_HOME}'<\/InstallDir>' ${base_app_dir}/project.xml
@@ -21,11 +30,14 @@
   mkdir -p /tmp/COMPSsWorker02/
   
   #----------------------------------------------------------------------------------
-  # Run application 48 - Schedulers
-  echo
-  echo "*** RUNNING JAVA APPLICATION SCHEDULERS"
-  output_log="${target_log_folder}/schedulers_0${retryNum}.outputlog"
-  error_log="${target_log_folder}/schedulers_0${retryNum}.errorlog"
+  # Run application 1 - Default Scheduler
+  echo " "
+  echo "*** RUNNING JAVA APPLICATION DEFAULT SCHEDULER"
+  
+  log_folder="${target_log_folder}/defaultScheduler"
+  mkdir -p ${log_folder}
+  output_log="${log_folder}/defaultScheduler_0${retryNum}.outputlog"
+  error_log="${log_folder}/defaultScheduler_0${retryNum}.errorlog"
   expectedTime=60s
   
   timeout --signal=2 $expectedTime ${COMPSs_exec} \
@@ -33,27 +45,72 @@
      --resources=${base_app_dir}/resources.xml \
      --debug \
      --comm=$comm \
+     -t \
      --classpath=${base_app_dir}/schedulers.jar \
-     schedulers.Main 1 > >(tee ${output_log}) 2> >(tee ${error_log} >&2)
+     schedulers.Main ${TASK_WIDTH} ${TASK_DEPTH} ${INIT_VALUE} > >(tee ${output_log}) 2> >(tee ${error_log} >&2)
   
   # Check timeout
   if [[ "$?" = "124" ]]; then
      # Copy LOG files
-     cp -rf ${COMPSs_log_folder}/schedulers.Main_0${retryNum}/* ${target_log_folder}
+     cp -rf ${COMPSs_log_folder}/schedulers.Main_0${testNum}/* ${log_folder}
      
      # Report time out
      echo "[WARNING] Java Application timed out" >> ${output_log}
-     exitValue=124
+     ev1=124
   else
      # Copy LOG files
-     cp -rf ${COMPSs_log_folder}/schedulers.Main_0${retryNum}/* ${target_log_folder}
+     cp -rf ${COMPSs_log_folder}/schedulers.Main_0${testNum}/* ${log_folder}
   
      # Check result
-     ${base_app_dir}/result ${output_log} ${target_log_folder} 
-     exitValue=$?
+     ${base_app_dir}/result_defaultScheduler ${output_log} ${log_folder} ${TASK_WIDTH} ${TASK_DEPTH} ${INIT_VALUE}
+     ev1=$?
+  fi
+  
+  #----------------------------------------------------------------------------------
+  # Run application 2 - FIFO Scheduler
+  echo " "
+  echo "*** RUNNING JAVA APPLICATION FIFO SCHEDULER"
+  
+  testNum=$((testNum + 1))
+  
+  log_folder="${target_log_folder}/fifoScheduler"
+  mkdir -p ${log_folder}
+  output_log="${log_folder}/fifoScheduler_0${retryNum}.outputlog"
+  error_log="${log_folder}/fifoScheduler_0${retryNum}.errorlog"
+  expectedTime=60s
+  
+  timeout --signal=2 $expectedTime ${COMPSs_exec} \
+     --project=${base_app_dir}/project.xml \
+     --resources=${base_app_dir}/resources.xml \
+     --debug \
+     --comm=$comm \
+     --scheduler=integratedtoolkit.scheduler.fifoScheduler.FIFOScheduler \
+     -t \
+     --classpath=${base_app_dir}/schedulers.jar \
+     schedulers.Main ${TASK_WIDTH} ${TASK_DEPTH} ${INIT_VALUE} > >(tee ${output_log}) 2> >(tee ${error_log} >&2)
+  
+  # Check timeout
+  if [[ "$?" = "124" ]]; then
+     # Copy LOG files
+     cp -rf ${COMPSs_log_folder}/schedulers.Main_0${testNum}/* ${log_folder}
+     
+     # Report time out
+     echo "[WARNING] Java Application timed out" >> ${output_log}
+     ev2=124
+  else
+     # Copy LOG files
+     cp -rf ${COMPSs_log_folder}/schedulers.Main_0${testNum}/* ${log_folder}
+  
+     # Check result
+     ${base_app_dir}/result_fifoScheduler ${output_log} ${log_folder} ${TASK_WIDTH} ${TASK_DEPTH} ${INIT_VALUE}
+     ev2=$?
   fi
   
   #----------------------------------------------------------------------------------
   # Return execution status
+  exitValue=$ev1
+  if [ $ev2 -ne 0 ]; then
+     exitValue=$ev2
+  fi
+  
   exit $exitValue
-
diff --git a/tests/sources/basic/48-schedulers/result_defaultScheduler b/tests/sources/basic/48-schedulers/result_defaultScheduler
--- a/tests/sources/basic/48-schedulers/result_defaultScheduler
+++ b/tests/sources/basic/48-schedulers/result_defaultScheduler
@@ -3,6 +3,9 @@
   #Obtain parameters
   output_file=$1 
   target_log_folder=$2
+  TASK_WIDTH=$3
+  TASK_DEPTH=$4
+  INIT_VALUE=$5
   
   # Log files
   runtime_log="${target_log_folder}/runtime.log"
@@ -28,17 +31,16 @@
 
   #---------------------------------------------------------------------------------- 
   # Compute result status
-  init_counter=$(cat ${output_file} | grep "\[INFO\] Creating task " | tr " " "\t" | awk {' print $(NF) '} | head -n 1)
-  final_counter_got=$(cat ${output_file} | grep "\[INFO\] Final counter value on file" | tr " " "\t" | awk {' print $(NF) '} | head -n 1)  
-  final_counter_expected=$((init_counter+2))
-
-  # Report result status
-  if [ "$final_counter_got" != "$final_counter_expected" ]; then
-     echo "ERROR ON TASKS SCHEDULE" | tee -a ${output_file}
-     echo "EXPECTED FIRST INCREMENT: $final_counter_expected" | tee -a ${output_file}
-     echo "GOT:      $final_counter_got" | tee -a ${output_file}
-     exit 1
-  fi
+  final_counter_expected=$((INIT_VALUE+TASK_DEPTH))
+  final_counters_got=$(cat ${output_file} | grep "\[INFO\] Final counter value on file" | tr " " "\t" | awk {' print $(NF) '})  
+  
+  for got in ${final_counters_got}; do
+    if [ "${got}" != "${final_counter_expected}" ]; then
+      echo "ERROR ON TASKS SCHEDULE" | tee -a ${output_file}
+      echo "EXPECTED: ${final_counter_expected}" | tee -a ${output_file}
+      echo "GOT:      ${got}" | tee -a ${output_file}
+      exit 1
+    fi
+  done
   
   exit 0
-  
