Add working dir to binary annotation. Bugfix on link files on gat sandbox. Add logger to streamGobbler. Bugfix on output/error capture for binary executors. Change MPI numProcs behaviour. Change -H option on mpirun. Remove -ib0 from nodenames in mpi call. Add scheduler tests. Change the -n and span options on the LSF queue configuration. Add try non-atomic move when atomic move fails. Fix NMMB UMO model mpi call.
git-svn-id: http://compss.bsc.es/svn/compss/framework/trunk@2851 9ab3861e-6c05-4e1b-b5ef-99af60850597

diff --git a/tests/sources/basic/48-schedulers/result_lifoScheduler b/tests/sources/basic/48-schedulers/result_lifoScheduler
--- a/tests/sources/basic/48-schedulers/result_lifoScheduler
+++ b/tests/sources/basic/48-schedulers/result_lifoScheduler
@@ -43,4 +43,73 @@
     fi
   done
   
+  #---------------------------------------------------------------------------------- 
+  # Compute scheduling status
+  pair1=$(cat ${target_log_folder}/trace/*.prv | grep "8000002" | tr ":" "\t" | awk {' print $NF '} | grep -v "^0" | head -n 2)
+  pair2=$(cat ${target_log_folder}/trace/*.prv | grep "8000002" | tr ":" "\t" | awk {' print $NF '} | grep -v "^0" | tail -n +3 | head -n 2)
+  pair3=$(cat ${target_log_folder}/trace/*.prv | grep "8000002" | tr ":" "\t" | awk {' print $NF '} | grep -v "^0" | tail -n +5 | head -n 2)
+  pair4=$(cat ${target_log_folder}/trace/*.prv | grep "8000002" | tr ":" "\t" | awk {' print $NF '} | grep -v "^0" | tail -n +7 | head -n 2)
+  pair5=$(cat ${target_log_folder}/trace/*.prv | grep "8000002" | tr ":" "\t" | awk {' print $NF '} | grep -v "^0" | tail -n +9 | head -n 2)
+  pair6=$(cat ${target_log_folder}/trace/*.prv | grep "8000002" | tr ":" "\t" | awk {' print $NF '} | grep -v "^0" | tail -n +11 | head -n 2)
+  
+  pair1Expected1=$'1\n2'
+  pair1Expected2=$'2\n1'
+  if [ "${pair1}" != "${pair1Expected1}" ] && [ "${pair1}" != "${pair1Expected2}" ]; then
+    echo "ERROR ON TASKS SCHEDULE ORDER 1" | tee -a ${output_file}
+    echo "EXPECTED1: ${pair1Expected1}" | tee -a ${output_file}
+    echo "EXPECTED2: ${pair1Expected2}" | tee -a ${output_file}
+    echo "GOT      : ${pair1}" | tee -a ${output_file}
+     exit 1
+  fi
+  
+  pair2Expected1=$'8\n7'
+  pair2Expected2=$'7\n8'
+  if [ "${pair2}" != "${pair2Expected1}" ] && [ "${pair2}" != "${pair2Expected2}" ]; then
+    echo "ERROR ON TASKS SCHEDULE ORDER 2" | tee -a ${output_file}
+    echo "EXPECTED1: ${pair2Expected1}" | tee -a ${output_file}
+    echo "EXPECTED2: ${pair2Expected2}" | tee -a ${output_file}
+    echo "GOT      : ${pair2}" | tee -a ${output_file}
+     exit 1
+  fi
+  
+  pair3Expected1=$'5\n6'
+  pair3Expected2=$'6\n5'
+  if [ "${pair3}" != "${pair3Expected1}" ] && [ "${pair3}" != "${pair3Expected2}" ]; then
+    echo "ERROR ON TASKS SCHEDULE ORDER 3" | tee -a ${output_file}
+    echo "EXPECTED1: ${pair3Expected1}" | tee -a ${output_file}
+    echo "EXPECTED2: ${pair3Expected2}" | tee -a ${output_file}
+    echo "GOT      : ${pair3}" | tee -a ${output_file}
+    exit 1
+  fi
+  
+  pair4Expected1=$'12\n11'
+  pair4Expected2=$'11\n12'
+  if [ "${pair4}" != "${pair4Expected1}" ] && [ "${pair4}" != "${pair4Expected2}" ]; then
+    echo "ERROR ON TASKS SCHEDULE ORDER 4" | tee -a ${output_file}
+    echo "EXPECTED1: ${pair4Expected1}" | tee -a ${output_file}
+    echo "EXPECTED2: ${pair4Expected2}" | tee -a ${output_file}
+    echo "GOT      : ${pair4}" | tee -a ${output_file}
+    exit 1
+  fi
+  
+  pair5Expected1=$'4\n3'
+  pair5Expected2=$'4\n3'
+  if [ "${pair5}" != "${pair5Expected1}" ] && [ "${pair5}" != "${pair5Expected2}" ]; then
+    echo "ERROR ON TASKS SCHEDULE ORDER 5" | tee -a ${output_file}
+    echo "EXPECTED1: ${pair5Expected1}" | tee -a ${output_file}
+    echo "EXPECTED2: ${pair5Expected2}" | tee -a ${output_file}
+    echo "GOT      : ${pair5}" | tee -a ${output_file}
+    exit 1
+  fi
+  
+  pair6Expected1=$'9\n10'
+  pair6Expected2=$'10\n9'
+  if [ "${pair6}" != "${pair6Expected1}" ] && [ "${pair6}" != "${pair6Expected2}" ]; then
+    echo "ERROR ON TASKS SCHEDULE ORDER 6" | tee -a ${output_file}
+    echo "EXPECTED1: ${pair6Expected1}" | tee -a ${output_file}
+    echo "EXPECTED2: ${pair6Expected2}" | tee -a ${output_file}
+    echo "GOT      : ${pair6}" | tee -a ${output_file}
+     exit 1
+  fi
+  
   exit 0
