Add new runtime annotations. Add support for ompss mpi opencl binary method tasks (up to invoker). Change gat invokations to support non-native tasks. Change nio task and implementations for non-native tasks. Add env_vars constraints. Refactor tests to work with new implementations. Solve bug on test 19 python. Add environment variables test. Add non-native tasks test
git-svn-id: http://compss.bsc.es/svn/compss/framework/trunk@2495 9ab3861e-6c05-4e1b-b5ef-99af60850597

diff --git a/tests/sources/basic/30-mpi/result b/tests/sources/basic/30-mpi/result
--- a/tests/sources/basic/30-mpi/result
+++ b/tests/sources/basic/30-mpi/result
@@ -25,7 +25,24 @@
     echo "ERROR: ERRMGR RAISED A FATAL ERROR. TEST FAILED." | tee -a ${output_file}
     exit 1
   fi
+  
+  #----------------------------------------------------------------------------------
+  # Check MPI task execution status
+  exitValue=0
+  
+  singleGOT=$(cat ${output_file} | grep "\[MPI\_SINGLE\] Received value from task is correct")
+  if [ -z "${singleGOT}" ]; then
+    echo "ERROR: Single MPI execution failed"
+    exitValue=1
+  fi
+  
+  multipleGOT=$(cat ${output_file} | grep "\[MPI\_MULTIPLE\] Received value from task is correct")
+  if [ -z "${multipleGOT}" ]; then
+    echo "ERROR: Multiple MPI execution failed"
+    exitValue=1
+  fi
+  
 
   #---------------------------------------------------------------------------------- 
-  # ALL OK. Report result status
-  exit 0
+  # Report result status
+  exit ${exitValue}
