Created two different task group constructors with and without barrier flag

diff --git a/tests/sources/python/2_task_groups/result b/tests/sources/python/2_task_groups/result
--- a/tests/sources/python/2_task_groups/result
+++ b/tests/sources/python/2_task_groups/result
@@ -52,8 +52,8 @@
 
   #----------------------------------------------------------------------------------
   # Compute result status
-  FILES=17
-  resultN=15
+  FILES=20
+  resultN=18
   FAILED=1
 
   # Checks if the file has been written as many times as expected
@@ -77,14 +77,21 @@
   # Check if the tasks have failed
   output1=$(grep -c "Task failure:" "${runtime_log}")
   if [ "${output1}" -ne "${FAILED}" ]; then
-  	echo "ERROR: A task has not failed."
+  	echo "ERROR: The number of failed tasks is not correct."
   	exit 1
   fi
 
   # Check if all successors have been canceled
   output1=$(cat "${runtime_log}" | grep "Task canceled:" | wc -l)
-  if [ ${output1} -ne 2 ]; then
-  	echo "ERROR: All tasks have not been canceled."
+  if [ ${output1} -ne 4 ]; then
+  	echo "ERROR: The number of canceled tasks is not correct."
+  	exit 1
+  fi
+
+  # Check if the tasks have failed
+  output1=$(grep -c "OMPSs Exception raised :" "${runtime_log}")
+  if [ "${output1}" -ne 2 ]; then
+  	echo "ERROR: The number of COMPSsExceptions raised is not correct."
   	exit 1
   fi
 
