Changed result of python test

diff --git a/tests/sources/python/2_task_groups/result b/tests/sources/python/2_task_groups/result
--- a/tests/sources/python/2_task_groups/result
+++ b/tests/sources/python/2_task_groups/result
@@ -10,50 +10,54 @@
   runtime_log="${target_log_folder}/runtime.log"
   resources_log="${target_log_folder}/resources.log"
 
-  # Default checker (application ends with : Error running application)
+  #----------------------------------------------------------------------------------
+  # Check output standard out status
   if [ -f "${output_file}" ]; then
-     result_expected="Error running application"
-     test_result=$(tail -n 2 < "${output_file}" | head -n 1)
+     result_expected="------------------------------------------------------------"
+     test_result=$(tail -1 "${output_file}")
      if [ "${result_expected}" != "${test_result}" ]; then
-        echo "[ERROR] SOME ERROR WAS FOUND. CHECK ERRORS ABOVE." | tee -a "${output_file}"
+        echo "SOME ERROR WAS FOUND. CHECK ERRORS ABOVE." | tee -a "${output_file}"
         exit 1
      fi
   else
      echo "[ERROR] Output file not found" | tee -a "${output_file}"
      exit 1
   fi
-
-  # Check that ErrorManager has raised any ERROR or FATAL message
+  # Check that ErrorManager has not raised any ERROR or FATAL message
   if [ -f "${error_file}" ]; then
     if grep -E "\\[ERRMGR\\].*(ERROR|FATAL|Shutting down COMPSs)" "${error_file}"; then
-       echo "[RESULT_CHECKER] ErrorManager raised and ERROR as expected" | tee -a "${output_file}"
-    else
-      echo "[ERROR] ErrorManager did not raise any error" | tee -a "${output_file}"
+      echo "ERROR: ErrorManager has raised a fatal error" | tee -a "${output_file}"
       exit 1
     fi
   else
-    echo "[ERROR] ErrorManager did not raise any error" | tee -a "${output_file}"
-    exit 1
+    # Empty error file, no exceptions could have been raised
+    :
   fi
-
-  #----------------------------------------------------------------------------------
-  # Compute result status
-  FILES=15
-  resultN=12
-  FAILED=1
-
-  # Check that the Runtime has registered any fatal error
+  # Check that the Runtime has not registered any fatal error
   if [ -f "${runtime_log}" ]; then
     if grep -E "ErrorManager\\].*\\[ERRMGR\\].*Error detected. Shutting down COMPSs" "${runtime_log}"; then
-      echo "[RESULT_CHECKER] ErrorManager registered an ERROR as expected" | tee -a "${output_file}"
-    else
-      echo "[ERROR] ErrorManager did not register any error" | tee -a "${output_file}"
+      echo "ERROR: ErrorManager has registered a fatal error in the runtime.log" | tee -a "${output_file}"
       exit 1
     fi
   else
     echo "[ERROR] runtime.log not found" | tee -a "${output_file}"
     exit 1
   fi
+
+  #----------------------------------------------------------------------------------
+  # Grep for unit test errors (ERROR or FAIL)
+  errors=$(cat "${output_file}" "${error_file}" | grep "ERROR" | cat)
+  fails=$(cat "${output_file}" "${error_file}" | grep "FAIL" | cat)
+  if [ "${errors}" != "" ] || [ "${fails}" != "" ]; then
+      echo "ERROR: UNIT TEST RAISED AN ERROR." | tee -a "${output_file}"
+      exit 1
+  fi
+
+  #----------------------------------------------------------------------------------
+  # Compute result status
+  FILES=14
+  resultN=12
+  FAILED=1
 
   # Checks if the file has been written as many times as expected
   result=$(cat /tmp/sharedDisk/taskGROUPS.txt)
@@ -73,10 +77,10 @@
     exit 1
   fi
 
-  # Check if the task has failed
-  output1=$(cat "${runtime_log}" | grep "TOTALLY FAILED" | wc -l)
+  # Check if the tasks have failed
+  output1=$(cat "${runtime_log}" | grep "Task failure:" | wc -l)
   if [ "${output1}" -ne "${FAILED}" ]; then
-  	echo "ERROR: The task has not failed."
+  	echo "ERROR: A task has not failed."
   	exit 1
   fi
 
