Add JVM Library lookup like runcompss
git-svn-id: http://compss.bsc.es/svn/compss/framework/trunk@2657 9ab3861e-6c05-4e1b-b5ef-99af60850597

diff --git a/compss/programming_model/bindings/bindings-common/install_common b/compss/programming_model/bindings/bindings-common/install_common
--- a/compss/programming_model/bindings/bindings-common/install_common
+++ b/compss/programming_model/bindings/bindings-common/install_common
@@ -22,7 +22,14 @@
     echo "Please define \$JAVA_HOME"
     exit 1
   fi
-  export JAVA_LIB_DIR=${JAVA_HOME}/jre/lib/amd64/server
+
+  # Look for the JVM Library                                                                                                                                                            
+  libjava=$(find ${JAVA_HOME}/jre/lib/ -name libjvm.so | head -n 1)
+  if [ -z "$libjava" ]; then
+    echo "Cannot find JVM Library"
+    exit 1
+  fi
+  export JAVA_LIB_DIR=$(dirname $libjava)
 
   # Install and deploy on scriptDir (for C binding)
   echo "Install on scriptDir = $scriptDir for Bindings compilation"
