Add support for C/C++ binding

diff --git a/compss/programming_model/bindings/tmp/c/compss_build_app b/compss/programming_model/bindings/tmp/c/compss_build_app
--- a/compss/programming_model/bindings/tmp/c/compss_build_app
+++ b/compss/programming_model/bindings/tmp/c/compss_build_app
@@ -1,15 +1,21 @@
 #!/bin/bash
 
-
 # FUNCTIONS DECLARATION
 #---------------------------------------------------
 show_opts() {
   cat <<EOT
-  General Options:
+  General options:
     --only-master                           Builds only the master part
                                             Default: Disabled
     --only-worker                           Builds only the worker part
                                             Default: Disabled
+  Environment options:
+    --java_home                             Specifies the home of the java version
+                                            to be used, environment variable JAVA_HOME used.
+                                            Default: $JAVA_HOME
+    --boostlib                              Specifies the path of the boost libraries 
+                                            to be used, environment variable BOOST_LIB used.
+                                            Default: $BOOST_LIB
   Tools enablers:
     --ompss                                 Enables worker compilation with OmpSs Mercurium compiler
                                             Default: Disabled
@@ -17,8 +23,13 @@ show_opts() {
                                             Default: Disabled
     --opencl                                Enables worker compilation with openCL compilation flags
                                             Default: Disabled
+  Specific cross compile flags:
+    --cross-compile                         Enables cross compilation.
+                                            Default: Disabled
+    --cross-compile-prefix                  Prefix to be used when cross compiling, the environment variable CROSS_COMPILE
+                                            is used to define the prefix if not set specifically.
+                                            Default: $CROSS_COMPILE
   Autotools and Makefile options:
-
     --goals=goal_1,goal_2,...,goal_N        Instead of using the goal all it uses the goals provided in the given order.
                                             Default: all
 
@@ -28,7 +39,7 @@ show_opts() {
     --CC=<C compiler>                       Defines and specific C compiler (cross_compiling)
                                             Default: $CC
     --CFLAGS="-cFlag_1 ... -cFlag_N"        Defines C compiler flags
-					    Default: $CFLAGS
+					                        Default: $CFLAGS
     --CXXFLAGS="-cxxflag_1 ... -cxxflag_N"  Defines C++ compiler flags
                                             Default: $CXXFLAGS
     --CPPFLAGS="-cppflag_1 ... -cppflag_N"  Defines C pre-processor flags
@@ -51,8 +62,8 @@ show_opts() {
                                             Default: Disabled
     --with_opencl=<ocl_installation_path>   Enables worker compilation with openCL installed in a certain location
                                             Default: Disabled
-    --opencl_libs="libs"		    Specifies extra opencl libraries locations
-					    Default: Empty
+    --opencl_libs="libs"                    Specifies extra opencl libraries locations
+                                            Default: Empty
 EOT
 }
 
@@ -86,7 +97,8 @@ display_error() {
 
   echo "$error_msg"
   echo " "
-
+ 
+  exit $exitCode
   #usage $exitCode 
 }
 
@@ -144,7 +156,13 @@ get_args() {
           only-worker)
             #Compile only the worker
            	ONLY_WORKER=true
+            ;;
+          java_home=*)
+            java_home=${OPTARG//java_home=/} 
             ;; 
+          boostlib=*)
+            boostlib=${OPTARG//boostlib=/}
+            ;;
 	     instrument)
             instrument=1
             ;;
@@ -160,8 +178,14 @@ get_args() {
           goals=*)
             goals=${OPTARG//goals=/}
             ;;
+          cross-compile)
+            enable_cross=true
+            ;;
+          cross-compile-prefix=*)
+            CROSS_COMPILE_PREFIX=${OPTARG//cross-compile-prefix=/}
+            ;;
           CC=*)
-	    defined_cc=${OPTARG//CC=/}
+	        defined_cc=${OPTARG//CC=/}
             ;;
           CXX=*)
             defined_cxx=${OPTARG//CXX=/}
@@ -240,12 +264,50 @@ get_goals() {
 }
 
 check_args() {
-    #Check whether you are going to compile both master and worker or one of them
 
+    local javapath=""
+    if [ -z "$java_home" ]; then
+        # Setting Java folder
+        if [ -z "$JAVA_HOME" ]; then
+            display_error "[Error] Set \$JAVA_HOME or either use the --java_home argument."
+        fi
+        libjava=$(find "${JAVA_HOME}"/jre/lib/ -name libjvm.so | head -n 1)
+        javapath=$JAVA_HOME
+    else
+        libjava=$(find "${java_home}"/jre/lib/ -name libjvm.so | head -n 1)
+        javapath=$java_home
+    fi
+   
+    if [ -z "$libjava" ]; then
+        display_error "[Error] Could not find the libjvm.so in $javapath" 1
+    fi
+    export LIBJAVAFOLDER=$(dirname "$libjava")
+
+    echo "[Info] Java libraries are searched in the directory: $LIBJAVAFOLDER"
+
+    local boostpath
+    if [ -z "$boostlib" ]; then
+        if [ -z "$BOOST_LIB" ]; then
+            if [ -z "$LD_LIBRARY_PATH"  ]; then
+                boostpath="/usr/lib/"
+            else
+                boostpath=$LD_LIBRARY_PATH
+            fi
+        else
+            boostpath=$BOOST_LIB
+        fi
+    else
+        export BOOST_LIB="$boostlib"
+        boostpath="$boostlib" 
+    fi
+
+    echo "[Info] Boost libraries are searched in the directory: $boostpath"
+
+    #Check whether you are going to compile both master and worker or one of them
     if [ "$ONLY_MASTER" = true ] && [ "$ONLY_WORKER" = true ]; then
 
         echo " "
-        echo "Error: Is not possible to specify both options --only-master and --only-worker, to compile both remove these arguments."
+        echo "[Error] Is not possible to specify both options --only-master and --only-worker, to compile both remove these arguments."
         
         exit 1
 
@@ -254,7 +316,7 @@ check_args() {
     if [ -z "$ompss_enabled" ] && [ -n "$cuda_enabled" ] && [ $cuda_enabled -eq 1 ]; then
 
         echo " "
-        echo "Warning: Is not possible to use the --cuda option while not using the --ompss one, removing --cuda..."
+        echo "[Warning] Is not possible to use the --cuda option while not using the --ompss one, removing --cuda..."
         cuda_enabled="" 
     
     fi 
@@ -264,6 +326,33 @@ check_args() {
         goals=$processed
     fi
 
+    if [ "$enable_cross" == "true" ]; then
+        if [ -z "${CROSS_COMPILE}" ]; then
+            CROSS_COMPILE=${CROSS_COMPILE_PREFIX}
+        fi
+        #At this point, if you defined a prefix, it will be set, if you enabled cross-compile 
+        #but you did not exported CROSS_COMPILE, no effect is expected from the option.
+        echo "[Info] You enabled cross-compile and the prefix to be used is: ${CROSS_COMPILE}"
+
+    else
+        CROSS_COMPILE=""
+    fi
+}
+
+set_target_host() {
+        #To use GNU tools, such as configure, we have to specify a target; environment variable TARGET_HOST will do the trick.
+        if [ -z "${TARGET_HOST}" && "${enable_cross}" ]; then
+            #If not defined, we assume that your currently CC or CXX configured (the want you are going to use to build)
+            #has the details of what architecture is the one we are targeting.
+            export TARGET_HOST=$(${CC} -dumpmachine)
+            local retVal=$?
+
+            if [ $retVal -ne 0 ]; then
+                display_error "[Error] Not possible to get the target host with the ${CC} -dumpmachine command. Alternatively, define the target host with the environment variable TARGET_HOST ." 1
+            fi
+
+            echo "[Info] The target host is: ${TARGET_HOST}"
+        fi
 }
 
 ONLY_MASTER=false
@@ -298,16 +387,6 @@ if [ $instrument -eq 1 ]; then
   ompss_flags="${ompss_flags} --instrument"
 fi
 
-# Setting Java folder
-libjava=$(find "${JAVA_HOME}"/jre/lib/ -name libjvm.so | head -n 1)
-if [ -z "$libjava" ]; then
-  libjava=$(find "${JAVA_HOME}"/jre/lib/ -name libjvm.dylib | head -n 1)
-  if [ -z "$libjava" ]; then
-    display_error "${JAVA_JRE_ERROR}" 1
-  fi
-fi
-LIBJAVAFOLDER=$(dirname "$libjava")
-export LIBJAVAFOLDER
 
 # GS HOME
 if [ -z "$CS_HOME" ]; then
@@ -319,18 +398,6 @@ if [ -z "$CS_HOME" ]; then
 fi
 export COMPSSGEN=$CS_HOME/bin/compss_generator
 
-# Application src compilation
-if [ -d "./src" ]; then
-  (
-  cd ./src || exit 1
-  make $goals)
-  ev=$?
-  if [ $ev -ne 0 ]; then 
-    echo " "
-    echo "Building user application failed, please check errors above!"
-    exit $ev
-  fi
-fi
 # Building Master and Worker
 if [ -z "${defined_cc}" ]; then
    if [ -z "$CC" ]; then
@@ -339,7 +406,7 @@ if [ -z "${defined_cc}" ]; then
 	defined_cc=$CC
    fi
 fi
-export CC=${defined_cc}
+export CC=${CROSS_COMPILE}${defined_cc}
 
 if [ -z "${defined_cxx}" ]; then
    if [ -z "$CXX" ]; then
@@ -348,7 +415,7 @@ if [ -z "${defined_cxx}" ]; then
         defined_cxx=$CXX
    fi
 fi
-export CXX=${defined_cxx}
+export CXX=${CROSS_COMPILE}${defined_cxx}
 
 if [ ! -z "${defined_cflags}" ]; then
    export CFLAGS="${defined_cflags}"
@@ -370,8 +437,79 @@ if [ ! -z "${defined_libs}" ]; then
    export LIBS="${defined_libs}"
 fi
 
-if [ "$ONLY_WORKER" = false ]; then
+if [ "${ompss_enabled}" != "" ]; then
+  # Flag is defined, check value
+  if [ ${ompss_enabled} == 1 ]; then
+	if [ -z "${defined_mcc}" ]; then
+	    if [ -z "${MCC}" ]; then
+	       defined_mcc="mcc"
+		else
+	       defined_mcc=${MCC}
+		fi
+	fi
+	export CC=${CROSS_COMPILE}${defined_mcc}
+	
+	if [ -z "${defined_mcxx}" ]; then
+		if [ -z "${MCXX}" ]; then
+		   defined_mcxx="mcxx"
+		else
+		   defined_mcxx=${MCXX}
+		fi
+	fi
+	export CXX=${CROSS_COMPILE}${defined_mcxx}
 
+	export CFLAGS="$CFLAGS --ompss ${ompss_flags} $COMPSS_MCXX_FLAGS"
+	export CXXFLAGS="$CXXFLAGS --ompss ${ompss_flags} $COMPSS_MCXX_FLAGS"
+	export CPPFLAGS="$CPPFLAGS -DOMPSS_ENABLED"
+
+  fi
+fi
+
+if [ "${cuda_enabled}" != "" ]; then
+  # Flag is defined, check value
+  if [ ${cuda_enabled} == 1 ]; then
+	if [ -z "${cuda_prefix}" ]; then
+		if [ -z "$CUDA_HOME" ]; then
+		   export CUDA_HOME=/usr/local/cuda/
+		fi
+	else
+		export CUDA_HOME=${cuda_prefix}
+	fi
+	export PATH=$PATH:${CUDA_HOME}/bin
+	export LDFLAGS="--cuda $LDFLAGS"
+	export LIBS="-L${CUDA_HOME}/lib64 -lcudart $LIBS"
+	export CFLAGS="$CFLAGS --cuda"
+	export CXXFLAGS="$CXXFLAGS --cuda"
+  fi
+fi
+
+if [ "${opencl_enabled}" != "" ]; then
+  # Flag is defined, check value
+  if [ ${opencl_enabled} == 1 ]; then
+	# Altera ocl flags export LDADD="$LDADD -L/home/altera/16.0.2/hld/linux64/lib -L/opt/intel_deliverable_WW49_16/bdw_fpga_pilot_opencl_bsp_v1.0/host/linux64/lib    -lalterahalmmd -laltera_qpi_mmd  -laalrt  -L/opt/aalsdk/aalsdk-5.0.2/lib"    
+	export LDFLAGS="--opencl $LDFLAGS ${opencl_libraries}"
+	export LIBS="$LIBS ${opencl_libraries}"
+	export CFLAGS="$CFLAGS --opencl"
+	export CXXFLAGS="$CXXFLAGS --opencl"
+  fi
+fi
+
+set_target_host #Tell GNU tools the target host of the build
+
+# Application src compilation
+if [ -d "./src" ]; then
+  (
+  cd ./src || exit 1
+  make $goals)
+  ev=$?
+  if [ $ev -ne 0 ]; then 
+    echo " "
+    echo "Building user application failed, please check errors above!"
+    exit $ev
+  fi
+fi
+
+if [ "$ONLY_WORKER" = false ]; then
 	# shellcheck disable=SC2086
 	"$CS_HOME"/bin/compss_build build master ${other_args}
 	ev=$?
@@ -379,58 +517,6 @@ if [ "$ONLY_WORKER" = false ]; then
 	  echo " "
 	  echo "Building binding failed, please check errors above!"
 	  exit $ev
-	fi
-	if [ "${ompss_enabled}" != "" ]; then
-	  # Flag is defined, check value
-	  if [ ${ompss_enabled} == 1 ]; then
-		if [ -z "${defined_mcc}" ]; then
-		if [ -z "${MCC}" ]; then
-		   defined_mcc="mcc"
-			else
-		   defined_mcc=${MCC}
-			fi
-		fi
-		export CC=${defined_mcc}
-		
-		if [ -z "${defined_mcxx}" ]; then
-			if [ -z "${MCXX}" ]; then
-			   defined_mcxx="mcxx"
-			else
-			   defined_mcxx=${MCXX}
-			fi
-		fi
-		export CXX=${defined_mcxx}
-		export CFLAGS="$CFLAGS --ompss ${ompss_flags} $COMPSS_MCXX_FLAGS"
-		export CXXFLAGS="$CXXFLAGS --ompss ${ompss_flags} $COMPSS_MCXX_FLAGS"
-		export CPPFLAGS="$CPPFLAGS -DOMPSS_ENABLED"
-	  fi
-	fi
-	if [ "${cuda_enabled}" != "" ]; then
-	  # Flag is defined, check value
-	  if [ ${cuda_enabled} == 1 ]; then
-		if [ -z "${cuda_prefix}" ]; then
-			if [ -z "$CUDA_HOME" ]; then
-			   export CUDA_HOME=/usr/local/cuda/
-			fi
-		else
-			export CUDA_HOME=${cuda_prefix}
-		fi
-		export PATH=$PATH:${CUDA_HOME}/bin
-		export LDFLAGS="--cuda $LDFLAGS"
-		export LIBS="-L${CUDA_HOME}/lib64 -lcudart $LIBS"
-		export CFLAGS="$CFLAGS --cuda"
-		export CXXFLAGS="$CXXFLAGS --cuda"
-	  fi
-	fi
-	if [ "${opencl_enabled}" != "" ]; then
-	  # Flag is defined, check value
-	  if [ ${opencl_enabled} == 1 ]; then
-		# Altera ocl flags export LDADD="$LDADD -L/home/altera/16.0.2/hld/linux64/lib -L/opt/intel_deliverable_WW49_16/bdw_fpga_pilot_opencl_bsp_v1.0/host/linux64/lib    -lalterahalmmd -laltera_qpi_mmd  -laalrt  -L/opt/aalsdk/aalsdk-5.0.2/lib"    
-		export LDFLAGS="--opencl $LDFLAGS ${opencl_libraries}"
-		export LIBS="$LIBS ${opencl_libraries}"
-		export CFLAGS="$CFLAGS --opencl"
-		export CXXFLAGS="$CXXFLAGS --opencl"
-	  fi
 	fi
 fi
 
