Test for bad process killing after compilation error created

diff --git a/tests/sources/basic/84-kill_processes_python/result b/tests/sources/basic/84-kill_processes_python/result
--- a/tests/sources/basic/84-kill_processes_python/result
+++ b/tests/sources/basic/84-kill_processes_python/result
@@ -8,37 +8,20 @@
   # Log files
   runtime_log="${target_log_folder}/runtime.log"
 
-  #----------------------------------------------------------------------------------
-  # Check output standard out status
-  if [ -f ${output_file} ]; then
-     result_expected="------------------------------------------------------------"
-     test_result=$(tail -1 ${output_file})
-     if [ "${result_expected}" != "${test_result}" ]; then
-        echo "SOME ERROR WAS FOUND. CHECK ERRORS ABOVE." | tee -a ${output_file}
-        exit 1
-     fi
-  else
-     echo "SOME ERROR WAS FOUND. CHECK ERRORS ABOVE." | tee -a ${output_file}
-     exit 1
-  fi
-  # Check that ErrorManager has not generated any ERROR or FATAL message.
-  if $(cat "${output_file}" "${runtime_log}" | tr '\n' ' ' | grep -E -q "[ERRMGR].*(ERROR|FATAL):.*.*Shutting"); then
-    echo "ERROR: ERRMGR RAISED A FATAL ERROR. TEST FAILED." | tee -a ${output_file}
-    exit 1
-  fi
-
-  #---------------------------------------------------------------------------------- 
-  # Compute result status
-  init_counter=$(cat ${output_file} | grep "Initial counter value" | cut -c 26-)
-  final_counter_got=$(cat ${output_file} | grep "Final counter value" | cut -c 24-)
-  final_counter_expected=$((init_counter+1))
+  # We avoid looking for the result of the test because it doesn't matter
+  # it's just a matter of isolated processes when the Python code has an error
 
   # Report result status
-  if [ "$final_counter_got" != "$final_counter_expected" ]; then
-     echo "ERROR ON TASKS SCHEDULE" | tee -a ${output_file}
-     echo "EXPECTED FIRST INCREMENT: $final_counter_expected" | tee -a ${output_file}
-     echo "GOT:      $final_counter_got" | tee -a ${output_file}
-     exit 1
+  # If there is more than one process that matches with compss-adaptors-nio-worker.jar (take a look to the path above)
+  # the test fails, note that the grep it's showed when the ps -ef is executed, that's why we compare with a 1 
+
+  to_wait=10 #seconds to timeout the script
+  to_match="${COMPSS_HOME}/Runtime/scripts/system/adaptors/nio/../../../../adaptors/nio/worker/compss-adaptors-nio-worker.jar"
+  timeout --signal=15 --preserve-status $to_wait ./process_checker $to_match  
+
+  if [ "$?" -ne "0" ]; then
+	echo "[TEST] SOME PROCESSES STILL ALIVE AFTER TEST EXECUTION." | tee -a ${error_file}
+	exit 1
   fi
 
   exit 0
