Remove unused scripts on utils (deprecated). Update main_distribution script to join distr and sc workflow
git-svn-id: http://compss.bsc.es/svn/compss/framework/trunk@3316 9ab3861e-6c05-4e1b-b5ef-99af60850597

Former-commit-id: 57f205af4d7ddfe678efb9cac0c2c7b76efc6dc2

diff --git a/utils/scripts/main_distribution b/utils/scripts/main_distribution
--- a/utils/scripts/main_distribution
+++ b/utils/scripts/main_distribution
@@ -17,29 +17,6 @@
     echo " "
   }
 
-  clean() {
-    # Clean test environment
-    if [ "${cfgFile}" != "" ]; then
-      # We must clean the test environment
-      #rm -f ${cfgFile}
-      rm -rf ~/.COMPSs/
-      sudo sh ${trunk_base}/tests/scripts/configure_hosts_remove
-      if [ $? -ne 0 ]; then
-        display_error "Cannot remove hosts after execution"
-      fi
-    fi
-
-    # Unninstall COMPSs if needed
-    local unninstaller_script=${script_dir}/installation/unninstall_compss_${distr}.sh
-    sudo sh ${unninstaller_script}
-    if [ $? -ne 0 ]; then
-      echo "------------------------- WARNING -----------------------------"
-      echo "Unninstall script failed on ${distr} either because"
-      echo "COMPSs was not installed or because there was an internal error"
-      echo "---------------------------------------------------------------"
-    fi
-  }
-
   set_env() {
     # Define jenkins job and path
     if [ "${distr}" == "ubuntu" ]; then
@@ -59,25 +36,31 @@
     JENKINS_PACKAGES_PATH="/home/jenkins/jobs/${JENKINS_JOB}/workspace/builders/packages/"
 
     # Define user variables
-    trunk_base=${script_dir}/../../				   # Base trunk folder
-    log_base_folder=${trunk_base}/logs/                            # Folder to store logs
+    trunk_base="${script_dir}/../../"				   # Base trunk folder
+    log_base_folder="${trunk_base}/logs/"                            # Folder to store logs
 
-    log_folder=${log_base_folder}/${distr}
-    specs_base_folder=${trunk_base}/builders/specs/		   # Folder to run package building scripts
-    package_base_folder=${trunk_base}/builders/packages/           # Folder to store packages and upload them to repository
+    log_folder="${log_base_folder}/${distr}"
+    specs_base_folder="${trunk_base}/builders/specs/"		   # Folder to run package building scripts
+    package_base_folder="${trunk_base}/builders/packages/"           # Folder to store packages and upload them to repository
 
     # Create package base folder if needed
-    mkdir -p ${package_base_folder}
+    mkdir -p "${package_base_folder}"
 
     # Wipe and create log folder
-    rm -rf ${log_folder}
-    mkdir -p ${log_folder}
+    rm -rf "${log_folder}"
+    mkdir -p "${log_folder}"
 
     # Set full log output file
-    full_log=${log_folder}/full_exec.log
+    full_log="${log_folder}/full_exec.log"
   }
 
   exec_distribution() {
+    # Setup VM
+    setup_vm
+
+    # Add trap for clean
+    trap clean_vm EXIT
+
     # Compile COMPSs
     compile
 
@@ -96,11 +79,21 @@
     # Update to testing repo
     update_repo "testing"
 
-    # Clean VM
-    # TODO clean_vm
+    # END
+    echo " "
+    echo " CONGRATULATIONS! The ${distr} process succeeded"
+    echo " "
+  }
 
-    # Perform live snapshot
-    # TODO snapshot
+  exec_sc() {
+    # Create packages
+    create_packages_sc
+
+    # Update to unstable repo
+    update_repo_from_master "unstable"
+
+    # Update to testing repo
+    update_repo_from_master "testing"
 
     # END
     echo " "
@@ -110,8 +103,23 @@
 
 
   #---------------------------------------------------------------------------------------------------------------------
-  # SECOND LEVEL FUNCTIONS
+  # SECOND LEVEL FUNCTIONS FOR GENERIC DISTRIBUTION
   #---------------------------------------------------------------------------------------------------------------------
+  setup_vm() {
+    echo -e "\e[0m"
+    echo "**************************"
+    echo "***      Setup VM      ***"
+    echo "**************************"
+    echo -e "\e[0m"
+
+    echo "-- Setting up VM hosts..."
+    sudo "${trunk_base}/tests/scripts/configure_hosts_insert"
+    if [ $? -ne 0 ]; then
+      display_error "Cannot configure hosts before tests"
+      exit 1
+    fi
+  }
+
   compile() {
     echo -e "\e[0m"
     echo "**************************"
@@ -119,13 +127,13 @@
     echo "**************************"
     echo -e "\e[0m"
 
-    cd ${trunk_base}
+    cd "${trunk_base}" || exit 1
     mvn -U clean install
     if [ $? -ne 0 ]; then
       display_error "Cannot compile COMPSs SVN Revision"
       exit 1
     fi
-    cd ${script_dir}
+    cd "${script_dir}" || exit 1
   }
 
   create_packages() {
@@ -136,21 +144,21 @@
     echo -e "\e[0m"
 
     if [[ ${DEBIAN_DISTRS} == *"${distr}"* ]]; then
-      cd ${specs_base_folder}/deb/
-      ./builddeb "${distr}" ${COMPSs_version}
+      cd "${specs_base_folder}/deb/" || exit 1
+      ./builddeb "${distr}" "${COMPSs_version}"
       if [ $? -ne 0 ]; then
         display_error "Building DEB script failed"
         exit 1
       fi 
-      cd ${script_dir}
+      cd "${script_dir}" || exit 1
     elif [[ ${RPM_DISTRS} == *"${distr}"* ]]; then
-      cd ${specs_base_folder}/rpm/
-      ./buildrpm "${distr}" ${COMPSs_version}
+      cd "${specs_base_folder}/rpm/" || exit 1
+      ./buildrpm "${distr}" "${COMPSs_version}"
       if [ $? -ne 0 ]; then
         display_error "Building RPM script failed"
         exit 1
       fi
-      cd ${script_dir}
+      cd "${script_dir}" || exit 1
     else
       # Other (should never reach this point)
       display_error "OTHER PACKAGES NOT SUPPORTED IN THIS SCRIPT"
@@ -168,13 +176,118 @@
     local release_type=$1
 
     # Move built packages to master
-    ssh -t -t -o StrictHostKeyChecking=no -o BatchMode=yes -o ChallengeResponseAuthentication=no ${JENKINS_USER}@${MASTER_VM} rm -rf ${JENKINS_PACKAGES_PATH}
-    ssh -t -t -o StrictHostKeyChecking=no -o BatchMode=yes -o ChallengeResponseAuthentication=no ${JENKINS_USER}@${MASTER_VM} mkdir -p ${JENKINS_PACKAGES_PATH}
-    scp -r -o StrictHostKeyChecking=no ${package_base_folder}/${distr} ${JENKINS_USER}@${MASTER_VM}:${JENKINS_PACKAGES_PATH}
+    ssh -t -t -o StrictHostKeyChecking=no -o BatchMode=yes -o ChallengeResponseAuthentication=no "${JENKINS_USER}"@"${MASTER_VM}" rm -rf "${JENKINS_PACKAGES_PATH}"
+    ssh -t -t -o StrictHostKeyChecking=no -o BatchMode=yes -o ChallengeResponseAuthentication=no "${JENKINS_USER}"@"${MASTER_VM}" mkdir -p "${JENKINS_PACKAGES_PATH}"
+    scp -r -o StrictHostKeyChecking=no "${package_base_folder}/${distr}" "${JENKINS_USER}"@"${MASTER_VM}":"${JENKINS_PACKAGES_PATH}"
     if [ $? -ne 0 ]; then
       display_error "Cannot move packages to master node"
       exit 1
     fi
+
+    # Ask the repo manager to upload them
+    update_repo_from_master "${release_type}"
+  }
+
+  install() {
+    echo -e "\e[0m"
+    echo "**************************"
+    echo "***  Installing COMPSs ***"
+    echo "**************************"
+    echo -e "\e[0m"
+
+    local installer_script="${script_dir}/installation/install_compss_${distr}"
+   
+    sudo "${installer_script}"
+    if [ $? -ne 0 ]; then
+      display_error "Cannot install unstable COMPSs version"
+      exit 1
+    fi
+  }
+
+  run_tests() {
+    echo -e "\e[0m"
+    echo "***************************"
+    echo "*** Running local TESTS ***"
+    echo "***************************"
+    echo -e "\e[0m"
+
+    echo "-- Running NIO tests..."
+    cfgFile=$(mktemp -p "${log_folder}")
+    cat > "$cfgFile" << EOT
+user=$(whoami)
+target_base_dir=${log_folder}/tests/
+comm=es.bsc.compss.nio.master.NIOAdaptor
+JAVA_HOME=${JAVA_HOME}
+EOT
+    cd "${trunk_base}/tests/scripts/" || exit 1
+    ./main local "$cfgFile"
+    #if [ $? -ne 0 ]; then
+    #  display_error "Tests failed. Check errors above"
+    #  exit 1
+    #fi
+    cd "${script_dir}" || exit 1
+  }
+
+  clean_vm() {
+    echo -e "\e[0m"
+    echo "**************************"
+    echo "***      Clean VM      ***"
+    echo "**************************"
+    echo -e "\e[0m"
+
+    # Cleaning test files
+    echo "-- Cleaning test files"
+    if [ "${cfgFile}" != "" ]; then
+      rm -f "${cfgFile}"
+    fi
+    rm -rf ~/.COMPSs/
+
+    # Restoring VM hosts
+    echo "-- Restoring VM hosts..."
+    sudo "${trunk_base}/tests/scripts/configure_hosts_remove"
+    if [ $? -ne 0 ]; then
+      display_error "Cannot restore hosts after tests"
+      exit 1
+    fi
+
+    # Unninstall COMPSs if needed
+    local unninstaller_script="${script_dir}/installation/unninstall_compss_${distr}"
+    sudo "${unninstaller_script}"
+    if [ $? -ne 0 ]; then
+      echo "------------------------- WARNING -----------------------------"
+      echo "Unninstall script failed on ${distr} either because"
+      echo "COMPSs was not installed or because there was an internal error"                                                                                                                                                                                                   
+      echo "---------------------------------------------------------------"
+    fi
+  }
+
+  #---------------------------------------------------------------------------------------------------------------------
+  # SECOND LEVEL FUNCTIONS FOR SC DISTRIBUTION
+  #---------------------------------------------------------------------------------------------------------------------
+  create_packages_sc() {
+    echo -e "\e[0m"
+    echo "**************************"
+    echo "*** Generate Packages  ***"
+    echo "**************************"
+    echo -e "\e[0m"
+
+    cd "${specs_base_folder}/sc" || exit 1
+    ./buildsc "${COMPSs_version}"
+    if [ $? -ne 0 ]; then
+      display_error "Building DEB script failed"
+      exit 1
+    fi 
+    cd "${script_dir}" || exit 1
+  }
+
+  update_repo_from_master() {
+    echo -e "\e[0m"
+    echo "**************************************"
+    echo "***   Export Packages from master  ***"
+    echo "**************************************"
+    echo -e "\e[0m"
+
+    local release_type=$1
 
     # Ask the repo manager to upload them
     local MAX_RETRIES=3
@@ -197,72 +310,6 @@
     fi
   }
 
-  install() {
-    echo -e "\e[0m"
-    echo "**************************"
-    echo "***  Installing COMPSs ***"
-    echo "**************************"
-    echo -e "\e[0m"
-
-    local installer_script=${script_dir}/installation/install_compss_${distr}.sh
-   
-    sudo sh ${installer_script}
-    if [ $? -ne 0 ]; then
-      display_error "Cannot install unstable COMPSs version"
-      exit 1
-    fi
-  }
-
-  run_tests() {
-    echo -e "\e[0m"
-    echo "***************************"
-    echo "*** Running local TESTS ***"
-    echo "***************************"
-    echo -e "\e[0m"
-
-    echo "-- Setting up VM hosts..."
-    sudo sh ${trunk_base}/tests/scripts/configure_hosts_insert
-    if [ $? -ne 0 ]; then
-      display_error "Cannot configure hosts before tests"
-      exit 1
-    fi
-
-    echo "-- Running NIO tests..."
-    cfgFile=$(mktemp -p ${log_folder})
-    cat > $cfgFile << EOT
-user=$(whoami)
-target_base_dir=${log_folder}/tests/
-comm=es.bsc.compss.nio.master.NIOAdaptor
-JAVA_HOME=${JAVA_HOME}
-EOT
-    cd ${trunk_base}/tests/scripts/
-    ./main local $cfgFile
-    #if [ $? -ne 0 ]; then
-    #  display_error "Tests failed. Check errors above"
-    #  exit 1
-    #fi
-    cd ${script_dir}
-  }
-
-  clean_vm() {
-    echo -e "\e[0m"
-    echo "**************************"
-    echo "***      Clean VM      ***"
-    echo "**************************"
-    echo -e "\e[0m"
-
-  }
-
-  snapshot() {
-    echo -e "\e[0m"
-    echo "**************************"
-    echo "***    Snapshot VM     ***"
-    echo "**************************"
-    echo -e "\e[0m"
-
-  }
-
-
   #---------------------------------------------------------------------------------------------------------------------
   # MAIN PROGRAM
   #---------------------------------------------------------------------------------------------------------------------
@@ -272,7 +319,7 @@ EOT
   #---------------------------------------------------------------------------------------------------------------------
 
   # Define script variables
-  script_dir=$(pwd)/$(dirname $0)
+  script_dir=$(pwd)/$(dirname "$0")
 
   COMPSs_version=2.1.rc1707
 
@@ -312,15 +359,12 @@ EOT
     exit 1
   fi
 
-  # Trap for clean
-  trap clean EXIT
-  
   # Execute distribution
   if [[ ${OTHER_DISTRS} == *"${distr}"* ]]; then
     # Execute SC
-    ${script_dir}/pre_process/exec_sc ${distr} ${log_folder} ${package_base_folder} > >(tee ${full_log}) 2> >(tee ${full_log} >&2)
+    exec_sc > >(tee "${full_log}") 2> >(tee "${full_log}" >&2)
   else
-    exec_distribution > >(tee ${full_log}) 2> >(tee ${full_log} >&2)
+    exec_distribution > >(tee "${full_log}") 2> >(tee "${full_log}" >&2)
     exitValue=$?
   fi
   exitValue=$?
