add rpm stuff

diff --git a/builders/specs/rpm/compss-storage/build b/builders/specs/rpm/compss-storage/build
--- a/builders/specs/rpm/compss-storage/build
+++ b/builders/specs/rpm/compss-storage/build
@@ -14,19 +14,40 @@
   echo " "
   echo "* Creating package structure..."
   mkdir -p tmp/BUILD tmp/RPMS tmp/SOURCES/ tmp/SPECS/ tmp/SRPMS tmp/BUILDROOT
+  mkdir -p tmp/SOURCES/${package_name}-${COMPSS_VERSION}
+
+  echo " "
+  echo "* Packing COMPSs sources..."
+  echo " "
+  target=tmp/SOURCES/${package_name}-${COMPSS_VERSION}/
+  cp -rf ${trunk_rel_path}/utils/storage ${target}
+
+  cd tmp/SOURCES/
+  find . -name '.git*' -exec rm -rf {} \;  #Cleans git files
+  tar czf ${package_name}-${COMPSS_VERSION}.tar.gz ${package_name}-${COMPSS_VERSION}
+  if [ $? -ne 0 ]; then
+	echo "Error compressing package"
+	exit 1
+  fi
+  cd ../../
+
+  echo " "
+  echo "* Cleaning tmp sources..."
+  rm -rf tmp/SOURCES/${package_name}-${COMPSS_VERSION}/
 
   echo " "
   echo "* Copying SPEC file to RPM build path..."
   echo " "
-  cp ./${package_name}_${mode}.spec tmp/SPECS/
+  cp ./${package_name}_${distr}_${mode}.spec tmp/SPECS/${package_name}_${mode}.spec
 
   echo " "
   echo "* Generating RPM package..."
   cd tmp/
+  export QA_SKIP_BUILD_ROOT=1
   rpmbuild --define "_topdir $PWD" -bb --clean SPECS/${package_name}_${mode}.spec
   if [ $? -ne 0 ]; then
-        echo "Error creating rpm";
-        exit 1;
+	echo "Error creating rpm";
+	exit 1;
   fi
   cd ..
 
