Remove tracing tags that were left after merging. Add mapReduce for PSCOs
git-svn-id: http://compss.bsc.es/svn/compss/framework/trunk@2423 9ab3861e-6c05-4e1b-b5ef-99af60850597

diff --git a/tests/sources/basic/29-pscos/result_internal b/tests/sources/basic/29-pscos/result_internal
--- a/tests/sources/basic/29-pscos/result_internal
+++ b/tests/sources/basic/29-pscos/result_internal
@@ -132,6 +132,16 @@
     echo "EXPECTED ID: ${targettp_pscoid2}"
     exit 1
   fi
+
+  
+  targetmr_got=$(grep "\[PSCO\_MR\]" ${output_file} | head -n 1)
+  targetmr_expected="[LOG][PSCO_MR] Person PName0,PName1,PName2,PName3 with age 6 has 6 computers"
+  if [ "${targetmr_got}" != "${targetmr_expected}" ]; then
+    echo "ERROR: TARGET PSCO is not correctly transfered to master"
+    echo "GOT:      ${targetmr_got}"
+    echo "EXPECTED: ${targetmr_expected}"
+    exit 1
+  fi
   
   #---------------------------------------------------------------------------------- 
   # ALL OK. Report result status
