Test all barrier API calls in JAVA

diff --git a/tests/sources/basic/26-java_api_calls/result b/tests/sources/basic/26-java_api_calls/result
--- a/tests/sources/basic/26-java_api_calls/result
+++ b/tests/sources/basic/26-java_api_calls/result
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-  #Obtain parameters
+  # Obtain parameters
   output_file=$1 
   target_log_folder=$2
   
@@ -9,60 +9,73 @@
 
   #----------------------------------------------------------------------------------
   # Check output standard out status
-  if [ -f ${output_file} ]; then
+  if [ -f "${output_file}" ]; then
      result_expected="------------------------------------------------------------"
-     test_result=$(tail -1 ${output_file})
+     test_result=$(tail -1 "${output_file}")
      if [ "${result_expected}" != "${test_result}" ]; then
-        echo "SOME ERROR WAS FOUND. CHECK ERRORS ABOVE." | tee -a ${output_file}
+        echo "SOME ERROR WAS FOUND. CHECK ERRORS ABOVE." | tee -a "${output_file}"
         exit 1
      fi
   else
-     echo "SOME ERROR WAS FOUND. CHECK ERRORS ABOVE." | tee -a ${output_file}
+     echo "SOME ERROR WAS FOUND. CHECK ERRORS ABOVE." | tee -a "${output_file}"
      exit 1
   fi
   # Check that ErrorManager has not generated any ERROR or FATAL message.
-  if $(cat "${output_file}" "${runtime_log}" | tr '\n' ' ' | grep -E -q "[ERRMGR].*(ERROR|FATAL):.*.*Shutting"); then
-    echo "ERROR: ERRMGR RAISED A FATAL ERROR. TEST FAILED." | tee -a ${output_file}
+  if cat "${output_file}" "${runtime_log}" | tr '\n' ' ' | grep -E -q "[ERRMGR].*(ERROR|FATAL):.*.*Shutting"; then
+    echo "ERROR: ERRMGR RAISED A FATAL ERROR. TEST FAILED." | tee -a "${output_file}"
     exit 1
   fi
   
   #---------------------------------------------------------------------------------- 
   # Compute result status
-  init_counter1=$(cat ${output_file} | grep "Initial counter1 value is" |  awk {' print $NF '})
-  final_counter_got1=$(cat ${output_file} | grep "Final counter1 value is" |  awk {' print $NF '})
+  init_counter1=$(grep "Initial counter1 value is" "${output_file}" | awk '{ print $NF }')
+  final_counter_got1=$(grep "Final counter1 value is" "${output_file}" | awk '{ print $NF }')
   final_counter_expected1=$((init_counter1+1))
 
   # Report result status
   if [ "$final_counter_got1" != "$final_counter_expected1" ]; then
-     echo "ERROR ON TASKS SCHEDULE" | tee -a ${output_file}
-     echo "EXPECTED FIRST INCREMENT: $final_counter_expected1" | tee -a ${output_file}
-     echo "GOT:      $final_counter_got1" | tee -a ${output_file}
+     echo "ERROR ON TASKS SCHEDULE" | tee -a "${output_file}"
+     echo "EXPECTED FIRST INCREMENT: $final_counter_expected1" | tee -a "${output_file}"
+     echo "GOT:      $final_counter_got1" | tee -a "${output_file}"
      exit 1
   fi
   
   #---------------------------------------------------------------------------------- 
   # Compute result status
-  init_counter2=$(cat ${output_file} | grep "Initial counter2 value is" | awk {' print $NF '})
-  final_counter_got2=$(cat ${output_file} | grep "Final counter2 value is" | awk {' print $NF '})
-  final_counter_expected2=$((init_counter1+1))
+  init_counter2=$(grep "Initial counter2 value is" "${output_file}" | awk '{ print $NF }')
+  final_counter_got2=$(grep "Final counter2 value is" "${output_file}" | awk '{ print $NF }')
+  final_counter_expected2=$((init_counter2+1))
 
   # Report result status
   if [ "$final_counter_got2" != "$final_counter_expected2" ]; then
-     echo "ERROR ON TASKS SCHEDULE" | tee -a ${output_file}
-     echo "EXPECTED FIRST INCREMENT: $final_counter_expected2" | tee -a ${output_file}
-     echo "GOT:      $final_counter_got2" | tee -a ${output_file}
+     echo "ERROR ON TASKS SCHEDULE" | tee -a "${output_file}"
+     echo "EXPECTED FIRST INCREMENT: $final_counter_expected2" | tee -a "${output_file}"
+     echo "GOT:      $final_counter_got2" | tee -a "${output_file}"
+     exit 1
+  fi
+
+  #---------------------------------------------------------------------------------- 
+  # Compute result status
+  init_counter3=$(grep "Initial counter3 value is" "${output_file}" | awk '{ print $NF }')
+  final_counter_got3=$(grep "Final counter3 value is" "${output_file}" | awk '{ print $NF }')
+  final_counter_expected3=$((init_counter3+1))
+
+  # Report result status
+  if [ "$final_counter_got3" != "$final_counter_expected3" ]; then
+     echo "ERROR ON TASKS SCHEDULE" | tee -a "${output_file}"
+     echo "EXPECTED FIRST INCREMENT: $final_counter_expected3" | tee -a "${output_file}"
+     echo "GOT:      $final_counter_got3" | tee -a "${output_file}"
      exit 1
   fi
   
   #---------------------------------------------------------------------------------- 
   # Check barrier
-  barrier=$(cat ${output_file} | egrep -o "Creating task|Barrier")
-  expectedBarrier=$'Creating task\nBarrier\nCreating task'
+  barrier=$(egrep -o "Creating task|Barrier" "${output_file}")
+  expectedBarrier=$'Creating task\nBarrier\nCreating task\nBarrier\nCreating task\nBarrier'
   if [ "$barrier" != "$expectedBarrier" ]; then
-     echo "ERROR ON BARRIER" | tee -a ${output_file}
-     echo "EXPECTED: $expectedBarrier" | tee -a ${output_file}
-     echo "GOT:      $barrier" | tee -a ${output_file}
-     exit 1
+     echo "ERROR ON BARRIER" | tee -a "${output_file}"
+     echo "EXPECTED: $expectedBarrier" | tee -a "${output_file}"
+     echo "GOT:      $barrier" | tee -a "${output_file}"
   fi
 
   #---------------------------------------------------------------------------------- 
