Task params in working dir strings tests for mpi and binary tasks.

diff --git a/tests/sources/local/python/1_decorator_binary/result b/tests/sources/local/python/1_decorator_binary/result
--- a/tests/sources/local/python/1_decorator_binary/result
+++ b/tests/sources/local/python/1_decorator_binary/result
@@ -16,7 +16,7 @@
      test_result=$(tail -1 "${output_file}")
      if [ "${result_expected}" != "${test_result}" ]; then
         echo "SOME ERROR WAS FOUND. CHECK ERRORS ABOVE." | tee -a "${output_file}"
-        exit 0
+        exit 1
      fi
   else
      echo "[ERROR] Output file not found" | tee -a "${output_file}"
@@ -147,6 +147,14 @@
       echo "ERROR: TASK FAILED: testFilesAndPrefixWithoutType function appearances check failed." | tee -a "${output_file}"
       exit 1
     fi
+  fi
+
+  # testParamInWD
+  wd_out_file="param_wd_out"
+  output_str=$(grep -i "test_param_in_wd" "$wd_out_file")
+  if [ "$output_str" = "" ]; then
+    echo "ERROR: TASK FAILED: testParamInWD function failed." | tee -a "${output_file}"
+    exit 1
   fi
 
   exit 0
diff --git a/tests/sources/local/python/1_decorator_mpi/result b/tests/sources/local/python/1_decorator_mpi/result
--- a/tests/sources/local/python/1_decorator_mpi/result
+++ b/tests/sources/local/python/1_decorator_mpi/result
@@ -144,4 +144,12 @@
     fi
   fi
 
+  # testParamInWD
+  wd_out_file="param_wd_out"
+  output_str=$(grep -i "test_param_in_wd" "$wd_out_file")
+  if [ "$output_str" = "" ]; then
+    echo "ERROR: TASK FAILED: testParamInWD function failed." | tee -a "${output_file}"
+    exit 1
+  fi
+
   exit 0
diff --git a/tests/sources/local/python/1_decorator_mpmd/result b/tests/sources/local/python/1_decorator_mpmd/result
--- a/tests/sources/local/python/1_decorator_mpmd/result
+++ b/tests/sources/local/python/1_decorator_mpmd/result
@@ -130,8 +130,6 @@
     fi
   fi
 
-  exit 0
-
   # testStdOutFile
   std_out_file="src/outfile"
   output_str=$(grep -i "simple test" "$std_out_file")
@@ -140,3 +138,12 @@
     exit 1
   fi
 
+  # testParamInWD
+  wd_out_file="param_wd_out"
+  output_str=$(grep -i "test_param_in_wd" "$wd_out_file")
+  if [ "$output_str" = "" ]; then
+    echo "ERROR: TASK FAILED: testParamInWD function failed." | tee -a "${output_file}"
+    exit 1
+  fi
+
+exit 0
