change pycompssplayer to pycompsscli

diff --git a/tests/sources/cli/environment/0_create_cluster/result b/tests/sources/cli/environment/0_create_cluster/result
--- a/tests/sources/cli/environment/0_create_cluster/result
+++ b/tests/sources/cli/environment/0_create_cluster/result
@@ -31,7 +31,13 @@
     fi
   fi
 
-    
+   pycompss environment remove cluster_env
+   # check if directory `cluster_env` has been removed from `~/.COMPSs/envs`
+   if [ -d "${HOME}/.COMPSs/envs/cluster_env" ]; then
+      echo "[ERROR] Directory `cluster_env` not removed from `~/.COMPSs/envs`" | tee -a "${output_file}"
+      rm -rf "${HOME}/.COMPSs/envs/cluster_env"
+      exit 1
+   fi
 
   #----------------------------------------------------------------------------------
   # Success
diff --git a/tests/sources/cli/environment/0_create_local/result b/tests/sources/cli/environment/0_create_local/result
--- a/tests/sources/cli/environment/0_create_local/result
+++ b/tests/sources/cli/environment/0_create_local/result
@@ -31,7 +31,13 @@
     fi
   fi
 
-    
+   pycompss environment remove local_env
+   # check if directory `local_env` has been removed from `~/.COMPSs/envs`
+   if [ -d "${HOME}/.COMPSs/envs/local_env" ]; then
+      echo "[ERROR] Directory `local_env` not removed from `~/.COMPSs/envs`" | tee -a "${output_file}"
+      rm -rf "${HOME}/.COMPSs/envs/local_env"
+      exit 1
+   fi
 
   #----------------------------------------------------------------------------------
   # Success
diff --git a/tests/sources/cli/environment/2_remove_default/result b/tests/sources/cli/environment/2_remove_default/result
--- a/tests/sources/cli/environment/2_remove_default/result
+++ b/tests/sources/cli/environment/2_remove_default/result
@@ -7,11 +7,17 @@
   #----------------------------------------------------------------------------------
   # Check output standard out status
   if [ -f "${output_file}" ]; then
-     test_result=$(cat "${output_file}")
-     regexp="Job submitted:"
-     if [[ ! "${test_result}" =~ $regexp ]]; then
-        echo "SOME ERROR WAS FOUND. CHECK ERRORS ABOVE." | tee -a "${output_file}"
+     result_expected="ERROR: \`default\` environment is required and cannot be deleted"
+     test_result=$(tail -1 "${output_file}")
+     if [ "${result_expected}" != "${test_result}" ]; then
+        echo "OUTPUT RESULT NOT AS EXPECTED." | tee -a "${output_file}"
         exit 1
+     fi
+
+     # Check if directory `default` exists in `~/.COMPSs/envs`
+     if [ ! -d "${HOME}/.COMPSs/envs/default" ]; then
+         echo "[ERROR] Directory \`default\` has been deleted from \`~/.COMPSs/envs\`" | tee -a "${output_file}"
+         exit 1
      fi
   else
      echo "[ERROR] Output file not found" | tee -a "${output_file}"
@@ -25,6 +31,9 @@
     fi
   fi
 
+    
+
   #----------------------------------------------------------------------------------
   # Success
   exit 0
+
