Fix some test shellscripts bad indent.

diff --git a/tests/sources/cli/environment/0_create_cluster/result b/tests/sources/cli/environment/0_create_cluster/result
--- a/tests/sources/cli/environment/0_create_cluster/result
+++ b/tests/sources/cli/environment/0_create_cluster/result
@@ -7,21 +7,21 @@
   #----------------------------------------------------------------------------------
   # Check output standard out status
   if [ -f "${output_file}" ]; then
-     result_expected="Deploying environment..."
-     test_result=$(tail -1 "${output_file}")
-     if [ "${result_expected}" != "${test_result}" ]; then
+    result_expected="Deploying environment..."
+    test_result=$(tail -1 "${output_file}")
+    if [ "${result_expected}" != "${test_result}" ]; then
         echo "SOME ERROR WAS FOUND. CHECK ERRORS ABOVE." | tee -a "${output_file}"
         exit 1
-     fi
+    fi
 
-     # Check if directory `cluster_env` exists in `~/.COMPSs/envs`
-     if [ ! -d "${HOME}/.COMPSs/envs/cluster_env" ]; then
+    # Check if directory `cluster_env` exists in `~/.COMPSs/envs`
+    if [ ! -d "${HOME}/.COMPSs/envs/cluster_env" ]; then
          echo "[ERROR] Directory `cluster_env` not found in `~/.COMPSs/envs`" | tee -a "${output_file}"
          exit 1
-     fi
+    fi
   else
-     echo "[ERROR] Output file not found" | tee -a "${output_file}"
-     exit 1
+    echo "[ERROR] Output file not found" | tee -a "${output_file}"
+    exit 1
   fi
   # Check that ErrorManager has not raised any ERROR or FATAL message
   if [ -f "${error_file}" ]; then
@@ -31,13 +31,13 @@
     fi
   fi
 
-   pycompss environment remove cluster_env
-   # check if directory `cluster_env` has been removed from `~/.COMPSs/envs`
-   if [ -d "${HOME}/.COMPSs/envs/cluster_env" ]; then
+  pycompss environment remove cluster_env
+  # check if directory `cluster_env` has been removed from `~/.COMPSs/envs`
+  if [ -d "${HOME}/.COMPSs/envs/cluster_env" ]; then
       echo "[ERROR] Directory `cluster_env` not removed from `~/.COMPSs/envs`" | tee -a "${output_file}"
       rm -rf "${HOME}/.COMPSs/envs/cluster_env"
       exit 1
-   fi
+  fi
 
   #----------------------------------------------------------------------------------
   # Success
diff --git a/tests/sources/cli/environment/1_change_env/result b/tests/sources/cli/environment/1_change_env/result
--- a/tests/sources/cli/environment/1_change_env/result
+++ b/tests/sources/cli/environment/1_change_env/result
@@ -7,12 +7,12 @@
   #----------------------------------------------------------------------------------
   # Check output standard out status
   if [ -f "${output_file}" ]; then
-     result_expected="Environment \`default\` is now active"
-     test_result=$(tail -1 "${output_file}")
-     if [ "${result_expected}" != "${test_result}" ]; then
+    result_expected="Environment \`default\` is now active"
+    test_result=$(tail -1 "${output_file}")
+    if [ "${result_expected}" != "${test_result}" ]; then
         echo "SOME ERROR WAS FOUND. CHECK ERRORS ABOVE." | tee -a "${output_file}"
         exit 1
-     fi
+    fi
 
       # Check if exists a file named `current` in `~/.COMPSs/envs/default`
       if [ ! -f "${HOME}/.COMPSs/envs/default/current" ]; then
@@ -31,8 +31,8 @@
          exit 1
       fi
   else
-     echo "[ERROR] Output file not found" | tee -a "${output_file}"
-     exit 1
+    echo "[ERROR] Output file not found" | tee -a "${output_file}"
+    exit 1
   fi
   # Check that ErrorManager has not raised any ERROR or FATAL message
   if [ -f "${error_file}" ]; then
@@ -42,26 +42,26 @@
     fi
   fi
 
-   pycompss environment remove docker_env
-   exit 0
-   # check if directory `docker_env` has been removed from `~/.COMPSs/envs`
-   if [ -d "${HOME}/.COMPSs/envs/docker_env" ]; then
+  pycompss environment remove docker_env
+  exit 0
+  # check if directory `docker_env` has been removed from `~/.COMPSs/envs`
+  if [ -d "${HOME}/.COMPSs/envs/docker_env" ]; then
       echo "[ERROR] Directory `docker_env` not removed from `~/.COMPSs/envs`" | tee -a "${output_file}"
       rm -rf "${HOME}/.COMPSs/envs/docker_env"
       exit 1
-   fi
-   
+  fi
+
    # check if docker container has been removed
-   if [ "$(docker ps -a | grep "pycompss-master-docker_env")" ]; then
+  if [ "$(docker ps -a | grep "pycompss-master-docker_env")" ]; then
       echo "[ERROR] Docker container not removed" | tee -a "${output_file}"
       exit 1
-   fi
+  fi
 
-   env_list_length=$(pycompss env list | grep -o "*" | wc -l)
-   if [ "${env_list_length}" -ne 1 ]; then
+  env_list_length=$(pycompss env list | grep -o "*" | wc -l)
+  if [ "${env_list_length}" -ne 1 ]; then
       echo "[ERROR] Environment list has wrong number of active envs" | tee -a "${output_file}"
       exit 1
-   fi
+  fi
 
     
 
diff --git a/tests/sources/cli/environment/2_remove_default/result b/tests/sources/cli/environment/2_remove_default/result
--- a/tests/sources/cli/environment/2_remove_default/result
+++ b/tests/sources/cli/environment/2_remove_default/result
@@ -7,21 +7,21 @@
   #----------------------------------------------------------------------------------
   # Check output standard out status
   if [ -f "${output_file}" ]; then
-     result_expected="ERROR: \`default\` environment is required and cannot be deleted"
-     test_result=$(tail -1 "${output_file}")
-     if [ "${result_expected}" != "${test_result}" ]; then
+    result_expected="ERROR: \`default\` environment is required and cannot be deleted"
+    test_result=$(tail -1 "${output_file}")
+    if [ "${result_expected}" != "${test_result}" ]; then
         echo "OUTPUT RESULT NOT AS EXPECTED." | tee -a "${output_file}"
         exit 1
-     fi
+    fi
 
-     # Check if directory `default` exists in `~/.COMPSs/envs`
-     if [ ! -d "${HOME}/.COMPSs/envs/default" ]; then
+    # Check if directory `default` exists in `~/.COMPSs/envs`
+    if [ ! -d "${HOME}/.COMPSs/envs/default" ]; then
          echo "[ERROR] Directory \`default\` has been deleted from \`~/.COMPSs/envs\`" | tee -a "${output_file}"
          exit 1
-     fi
+    fi
   else
-     echo "[ERROR] Output file not found" | tee -a "${output_file}"
-     exit 1
+    echo "[ERROR] Output file not found" | tee -a "${output_file}"
+    exit 1
   fi
   # Check that ErrorManager has not raised any ERROR or FATAL message
   if [ -f "${error_file}" ]; then
diff --git a/tests/sources/cli/runapps/0_deploy_app/result b/tests/sources/cli/runapps/0_deploy_app/result
--- a/tests/sources/cli/runapps/0_deploy_app/result
+++ b/tests/sources/cli/runapps/0_deploy_app/result
@@ -7,20 +7,20 @@
   #----------------------------------------------------------------------------------
   # Check output standard out status
   if [ -f "${output_file}" ]; then
-     result_expected="Environment ID: cluster_env
+    result_expected="Environment ID: cluster_env
 Deploying environment...
 Deploying app...
 Application \`matmul\` removed successfully
 Environment \`default\` is now active
 Deleting environment \`cluster_env\`..."
-     test_result=$(cat "${output_file}")
-     if [ "${result_expected}" != "${test_result}" ]; then
+    test_result=$(cat "${output_file}")
+    if [ "${result_expected}" != "${test_result}" ]; then
         echo "SOME ERROR WAS FOUND. CHECK ERRORS ABOVE." | tee -a "${output_file}"
         exit 1
-     fi
+    fi
   else
-     echo "[ERROR] Output file not found" | tee -a "${output_file}"
-     exit 1
+    echo "[ERROR] Output file not found" | tee -a "${output_file}"
+    exit 1
   fi
   # Check that ErrorManager has not raised any ERROR or FATAL message
   if [ -f "${error_file}" ]; then
diff --git a/tests/sources/local/agents/0.1_1_agent_deployment/execution b/tests/sources/local/agents/0.1_1_agent_deployment/execution
--- a/tests/sources/local/agents/0.1_1_agent_deployment/execution
+++ b/tests/sources/local/agents/0.1_1_agent_deployment/execution
@@ -99,8 +99,8 @@ compss_agent_start \
   sleep 1
   RESULT=$(grep "test invoked" "${agent1_output_log}")
   if [ -z "${RESULT}" ]; then  
-     echo "Agent failed to start" > >(tee -a "${error_log}")
-     exit 1
+    echo "Agent failed to start" > >(tee -a "${error_log}")
+    exit 1
   fi
   echo "Agent started" > >(tee -a "${output_log}")
   sleep 1
diff --git a/tests/sources/local/c/4_worker_in_master/execution b/tests/sources/local/c/4_worker_in_master/execution
--- a/tests/sources/local/c/4_worker_in_master/execution
+++ b/tests/sources/local/c/4_worker_in_master/execution
@@ -20,8 +20,8 @@
   "$(dirname "${COMPSs_exec}")"/compss_build_app "${app_name}"
   ev=$?
   if [ $ev -ne 0 ]; then
-     echo "[ERROR] Cannot compile C app. See errors above."
-     exit $ev
+    echo "[ERROR] Cannot compile C app. See errors above."
+    exit $ev
   fi
 
   #----------------------------------------------------------------------------------
@@ -46,31 +46,31 @@
 
   # shellcheck disable=SC2086
   timeout --signal=2 $expectedTime "${COMPSs_exec}" \
-     --project="${base_app_dir}"/project.xml \
-     --resources="${base_app_dir}"/resources.xml \
-     \
-     --comm="$comm" \
-     \
-     --debug \
-     ${runcompss_opts} \
-     \
-     "${base_app_dir}/master/${app_name}" $counterVal > >(tee "${output_log}") 2> >(tee "${error_log}" >&2)
+    --project="${base_app_dir}"/project.xml \
+    --resources="${base_app_dir}"/resources.xml \
+    \
+    --comm="$comm" \
+    \
+    --debug \
+    ${runcompss_opts} \
+    \
+    "${base_app_dir}/master/${app_name}" $counterVal > >(tee "${output_log}") 2> >(tee "${error_log}" >&2)
   
   # Check timeout
   if [[ "$?" = "124" ]]; then
-     # Copy LOG files
-     cp -rf "${COMPSs_log_folder}/${app_name}_0${retry_num}"/* "${target_log_folder}"
+    # Copy LOG files
+    cp -rf "${COMPSs_log_folder}/${app_name}_0${retry_num}"/* "${target_log_folder}"
 
-     # Report time out
-     echo "[WARNING] C Application timed out" >> "${output_log}"
-     exit_value=124
+    # Report time out
+    echo "[WARNING] C Application timed out" >> "${output_log}"
+    exit_value=124
   else
-     # Copy LOG files
-     cp -rf "${COMPSs_log_folder}/${app_name}_0${retry_num}"/* "${target_log_folder}"
+    # Copy LOG files
+    cp -rf "${COMPSs_log_folder}/${app_name}_0${retry_num}"/* "${target_log_folder}"
 
-     # Check result
-     "${base_app_dir}"/result "${output_log}" "${error_log}" "${target_log_folder}"
-     exit_value=$?
+    # Check result
+    "${base_app_dir}"/result "${output_log}" "${error_log}" "${target_log_folder}"
+    exit_value=$?
   fi
   
   #----------------------------------------------------------------------------------
diff --git a/tests/sources/local/c/9_gpu_fpga_implementation/result b/tests/sources/local/c/9_gpu_fpga_implementation/result
--- a/tests/sources/local/c/9_gpu_fpga_implementation/result
+++ b/tests/sources/local/c/9_gpu_fpga_implementation/result
@@ -11,15 +11,15 @@
   #----------------------------------------------------------------------------------
   # Check output standard out status
   if [ -f "${output_file}" ]; then
-     result_expected="------------------------------------------------------------"
-     test_result=$(tail -1 "${output_file}")
-     if [ "${result_expected}" != "${test_result}" ]; then
+    result_expected="------------------------------------------------------------"
+    test_result=$(tail -1 "${output_file}")
+    if [ "${result_expected}" != "${test_result}" ]; then
         echo "SOME ERROR WAS FOUND. CHECK ERRORS ABOVE." | tee -a "${output_file}"
         exit 1
-     fi
+    fi
   else
-     echo "[ERROR] Output file not found" | tee -a "${output_file}"
-     exit 1
+    echo "[ERROR] Output file not found" | tee -a "${output_file}"
+    exit 1
   fi
   # Check that ErrorManager has not raised any ERROR or FATAL message
   if [ -f "${error_file}" ]; then
@@ -70,22 +70,22 @@
 
   # Report result status
   if [ "$result" != "$expected_result" ] || [ "$usesCPU" -lt 1 ] || [ "$usesGPU" -lt 1 ] || [ "$usesFPGA" -lt 1 ] || [ "$FPGAreprogrammed" -eq 0 ]; then
-     echo "ERROR ON TASKS SCHEDULE" | tee -a "${output_file}"
-     echo "EXPECTED RESULT: $expected_result" | tee -a "${output_file}"
-     echo "GOT: $result" | tee -a "${output_file}"
-     if [ "$usesCPU" -lt 1 ] ; then
-       echo "No CPU tasks were executed!"
-     fi
-     if [ "$usesGPU" -lt 1 ] ; then
-       echo "No GPU tasks were executed!"
-     fi
-     if [ "$usesFPGA" -lt 1 ] ; then
-       echo "No FPGA tasks were executed!"
-     fi
-     if [ "$FPGAreprogrammed" -eq 0 ] ; then
-       echo "Failed to reprogram the FPGA!"
-     fi
-     exit 1
+    echo "ERROR ON TASKS SCHEDULE" | tee -a "${output_file}"
+    echo "EXPECTED RESULT: $expected_result" | tee -a "${output_file}"
+    echo "GOT: $result" | tee -a "${output_file}"
+    if [ "$usesCPU" -lt 1 ] ; then
+      echo "No CPU tasks were executed!"
+    fi
+    if [ "$usesGPU" -lt 1 ] ; then
+      echo "No GPU tasks were executed!"
+    fi
+    if [ "$usesFPGA" -lt 1 ] ; then
+      echo "No FPGA tasks were executed!"
+    fi
+    if [ "$FPGAreprogrammed" -eq 0 ] ; then
+      echo "Failed to reprogram the FPGA!"
+    fi
+    exit 1
   fi
 
   exit 0
diff --git a/tests/sources/local/fault_tolerance/2_on_failure_retry/result b/tests/sources/local/fault_tolerance/2_on_failure_retry/result
--- a/tests/sources/local/fault_tolerance/2_on_failure_retry/result
+++ b/tests/sources/local/fault_tolerance/2_on_failure_retry/result
@@ -11,22 +11,22 @@
 
   # Default checker (application ends with : Error running application)
   if [ -f "${output_file}" ]; then
-     result_expected="Error running application"
-     test_result=$(tail -n 1 < "${error_file}" )
-     result_found=$(echo "${test_result}" | grep -c "${result_expected}")
-     if [ ! "${result_found}" == "1" ]; then
+    result_expected="Error running application"
+    test_result=$(tail -n 1 < "${error_file}" )
+    result_found=$(echo "${test_result}" | grep -c "${result_expected}")
+    if [ ! "${result_found}" == "1" ]; then
         echo "[ERROR] SOME ERROR WAS FOUND. CHECK ERRORS ABOVE." | tee -a "${output_file}"
         exit 1
-     fi
+    fi
   else
-     echo "[ERROR] Output file not found" | tee -a "${output_file}"
-     exit 1
+    echo "[ERROR] Output file not found" | tee -a "${output_file}"
+    exit 1
   fi
 
   # Check that ErrorManager has raised any ERROR or FATAL message
   if [ -f "${error_file}" ]; then
     if grep -E "\\[ERRMGR\\].*(ERROR|FATAL|Shutting down COMPSs)" "${error_file}"; then
-       echo "[RESULT_CHECKER] ErrorManager raised and ERROR as expected" | tee -a "${output_file}"
+      echo "[RESULT_CHECKER] ErrorManager raised and ERROR as expected" | tee -a "${output_file}"
     else
       echo "[ERROR] ErrorManager did not raise any error" | tee -a "${output_file}"
       exit 1
diff --git a/tests/sources/local/java/1_annotation_mpi/result b/tests/sources/local/java/1_annotation_mpi/result
--- a/tests/sources/local/java/1_annotation_mpi/result
+++ b/tests/sources/local/java/1_annotation_mpi/result
@@ -12,15 +12,15 @@
   #----------------------------------------------------------------------------------
   # Check output standard out status
   if [ -f "${output_file}" ]; then
-     result_expected="------------------------------------------------------------"
-     test_result=$(tail -1 "${output_file}")
-     if [ "${result_expected}" != "${test_result}" ]; then
+    result_expected="------------------------------------------------------------"
+    test_result=$(tail -1 "${output_file}")
+    if [ "${result_expected}" != "${test_result}" ]; then
         echo "SOME ERROR WAS FOUND. CHECK ERRORS ABOVE." | tee -a "${output_file}"
         exit 1
-     fi
+    fi
   else
-     echo "[ERROR] Output file not found" | tee -a "${output_file}"
-     exit 1
+    echo "[ERROR] Output file not found" | tee -a "${output_file}"
+    exit 1
   fi
   # Check that ErrorManager has not raised any ERROR or FATAL message
   if [ -f "${error_file}" ]; then
@@ -46,7 +46,7 @@
   #----------------------------------------------------------------------------------
   # Check MPI task execution status
   exitValue=0
-   
+
   dotValue=$(grep "TotalSum" "${output_file}" | tr ":" "\\t" | awk '{ print $2 }')
   
   singleGOT=$(grep "\\[RESULT\\] MPI Task1" "${output_file}" | grep "MULTIPLICATION_RESULT" | awk '{ print $NF }')
diff --git a/tests/sources/local/java/3_node_init_failure/result b/tests/sources/local/java/3_node_init_failure/result
--- a/tests/sources/local/java/3_node_init_failure/result
+++ b/tests/sources/local/java/3_node_init_failure/result
@@ -17,15 +17,15 @@
   #----------------------------------------------------------------------------------
   # Check output standard out status
   if [ -f "${output_file_0}" ]; then
-     result_expected="------------------------------------------------------------"
-     test_result=$(tail -1 "${output_file_0}")
-     if [ "${result_expected}" != "${test_result}" ]; then
+    result_expected="------------------------------------------------------------"
+    test_result=$(tail -1 "${output_file_0}")
+    if [ "${result_expected}" != "${test_result}" ]; then
         echo "SOME ERROR WAS FOUND. CHECK ERRORS ABOVE." | tee -a "${output_file_0}"
         exit 1 
-     fi
+    fi
   else
-     echo "[ERROR] Output file not found" | tee -a "${output_file_0}"
-     exit 1 
+    echo "[ERROR] Output file not found" | tee -a "${output_file_0}"
+    exit 1
   fi
   # Check that ErrorManager has not raised any ERROR or FATAL message
   if [ -f "${error_file_0}" ]; then
diff --git a/tests/sources/local/java/3_remote_file/result b/tests/sources/local/java/3_remote_file/result
--- a/tests/sources/local/java/3_remote_file/result
+++ b/tests/sources/local/java/3_remote_file/result
@@ -12,15 +12,15 @@
   #----------------------------------------------------------------------------------
   # Check output standard out status
   if [ -f "${output_file}" ]; then
-     result_expected="------------------------------------------------------------"
-     test_result=$(tail -1 "${output_file}")
-     if [ "${result_expected}" != "${test_result}" ]; then
+    result_expected="------------------------------------------------------------"
+    test_result=$(tail -1 "${output_file}")
+    if [ "${result_expected}" != "${test_result}" ]; then
         echo "SOME ERROR WAS FOUND. CHECK ERRORS ABOVE." | tee -a "${output_file}"
         exit 1
-     fi
+    fi
   else
-     echo "[ERROR] Output file not found" | tee -a "${output_file}"
-     exit 1
+    echo "[ERROR] Output file not found" | tee -a "${output_file}"
+    exit 1
   fi
   # Check that ErrorManager has not raised any ERROR or FATAL message
   if [ -f "${error_file}" ]; then
@@ -51,10 +51,10 @@
 
   # Report result status
   if [ "$final_counter_got" != "$final_counter_expected" ]; then
-     echo "ERROR ON TASKS SCHEDULE" | tee -a "${output_file}"
-     echo "EXPECTED FIRST INCREMENT: $final_counter_expected" | tee -a "${output_file}"
-     echo "GOT:      $final_counter_got" | tee -a "${output_file}"
-     exit 1
+    echo "ERROR ON TASKS SCHEDULE" | tee -a "${output_file}"
+    echo "EXPECTED FIRST INCREMENT: $final_counter_expected" | tee -a "${output_file}"
+    echo "GOT:      $final_counter_got" | tee -a "${output_file}"
+    exit 1
   fi
   
   exit 0
diff --git a/tests/sources/local/python/1_compss_exceptions/result b/tests/sources/local/python/1_compss_exceptions/result
--- a/tests/sources/local/python/1_compss_exceptions/result
+++ b/tests/sources/local/python/1_compss_exceptions/result
@@ -13,12 +13,12 @@
   #----------------------------------------------------------------------------------
   # Check output standard out status
   if [ -f "${output_file}" ]; then
-     result_expected="------------------------------------------------------------"
-     test_result=$(tail -1 "${output_file}")
-     
+    result_expected="------------------------------------------------------------"
+    test_result=$(tail -1 "${output_file}")
+
   else
-     echo "[ERROR] Output file not found" | tee -a "${output_file}"
-     exit 1
+    echo "[ERROR] Output file not found" | tee -a "${output_file}"
+    exit 1
   fi
   # Check that ErrorManager has not raised any ERROR or FATAL message
   if [ -f "${error_file}" ]; then
diff --git a/tests/sources/local/python/1_decorator_software/result b/tests/sources/local/python/1_decorator_software/result
--- a/tests/sources/local/python/1_decorator_software/result
+++ b/tests/sources/local/python/1_decorator_software/result
@@ -12,15 +12,15 @@
   #----------------------------------------------------------------------------------
   # Check output standard out status
   if [ -f "${output_file}" ]; then
-     result_expected="------------------------------------------------------------"
-     test_result=$(tail -1 "${output_file}")
-     if [ "${result_expected}" != "${test_result}" ]; then
+    result_expected="------------------------------------------------------------"
+    test_result=$(tail -1 "${output_file}")
+    if [ "${result_expected}" != "${test_result}" ]; then
         echo "SOME ERROR WAS FOUND. CHECK ERRORS ABOVE." | tee -a "${output_file}"
         exit 1
-     fi
+    fi
   else
-     echo "[ERROR] Output file not found" | tee -a "${output_file}"
-     exit 1
+    echo "[ERROR] Output file not found" | tee -a "${output_file}"
+    exit 1
   fi
   # Check that ErrorManager has not raised any ERROR or FATAL message
   if [ -f "${error_file}" ]; then
@@ -128,7 +128,7 @@
   hellofile=$(grep -r -l "sed s/Hi/HELLO/g" "${jobs_logs}")
   hello=$(grep -r -l "HELLO, this is a simple test to grep." "${hellofile}")
   if [[ -z "$hello" ]]; then
-     echo "ERROR: TASK FAILED: testFileManagementIN function failed." | tee -a "${output_file}"
+    echo "ERROR: TASK FAILED: testFileManagementIN function failed." | tee -a "${output_file}"
     exit 1
   else
     appearances=$(grep -c "HELLO, this is a simple test to grep." "${hellofile}")
@@ -140,19 +140,19 @@
 
   prolog=$(grep -r -l "this is prolog" "${jobs_logs}")
   if [[ -z "$prolog" ]]; then
-     echo "ERROR: TASK FAILED: Prolog execution failed." | tee -a "${output_file}"
+    echo "ERROR: TASK FAILED: Prolog execution failed." | tee -a "${output_file}"
     exit 1
   fi
   epilog=$(grep -r -l "this is epilog" "${jobs_logs}")
   if [[ -z "$epilog" ]]; then
-     echo "ERROR: TASK FAILED: Epilog execution failed." | tee -a "${output_file}"
+    echo "ERROR: TASK FAILED: Epilog execution failed." | tee -a "${output_file}"
     exit 1
   fi
 
 
   tmp=$(grep -r -l "greetings from a task with no task decorator." "${jobs_logs}")
   if [[ -z "$tmp" ]]; then
-     echo "ERROR: TASK FAILED: testMpiWoTaskDecor function failed." | tee -a "${output_file}"
+    echo "ERROR: TASK FAILED: testMpiWoTaskDecor function failed." | tee -a "${output_file}"
     exit 1
   fi
 
diff --git a/tests/sources/local/python/8_argument_deprecation/result b/tests/sources/local/python/8_argument_deprecation/result
--- a/tests/sources/local/python/8_argument_deprecation/result
+++ b/tests/sources/local/python/8_argument_deprecation/result
@@ -12,15 +12,15 @@
   #----------------------------------------------------------------------------------
   # Check output standard out status
   if [ -f "${output_file}" ]; then
-     result_expected="------------------------------------------------------------"
-     test_result=$(tail -1 "${output_file}")
-     if [ "${result_expected}" != "${test_result}" ]; then
+    result_expected="------------------------------------------------------------"
+    test_result=$(tail -1 "${output_file}")
+    if [ "${result_expected}" != "${test_result}" ]; then
         echo "SOME ERROR WAS FOUND. CHECK ERRORS ABOVE." | tee -a "${output_file}"
         exit 1
-     fi
+    fi
   else
-     echo "[ERROR] Output file not found" | tee -a "${output_file}"
-     exit 1
+    echo "[ERROR] Output file not found" | tee -a "${output_file}"
+    exit 1
   fi
   # Check that ErrorManager has not raised any ERROR or FATAL message
   if [ -f "${error_file}" ]; then
@@ -58,8 +58,8 @@
   expected="12"
   deprecated=$(cat "${error_file}" | grep "WARNING" | grep "Deprecated" | wc -l)
   if [ "${deprecated}" != ${expected} ] ; then
-     echo "ERROR: WRONG NUMBER OF DEPRECATED ARGUMENTS WARNING MESSAGES (Expected: ${expected} - Found: ${deprecated})" | tee -a "${output_file}"
-     exit 1
+    echo "ERROR: WRONG NUMBER OF DEPRECATED ARGUMENTS WARNING MESSAGES (Expected: ${expected} - Found: ${deprecated})" | tee -a "${output_file}"
+    exit 1
   fi
 
   #----------------------------------------------------------------------------------
diff --git a/tests/sources/local/python/9_jupyter_notebook/result b/tests/sources/local/python/9_jupyter_notebook/result
--- a/tests/sources/local/python/9_jupyter_notebook/result
+++ b/tests/sources/local/python/9_jupyter_notebook/result
@@ -23,8 +23,8 @@
   #----------------------------------------------------------------------------------
   # Check output and runtime.log exist
   if [ ! -f "${output_file}" ]; then
-     echo "[ERROR] Output file not found" | tee -a "${output_file}"
-     exit 1
+    echo "[ERROR] Output file not found" | tee -a "${output_file}"
+    exit 1
   fi
   if [ ! -f "${runtime_log}" ]; then
     echo "[ERROR] runtime.log not found" | tee -a "${output_file}"
@@ -34,15 +34,15 @@
   #----------------------------------------------------------------------------------
   # Check output standard out status of simple.ipynb or simpleGAT.ipynb
   if [ -f "${html}" ]; then
-     result_expected="RESULT=EXPECTED"
-     test_result=$(grep -aoE '\bRESULT=\w*' "${html}" | tail -n 1)
-     if [ "${result_expected}" != "${test_result}" ]; then
+    result_expected="RESULT=EXPECTED"
+    test_result=$(grep -aoE '\bRESULT=\w*' "${html}" | tail -n 1)
+    if [ "${result_expected}" != "${test_result}" ]; then
         echo "SOME ERROR WAS FOUND. CHECK ERRORS ABOVE." | tee -a "${output_file}"
         exit 1
-     fi
+    fi
   else
-     echo "SOME ERROR WAS FOUND. HTML FILE NOT EXISTS." | tee -a "${output_file}"
-     exit 1
+    echo "SOME ERROR WAS FOUND. HTML FILE NOT EXISTS." | tee -a "${output_file}"
+    exit 1
   fi
 
   # Check that ErrorManager has not raised any ERROR or FATAL message
@@ -78,8 +78,8 @@
   #----------------------------------------------------------------------------------
   # Check that graph has been generated
   if [ ! -f "${target_log_folder}"/monitor/complete_graph.dot ]; then
-     echo "SOME ERROR WAS FOUND. GRAPH NOT GENERATED." | tee -a "${output_file}"
-     exit 1
+    echo "SOME ERROR WAS FOUND. GRAPH NOT GENERATED." | tee -a "${output_file}"
+    exit 1
   fi
 
   #----------------------------------------------------------------------------------
diff --git a/tests/sources/sc/simple/0_simple_c_sc/execution b/tests/sources/sc/simple/0_simple_c_sc/execution
--- a/tests/sources/sc/simple/0_simple_c_sc/execution
+++ b/tests/sources/sc/simple/0_simple_c_sc/execution
@@ -42,8 +42,8 @@
   compss_build_app "${app_name}"
   ev=$?
   if [ $ev -ne 0 ]; then
-     echo "[ERROR] Cannot compile C app. See errors above."
-     exit $ev
+    echo "[ERROR] Cannot compile C app. See errors above."
+    exit $ev
   fi
   #----------------------------------------------------------------------------------
   # Run application
@@ -67,15 +67,15 @@
     expectedTime=5
 
     "${COMPSs_exec}" --exec_time=${expectedTime} \
-     --num_nodes=1 \
-     --comm="$comm" \
-     --debug \
-     --worker_in_master_cpus=8 \
-     --job_execution_dir=${master_working_dir} \
-     --worker_working_dir=${worker_working_dir} \
-     --log_dir=${target_log_folder} \
-     ${runcompss_opts} \
-     --appdir="${base_app_dir}" \
-     "${base_app_dir}/master/${app_name}" $counterVal > >(tee "${output_log}") 2> >(tee "${error_log}" >&2)
+    --num_nodes=1 \
+    --comm="$comm" \
+    --debug \
+    --worker_in_master_cpus=8 \
+    --job_execution_dir=${master_working_dir} \
+    --worker_working_dir=${worker_working_dir} \
+    --log_dir=${target_log_folder} \
+    ${runcompss_opts} \
+    --appdir="${base_app_dir}" \
+    "${base_app_dir}/master/${app_name}" $counterVal > >(tee "${output_log}") 2> >(tee "${error_log}" >&2)
 
   done
