Splitting of tests in task_group, time_out and compss_exceptions

diff --git a/tests/sources/java/1_compss_exception/result b/tests/sources/java/1_compss_exception/result
--- a/tests/sources/java/1_compss_exception/result
+++ b/tests/sources/java/1_compss_exception/result
@@ -46,7 +46,7 @@
 
   #----------------------------------------------------------------------------------
   # Compute result status
-  FILES=32
+  FILES=6
 
   # Checks if the file has been written as many times as expected
   result=$(cat /tmp/sharedDisk/taskGroups.txt)
@@ -64,6 +64,20 @@
   if [ -f "${target_log_folder}/jobs/job$((FILES+1))_NEW.out" ]; then
     echo "ERROR: More tasks than expected have been executed."
     exit 1
+  fi
+  
+  # Check if all successors have been canceled
+  output1=$(cat "${runtime_log}" | grep "Task canceled:" | wc -l)
+  if [ "${output1}" -ne 4 ]; then
+  	echo "ERROR: The number of canceled tasks is not correct."
+  	exit 1
+  fi
+
+  # Check if the tasks have failed
+  output1=$(grep -c "COMPSs Exception raised :" "${runtime_log}")
+  if [ "${output1}" -ne 2 ]; then
+  	echo "ERROR: The number of COMPSsExceptions raised is not correct."
+  	exit 1
   fi
   
   #----------------------------------------------------------------------------------
diff --git a/tests/sources/java/2_time_out/result b/tests/sources/java/2_time_out/result
--- a/tests/sources/java/2_time_out/result
+++ b/tests/sources/java/2_time_out/result
@@ -4,7 +4,6 @@
   output_file=$1
   error_file=$2
   target_log_folder=$3
-  final_graph_expected=$4
 
   # Log files
   runtime_log="${target_log_folder}/runtime.log"
@@ -46,7 +45,7 @@
 
   #----------------------------------------------------------------------------------
   # Compute result status
-  FILES=32
+  FILES=2
 
   # Checks if the file has been written as many times as expected
   result=$(cat /tmp/sharedDisk/taskGroups.txt)
@@ -66,13 +65,11 @@
     exit 1
   fi
   
-  #----------------------------------------------------------------------------------
-  # Check dot file
-  final_graph_got=${target_log_folder}/monitor/complete_graph.dot
-  graph_status=$(diff -U 0 "${final_graph_expected}" "${final_graph_got}" | grep -v ^@ | grep -v "#" | tail -n+3)
-  if [ ! -z "${graph_status}" ]; then
-    echo "[ERROR] Obtained graph file is not as expected" | tee -a "${output_file}"
-    exit 1
+  # Check if the tasks have failed
+  output1=$(grep -c "Task failure:" "${runtime_log}")
+  if [ "${output1}" -ne 1 ]; then
+  	echo "ERROR: The number of failed tasks is not correct."
+  	exit 1
   fi
 
   #---------------------------------------------------------------------------------- 
diff --git a/tests/sources/python/1_compss_exceptions/result b/tests/sources/python/1_compss_exceptions/result
--- a/tests/sources/python/1_compss_exceptions/result
+++ b/tests/sources/python/1_compss_exceptions/result
@@ -8,50 +8,57 @@
 
   # Log files
   runtime_log="${target_log_folder}/runtime.log"
-  resources_log="${target_log_folder}/resources.log"                                                                                                                                                                                                                          
+  resources_log="${target_log_folder}/resources.log"
 
   #----------------------------------------------------------------------------------
   # Check output standard out status
   if [ -f "${output_file}" ]; then
      result_expected="------------------------------------------------------------"
      test_result=$(tail -1 "${output_file}")
-     if [ "${result_expected}" != "${test_result}" ]; then
-        echo "SOME ERROR WAS FOUND. CHECK ERRORS ABOVE." | tee -a "${output_file}"
-        exit 1 
-     fi
+
   else
      echo "[ERROR] Output file not found" | tee -a "${output_file}"
-     exit 1 
+     exit 1
   fi
   # Check that ErrorManager has not raised any ERROR or FATAL message
   if [ -f "${error_file}" ]; then
     if grep -E "\\[ERRMGR\\].*(ERROR|FATAL|Shutting down COMPSs)" "${error_file}"; then
       echo "ERROR: ErrorManager has raised a fatal error" | tee -a "${output_file}"
-      exit 1 
+      exit 1
     fi
   else
     # Empty error file, no exceptions could have been raised
-    : 
+    :
   fi
   # Check that the Runtime has not registered any fatal error
   if [ -f "${runtime_log}" ]; then
     if grep -E "ErrorManager\\].*\\[ERRMGR\\].*Error detected. Shutting down COMPSs" "${runtime_log}"; then
       echo "ERROR: ErrorManager has registered a fatal error in the runtime.log" | tee -a "${output_file}"
-      exit 1 
+      exit 1
     fi
   else
     echo "[ERROR] runtime.log not found" | tee -a "${output_file}"
-    exit 1 
+    exit 1
+  fi
+
+  #----------------------------------------------------------------------------------
+  # Grep for unit test errors (ERROR or FAIL)
+  errors=$(cat "${output_file}" "${error_file}" | grep "ERROR" | cat)
+  fails=$(cat "${output_file}" "${error_file}" | grep "FAIL" | cat)
+  if [ "${errors}" != "" ] || [ "${fails}" != "" ]; then
+      echo "ERROR: UNIT TEST RAISED AN ERROR." | tee -a "${output_file}"
+      exit 1
   fi
 
   #----------------------------------------------------------------------------------
   # Compute result status
-  FILES=32
+  FILES=7
+  resultN=7
 
   # Checks if the file has been written as many times as expected
-  result=$(cat /tmp/sharedDisk/taskGroups.txt)
-  if [ ${#result} -ne $FILES ]; then
-    echo "ERROR: The number of writing tasks is not correct. ${#result} "
+  result=$(cat /tmp/sharedDisk/taskGROUPS.txt)
+  if [ ${#result} -ne $resultN ]; then
+    echo "ERROR: The number of writing tasks is not correct. ${result} "
     exit 1
   fi
 
@@ -65,7 +72,21 @@
     echo "ERROR: More tasks than expected have been executed."
     exit 1
   fi
-  
+
+  # Check if all successors have been canceled
+  output1=$(cat "${runtime_log}" | grep "Task canceled:" | wc -l)
+  if [ "${output1}" -ne 6 ]; then
+  	echo "ERROR: The number of canceled tasks is not correct."
+  	exit 1
+  fi
+
+  # Check if the tasks have raised a COMPSsException
+  output1=$(grep -c "COMPSs Exception raised :" "${runtime_log}")
+  if [ "${output1}" -ne 3 ]; then
+  	echo "ERROR: The number of COMPSsExceptions raised is not correct."
+  	exit 1
+  fi
+
   #----------------------------------------------------------------------------------
   # Check dot file
   final_graph_got=${target_log_folder}/monitor/complete_graph.dot
@@ -75,6 +96,6 @@
     exit 1
   fi
 
-  #---------------------------------------------------------------------------------- 
+  #----------------------------------------------------------------------------------
   # ALL OK. Report result status
   exit 0
