Implicit and explicit barriers for throwing a COMPSsException

diff --git a/tests/sources/java/1_compss_exception/result b/tests/sources/java/1_compss_exception/result
--- a/tests/sources/java/1_compss_exception/result
+++ b/tests/sources/java/1_compss_exception/result
@@ -66,6 +66,13 @@
     exit 1
   fi
   
+  # Check if the tasks have finished correctly
+  output1=$(cat "${runtime_log}" | grep "end status FINISHED" | wc -l)
+  if [ "${output1}" -ne 6 ]; then
+  	echo "ERROR: The number of correclty finished tasks is not correct. ${output1} (expected 6)"
+  	exit 1
+  fi
+  
   # Check if all successors have been canceled
   output1=$(cat "${runtime_log}" | grep "Task canceled:" | wc -l)
   if [ "${output1}" -ne 4 ]; then
@@ -77,6 +84,13 @@
   output1=$(grep -c "COMPSs Exception raised :" "${runtime_log}")
   if [ "${output1}" -ne 2 ]; then
   	echo "ERROR: The number of COMPSsExceptions raised is not correct."
+  	exit 1
+  fi
+  
+  # Check the exception message
+  output1=$(cat "${runtime_log}" | grep "The thrown exception message is: Exception from write one" | wc -l)
+  if [ "${output1}" -ne 2 ]; then
+  	echo "ERROR: The thrown exception message is not correct."
   	exit 1
   fi
   
diff --git a/tests/sources/python/2_cancel_running_tasks/result b/tests/sources/python/2_cancel_running_tasks/result
--- a/tests/sources/python/2_cancel_running_tasks/result
+++ b/tests/sources/python/2_cancel_running_tasks/result
@@ -52,8 +52,8 @@
 
   #----------------------------------------------------------------------------------
   # Compute result status
-  FILES=8
-  resultN=2
+  FILES=13
+  resultN=4
 
   # Checks if the file has been written as many times as expected
   result=$(cat /tmp/sharedDisk/taskGROUPS.txt | grep -o 2 | wc -l)
@@ -75,22 +75,29 @@
 
   # Check if all tasks have finished
   output1=$(cat "${runtime_log}" | grep "with end status FINISHED" | wc -l)
-  if [ "${output1}" -ne 5 ]; then
+  if [ "${output1}" -ne 10 ]; then
   	echo "ERROR: The number of canceled tasks is not correct."
   	exit 1
   fi
 
   # Check if all members of group have been canceled
   output1=$(cat "${runtime_log}" | grep "with end status CANCELED" | wc -l)
-  if [ "${output1}" -ne 3 ]; then
+  if [ "${output1}" -ne 6 ]; then
   	echo "ERROR: The number of canceled tasks is not correct."
   	exit 1
   fi
 
   # Check if the tasks have raised a COMPSsException
   output1=$(grep -c "COMPSs Exception raised :" "${runtime_log}")
-  if [ "${output1}" -ne 1 ]; then
+  if [ "${output1}" -ne 2 ]; then
   	echo "ERROR: The number of COMPSsExceptions raised is not correct."
+  	exit 1
+  fi
+
+  # Check the exception message
+  output1=$(cat "${runtime_log}" | grep "The thrown exception message is: Exception raised from the third task" | wc -l)
+  if [ "${output1}" -ne 2 ]; then
+  	echo "ERROR: The thrown exception message is not correct. ${output1}"
   	exit 1
   fi
 
