Fixed symlinks creation on post install.

diff --git a/compss/programming_model/bindings/python/commons b/compss/programming_model/bindings/python/commons
--- a/compss/programming_model/bindings/python/commons
+++ b/compss/programming_model/bindings/python/commons
@@ -17,3 +17,42 @@ else:
     print([get_python_lib()][0])
 " )
   }
+
+  create_symbolic_links (){
+    # Setup the appropriate symbolic links to site-packages/dist-packages
+    # $1 -> python version (2 or 3)
+    # $2 -> origin path
+    
+    version=$1
+    origin=$2
+    
+    echo "Looking for package where to place the symbolic links."
+    get_packages_folder python${version}
+
+    # Setup a symbolic link to pycompss
+    ln -sfn ${origin}/pycompss ${packages_folder}/pycompss
+    if [ $? -ne 0 ]; then
+      echo "Failed, to create symbolic link from ${origin}/pycompss to ${packages_folder}/pycompss"
+      exit 1
+    else
+      echo "Created symbolic link from ${origin}/pycompss to ${packages_folder}/pycompss"
+    fi
+
+    # Setup a symbolic link to compss module
+    ln -sfn ${origin}/compss.* ${packages_folder}/
+    if [ $? -ne 0 ]; then
+      echo "Failed, to create symbolic link from ${origin}/compss.* to ${packages_folder}/compss.*"
+      exit 1
+    else
+      echo "Created symbolic link from ${origin}/compss.* to ${packages_folder}/compss.*"
+    fi
+
+    # Setup a symbolic link to thread affinity module
+    ln -sfn ${origin}/thread_affinity.* ${packages_folder}/
+    if [ $? -ne 0 ]; then
+      echo "Failed, to create symbolic link from ${origin}/thread_affinity.* to ${packages_folder}/thread_affinity.*"
+      exit 1
+    else
+      echo "Created symbolic link from ${origin}/thread_affinity.* to ${packages_folder}/thread_affinity.*"
+    fi
+  }
