Added python binding installation checks.

diff --git a/compss/programming_model/bindings/python/install b/compss/programming_model/bindings/python/install
--- a/compss/programming_model/bindings/python/install
+++ b/compss/programming_model/bindings/python/install
@@ -37,8 +37,22 @@
     #export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-armhf
 
     if command_exists python$1 ; then
+      # Check that the sources can be byte-compiled - this avoids syntax errors
+      # that are not checked on the installation
+      python$1 -m compileall ${SCRIPT_DIR}/src/pycompss
+      exitCode=$?
+      if [ $exitCode -ne 0 ]; then
+        echo "ERROR: Cannot install PyCOMPSs for Python $1 - Could not byte-compile."
+        exit $exitCode
+      fi
+      # Do the installation
       python$1 ${SCRIPT_DIR}/setup.py install --install-lib=${PYCOMPSS_HOME} -O2
       exitCode=$?
+      if [ $exitCode -ne 0 ]; then
+        echo "ERROR: Cannot install PyCOMPSs for Python $1"
+        exit $exitCode
+      fi
+      # Unify installed versions
       if [ $1 == "3" ] && [ -d "${targetDir}/2" ] && [ "$unify_installs" = "true" ]; then
         unify_installed_versions "${targetDir}"
       fi
@@ -47,12 +61,9 @@
         # Pip package sets these symbolic links and updates the 'activate' script accordingly.
         create_symbolic_links $1 "${PYCOMPSS_HOME}"
       fi
-      if [ $exitCode -ne 0 ]; then
-        echo "ERROR: Cannot install PyCOMPSs for Python $1"
-        exit $exitCode
-      fi
     else
-      echo "WARNING: PyCOMPSS FOR PYTHON $1 HAS NOT BEEN INSTALLED."
+      echo "ERROR! python$1 IS NOT AVAILABLE."
+      exit 1
     fi
   }
 
@@ -88,6 +99,7 @@
         install 3
       else
         echo "ERROR! UNSUPPORTED TARGET DIRECTORY WITHIN site-packages OR dist-packages."
+        exit 1
       fi
     else
       # Install all
@@ -104,6 +116,7 @@
     install 3
   else
     echo "ERROR! UNSUPPORTED PYTHON VERSION."
+    exit 1
   fi
 
   # Copy cleaning and commons scripts for setup or uninstalling
