Added configurable port to GOSAdaptor

diff --git a/tests/sources/local/gos_batch/2_runcompss/execution b/tests/sources/local/gos_batch/2_runcompss/execution
--- a/tests/sources/local/gos_batch/2_runcompss/execution
+++ b/tests/sources/local/gos_batch/2_runcompss/execution
@@ -13,117 +13,134 @@
   # Global variables
   exit_value=1
   app_name="decorator_mpi.py"
+  test_name="2_runcompss"
+  pyPath="simple_compss_nested.py"
 
   #----------------------------------------------------------------------------------
-  test_name="2_runcompss"
 
-    # Process extra execution envs
+  # Process extra execution envs
+  VARIABLES=($(echo "$execution_envs" | tr "|" "\n"))
+  if [ "${#VARIABLES[@]}" -lt 5 ]; then
+    echo "[ERROR] Not enough variables declared in execution_envs, try launching with corresponding configuration."
+    echo "[ERROR] Aborting execution for not enough input arguments for the xml files."
+    exit 1
+  fi
+
+  PORT=22
+  QOS="default"
+  RESERVATION="disabled"
+  INSTALL_DIR="/apps/COMPSs/Trunk"
+  APP_DIR="${base_app_dir}"
+
+  WK_DIR="${base_app_dir}/COMPSsWorker"
+  CLASSPATH="${base_app_dir}/${jar_name}"
+  PYTHONPATH="${base_app_dir}/src"
+  ENV_SCRIPT="${base_app_dir}/env.sh"
+  REAL_ENVIRONMENT_ENVS=""
 
     # shellcheck disable=SC2207
-    VARIABLES=($(echo "$execution_envs" | tr "|" "\n"))
-    for item in ${VARIABLES[*]}
-      do
-          # shellcheck disable=SC2207
-          var=($(echo "$item" | tr "=" "\n"))
-          echo "var : ${var[0]} value: ${var[1]}"
-          case ${var[0]} in
-          INSTALL_DIR)
-          	if [ "${var[1]}" = "DEFAULT" ]; then
-              INSTALL_DIR="/apps/COMPSs/Trunk"
-            else
-              INSTALL_DIR=${var[1]}
-            fi
-          	;;
-          USER)
-          	USER=${var[1]}
-          	;;
-          HOST)
-          	HOST=${var[1]}
-          	#copy to host appDIR
-          	;;
-          ENV_SCRIPT)
-            if [ "${var[1]}" = "DEFAULT" ]; then
-              ENV_SCRIPT="${base_app_dir}"/env.sh
-            else
-          	  ENV_SCRIPT=${var[1]}
-          	fi
-          	;;
-          QUEUE)
-          	QUEUE=${var[1]}
-          	;;
-          QOS)
-          	QOS=${var[1]}
-          	;;
-          WK_DIR)
-            if [ "${var[1]}" = "DEFAULT" ]; then
-              ENV_SCRIPT="${base_app_dir}"/COMPSsWorker
-            else
-          	  WK_DIR=${var[1]}
-            fi
+  for item in ${VARIABLES[*]}
+    do
+        # shellcheck disable=SC2207
+        var=($(echo "$item" | tr "=" "\n"))
+        echo "var : ${var[0]} value: ${var[1]}"
+        case ${var[0]} in
+        INSTALL_DIR)
+          if [ ! "${var[1]}" = "DEFAULT" ]; then
+            INSTALL_DIR=${var[1]}
+          fi
+          ;;
+        USER)
+          USER=${var[1]}
+          ;;
+        HOST)
+          HOST=${var[1]}
+          ;;
+       REAL_ENVIRONMENT_ENVS)
+         if [ "${var[1]}" = "DEFAULT" ]; then
+           REAL_ENVIRONMENT_ENVS=""
+         else
+           REAL_ENVIRONMENT_ENVS=${var[1]}
+         fi
+         ;;
+        ENV_SCRIPT)
+          if [ "${var[1]}" = "DEFAULT" ]; then
+            ENV_SCRIPT="${APP_DIR}/env.sh"
+          else
+            ENV_SCRIPT=${var[1]}
+          fi
+          ;;
+        QUEUE)
+            QUEUE=${var[1]}
             ;;
-          COMPUTER)
-            if [ "${var[1]}" = "DEFAULT" ]; then
-              COMPUTER="nord3"
-            else
-              COMPUTER=${var[1]}
-            fi
-          	;;
-         APP_DIR)
-            if [ "${var[1]}" = "DEFAULT" ]; then
-               CLASSPATH="${base_app_dir}/${jar_name}"
-               APP_DIR="${base_app_dir}"
-            else
-              if [ -n "$test_name" ]; then
-               test_name="${jar_name::-4}"
-              fi
-              CLASSPATH="${var[1]}/${test_name}/target/${jar_name}"
-              APP_DIR="${base_app_dir}"
-            fi
-            ;;
-          PYTHONPATH)
-               if [ "${var[1]}" = "DEFAULT" ]; then
-                  PYTHONPATH="${base_app_dir}/src"
-               else
-                 if [ -n "$test_name" ]; then
-                    test_name="${app_name::-3}"
-                 fi
-                 PYTHONPATH="${var[1]}/target/${test_name}"
-               fi
-            ;;
-          esac
-      done
-      FILE_CFG="${INSTALL_DIR}/Runtime/scripts/queues/supercomputers/${COMPUTER}.cfg"
-      projectFile="${base_app_dir}"/project.xml
-      resourcesFile="${base_app_dir}"/resources.xml
+        PORT)
+          PORT=${var[1]}
+          ;;
+        RESERVATION)
+          RESERVATION=${var[1]}
+          ;;
+        QOS)
+          QOS=${var[1]}
+          ;;
+        WK_DIR)
+          if [ ! "${var[1]}" = "DEFAULT" ]; then
+            WK_DIR=${var[1]}
+          fi
+          ;;
+        COMPUTER)
+          if [ ! "${var[1]}" = "DEFAULT" ]; then
+            COMPUTER=${var[1]}
+          fi
+          ;;
+       APP_DIR)
+          if [ ! "${var[1]}" = "DEFAULT" ]; then
+            APP_DIR="${var[1]}/${test_name}"
+            CLASSPATH="${APP_DIR}/target/${jar_name}"
+          fi
+          ;;
+        PYTHONPATH)
+             if [ "${var[1]}" = "DEFAULT" ]; then
+                PYTHONPATH="${base_app_dir}/src/${pyPath}"
+             else
+               PYTHONPATH="${var[1]}"
+             fi
+          ;;
+        esac
+    done
+    FILE_CFG="${INSTALL_DIR}/Runtime/scripts/queues/supercomputers/${COMPUTER}.cfg"
+    projectFile="${base_app_dir}"/project.xml
+    resourcesFile="${base_app_dir}"/resources.xml
 
-      sed -i '/<Queue>/c<Queue>'"${QUEUE}"'<\/Queue>' "$resourcesFile"
+    sed -i '/<Queue>/c<Queue>'"${QUEUE}"'<\/Queue>' "$resourcesFile"
 
-      sed -i '/<Queue>/c<Queue>'"${QUEUE}"'<\/Queue>' "$projectFile"
-      sed -i '/<QOS>/c<QOS>'"${QOS}"'<\/QOS>' "$projectFile"
-      sed -i '/<InstallDir>/c<InstallDir>'"${INSTALL_DIR}"'<\/InstallDir>' "$projectFile"
-      sed -i '/<WorkingDir>/c<WorkingDir>'"${WK_DIR}"'<\/WorkingDir>' "$projectFile"
-      sed -i '/<AppDir>/c<AppDir>'"${APP_DIR}"'<\/AppDir>' "$projectFile"
-      sed -i '/<Classpath>/c<Classpath>'"${CLASSPATH}"'<\/Classpath>' "$projectFile"
-      sed -i '/<Pythonpath>/c<Pythonpath>'"${PYTHONPATH}"'<\/Pythonpath>' "$projectFile"
-      sed -i '/<EnvironmentScript>/c<EnvironmentScript>'"${ENV_SCRIPT}"'<\/EnvironmentScript>' "$projectFile"
-      sed -i '/<User>/c<User>'"${USER}"'<\/User>' "$projectFile"
-      sed -i '/<FileCFG>/c<FileCFG>'"${FILE_CFG}"'<\/FileCFG>' "$projectFile"
+    sed -i '/<Queue>/c<Queue>'"${QUEUE}"'<\/Queue>' "$projectFile"
+    sed -i '/<QOS>/c<QOS>'"${QOS}"'<\/QOS>' "$projectFile"
+    sed -i '/<InstallDir>/c<InstallDir>'"${INSTALL_DIR}"'<\/InstallDir>' "$projectFile"
+    sed -i '/<WorkingDir>/c<WorkingDir>'"${WK_DIR}"'<\/WorkingDir>' "$projectFile"
+    sed -i '/<AppDir>/c<AppDir>'"${APP_DIR}"'<\/AppDir>' "$projectFile"
+    sed -i '/<Classpath>/c<Classpath>'"${CLASSPATH}"'<\/Classpath>' "$projectFile"
+    sed -i '/<Pythonpath>/c<Pythonpath>'"${PYTHONPATH}"'<\/Pythonpath>' "$projectFile"
+    sed -i '/<EnvironmentScript>/c<EnvironmentScript>'"${ENV_SCRIPT}"'<\/EnvironmentScript>' "$projectFile"
+    sed -i '/<User>/c<User>'"${USER}"'<\/User>' "$projectFile"
+    sed -i '/<FileCFG>/c<FileCFG>'"${FILE_CFG}"'<\/FileCFG>' "$projectFile"
+    sed -i '/<Port>/c<Port>'"${PORT}"'<\/Port>' "$projectFile"
 
-      sed -i '/<ComputeNode Name=/c<ComputeNode Name=\"'"${HOST}"'\">' "$resourcesFile"
-      sed -i '/<ComputingCluster Name=/c<ComputingCluster Name=\"'"${HOST}"'\">' "$resourcesFile"
-      sed -i '/<ComputeNode Name=/c<ComputeNode Name=\"'"${HOST}"'\">' "$projectFile"
-      sed -i '/<ComputingCluster Name=/c<ComputingCluster Name=\"'"${HOST}"'\">' "$projectFile"
+    sed -i '/<ComputeNode Name=/c<ComputeNode Name=\"'"${HOST}"'\">' "$resourcesFile"
+    sed -i '/<ComputingCluster Name=/c<ComputingCluster Name=\"'"${HOST}"'\">' "$resourcesFile"
+    sed -i '/<ComputeNode Name=/c<ComputeNode Name=\"'"${HOST}"'\">' "$projectFile"
+    sed -i '/<ComputingCluster Name=/c<ComputingCluster Name=\"'"${HOST}"'\">' "$projectFile"
 
 
 
-      execution_envs=""
+
+  execution_envs=$REAL_ENVIRONMENT_ENVS
 
   #----------------------------------------------------------------------------------
   # Run application
   echo
   echo "*** RUNNING PYTHON APPLICATION DECORATOR MPI"
-  export RUNCOMPSS="/home/bsc19/bsc19409/COMPSsInstallDIR/opt/COMPSs/Runtime/scripts/user/runcompss"
-  export APP_DIR="/home/bsc19/bsc19409/apps/sources/local/python/1_decorator_compss/"
+  export RUNCOMPSS="${INSTALL_DIR}/Runtime/scripts/user/runcompss"
+  export APP_DIR
 
   export CUS=2
 
