Friendlier command line.

diff --git a/builders/specs/pip-headless/pyCOMPSsHeadlessResources/pycompss-headless/pycompss b/builders/specs/pip-headless/pyCOMPSsHeadlessResources/pycompss-headless/pycompss
--- a/builders/specs/pip-headless/pyCOMPSsHeadlessResources/pycompss-headless/pycompss
+++ b/builders/specs/pip-headless/pyCOMPSsHeadlessResources/pycompss-headless/pycompss
@@ -11,8 +11,61 @@ shift 1
 
 export PYTHONPATH=$PYTHONPATH:${cmd_path}
 
-if [ -z "${cmd}" ] || [ "$cmd" == "help" ]; then
+if [ "${cmd}" == "init" ]; then
+    working_dir=$1
+    python3 -c "from pycompss_cmd import _start_daemon; _start_daemon(working_dir='${working_dir}')"
 
+elif [ "${cmd}" == "update" ]; then
+    echo "Updating docker image"
+    docker_image="compss/compss:2.6"
+    if [ -n "${COMPSS_DOCKER_IMAGE}" ]; then
+        echo "Found COMPSS_DOCKER_IMAGE environment variable: '$COMPSS_DOCKER_IMAGE'. Updating.";
+        docker_image=$COMPSS_DOCKER_IMAGE
+    else
+        echo "COMPSS_DOCKER_IMAGE is unset or empty. Updating default docker image: $docker_image";
+    fi
+    docker pull $docker_image
+
+elif [ "${cmd}" == "kill" ]; then
+    python3 -c "from pycompss_cmd import _stop_daemon; _stop_daemon(True)"
+
+elif [ "${cmd}" == "run" ]; then    subcmd=$@
+    python3 -c "from pycompss_cmd import _exec_in_daemon; _exec_in_daemon('${subcmd}')"
+
+elif [ "${cmd}" == "exec" ]; then
+    params=$@
+    python3 -c "from pycompss_cmd import _exec_in_daemon; \
+    _exec_in_daemon('runcompss \
+        --project=/project.xml \
+        --resources=/resources.xml \
+        --master_name=172.17.0.2 \
+        ${params}')"
+
+elif [ "${cmd}" == "monitor" ]; then
+    option=$1
+    if [ "${option}" == "start" ]; then
+        python3 -c "from pycompss_cmd import _start_monitoring; _start_monitoring()"
+    elif [ "${option}" == "stop" ]; then
+        python3 -c "from pycompss_cmd import _stop_monitoring; _stop_monitoring()"
+    else
+        echo "Unexpected option for monitoring: ${option}"
+        echo "Please, use start or stop."
+    fi
+
+elif [ "${cmd}" == "jupyter" ]; then
+    params=$@
+    subcmd="jupyter-notebook ${params} --ip=0.0.0.0 --allow-root"
+    python3 -c "from pycompss_cmd import _exec_in_daemon; _exec_in_daemon('${subcmd}')"
+
+elif [ "${cmd}" == "components" ]; then
+    subcmd=$@
+    python3 -c "from pycompss_cmd import _components; _components(arg='${subcmd}')"
+
+else
+    if ! { [ -z "${cmd}" ] || [ "$cmd" == "help" ]; }; then
+        echo "ERROR: Unknown command: $cmd"
+        echo ""
+    fi
     echo "PyCOMPSs|COMPSS Headless:"
     echo ""
     echo "Usage: pycompss COMMAND  |  compss COMMAND"
@@ -37,63 +90,5 @@ if [ -z "${cmd}" ] || [ "$cmd" == "help" ]; then
     echo ""
     echo "Define the COMPSS_DOCKER_IMAGE environment variable to use a different COMPSs docker image."
     echo ""
-fi
-
-if [ "${cmd}" == "init" ]; then
-    working_dir=$1
-    python3 -c "from pycompss_cmd import _start_daemon; _start_daemon(working_dir='${working_dir}')"
-fi
-
-if [ "${cmd}" == "update" ]; then
-    echo "Updating docker image"
-    docker_image="compss/compss:2.6"
-    if [ -n "${COMPSS_DOCKER_IMAGE}" ]; then
-        echo "Found COMPSS_DOCKER_IMAGE environment variable: '$COMPSS_DOCKER_IMAGE'. Updating.";
-        docker_image=$COMPSS_DOCKER_IMAGE
-    else
-        echo "COMPSS_DOCKER_IMAGE is unset or empty. Updating default docker image: $docker_image";
-    fi
-    docker pull $docker_image
-fi
-
-if [ "${cmd}" == "kill" ]; then
-    python3 -c "from pycompss_cmd import _stop_daemon; _stop_daemon(True)"
-fi
-
-if [ "${cmd}" == "run" ]; then    subcmd=$@
-    python3 -c "from pycompss_cmd import _exec_in_daemon; _exec_in_daemon('${subcmd}')"
-fi
-
-if [ "${cmd}" == "exec" ]; then
-    params=$@
-    python3 -c "from pycompss_cmd import _exec_in_daemon; \
-    _exec_in_daemon('runcompss \
-        --project=/project.xml \
-        --resources=/resources.xml \
-        --master_name=172.17.0.2 \
-        ${params}')"
-fi
-
-if [ "${cmd}" == "monitor" ]; then
-    option=$1
-    if [ "${option}" == "start" ]; then
-        python3 -c "from pycompss_cmd import _start_monitoring; _start_monitoring()"
-    elif [ "${option}" == "stop" ]; then
-        python3 -c "from pycompss_cmd import _stop_monitoring; _stop_monitoring()"
-    else
-        echo "Unexpected option for monitoring: ${option}"
-        echo "Please, use start or stop."
-    fi
-fi
-
-if [ "${cmd}" == "jupyter" ]; then
-    params=$@
-    subcmd="jupyter-notebook ${params} --ip=0.0.0.0 --allow-root"
-    python3 -c "from pycompss_cmd import _exec_in_daemon; _exec_in_daemon('${subcmd}')"
-fi
-
-if [ "${cmd}" == "components" ]; then
-    subcmd=$@
-    python3 -c "from pycompss_cmd import _components; _components(arg='${subcmd}')"
 
 fi
