HTTP Task Java tests.

diff --git a/tests/sources/local/java/1_http_task/execution b/tests/sources/local/java/1_http_task/execution
--- a/tests/sources/local/java/1_http_task/execution
+++ b/tests/sources/local/java/1_http_task/execution
@@ -14,10 +14,30 @@
   exit_value=0
   jar_name="1_http_task.jar"
   app_name="testHttpTask.TestHttpTask"
+  ws_jar_name="jars/ws.jar"
 
-#----------------------------------------------------------------------------------
+
+  #----------------------------------------------------------------------------------
   # Generate Project.xml according to system
   sed -i '/<InstallDir>/c<InstallDir>'"${COMPSS_HOME}"'<\/InstallDir>' "${base_app_dir}"/project.xml
+
+
+  #----------------------------------------------------------------------------------
+  echo "*** STARTING THE WEB SERVICE"
+  java -jar ${ws_jar_name} &
+  ws_pid="$!"
+  sleep 2
+
+  check_ws="$(curl -XGET http://localhost:1992/test/dummy 2>/dev/null)"
+
+  if [ "$check_ws" == "it_works" ]; then
+    echo
+    echo "*** WEB SERVICE RUNNING WITH PID: ${ws_pid}"
+  else
+    kill -9 ${ws_pid}
+    echo " Cannot start Web Service"
+    exit 1
+  fi
 
   #----------------------------------------------------------------------------------
   echo
@@ -37,24 +57,29 @@
      ${runcompss_opts} \
      -g \
      --classpath="${base_app_dir}/${jar_name}" \
-     \
      "${app_name}" > >(tee "${output_log}") 2> >(tee "${error_log}" >&2)
-  
+
   # Check timeout
   if [[ "$?" = "124" ]]; then
      # Copy LOG files
-     cp -rf "${COMPSs_log_folder}/${app_name}${retry_num}"/* "${target_log_folder}"
-     
+     cp -rf "${COMPSs_log_folder}/${app_name}_0${retry_num}"/* "${target_log_folder}"
+
      # Report time out
      echo "[WARNING] Java Application timed out" >> "${output_log}"
      exit_value=124
   else
      # Copy LOG files
-     cp -rf "${COMPSs_log_folder}/${app_name}${retry_num}"/* "${target_log_folder}"
+     cp -rf "${COMPSs_log_folder}/${app_name}_0${retry_num}"/* "${target_log_folder}"
 
+     # Check result
+     "${base_app_dir}"/result "${output_log}" "${error_log}" "${target_log_folder}"
+     exit_value=$?
   fi
 
-  sleep 10s
+  #----------------------------------------------------------------------------------
+  echo "*** STOPPING THE WEB SERVICE"
+  kill -9 ${ws_pid}
+  echo "*** WEB SERVICE HAS BEEN STOPPED:"
 
   #----------------------------------------------------------------------------------
   # Return execution status
diff --git a/tests/sources/local/java/1_http_task/result b/tests/sources/local/java/1_http_task/result
--- a/tests/sources/local/java/1_http_task/result
+++ b/tests/sources/local/java/1_http_task/result
@@ -1,18 +1,23 @@
 #!/bin/bash -e
 
   # Obtain parameters
-  target_log_folder_0=$1
-  output_file_0=$2
-  error_file_0=$3
-  target_log_folder_1=$4
-  output_file_1=$5
-  error_file_1=$6
+  output_file=$1
+  error_file=$2
+  target_log_folder=$3
 
   # Log files
-  runtime_log_0="${target_log_folder_0}/runtime.log"
-  resources_log_0="${target_log_folder_0}/resources.log"
-  runtime_log_1="${target_log_folder_1}/runtime.log"
-  resources_log_1="${target_log_folder_1}/resources.log"
+  runtime_log="${target_log_folder}/runtime.log"
+  resources_log="${target_log_folder}/resources.log"
+
+  if grep -E "Error running application" "${output_file}"; then
+    echo "ERROR: TESTS FAILED." | tee -a "${output_file}"
+    exit 1
+  fi
+
+  if grep -E "TEST FAILED" "${output_file}"; then
+    echo "ERROR: TESTS FAILED." | tee -a "${output_file}"
+    exit 1
+  fi
 
   #---------------------------------------------------------------------------------- 
   # ALL OK. Report result status
