Changes on tests

diff --git a/tests/sources/fault_tolerance/2_on_failure_cancel_successors_python/result b/tests/sources/fault_tolerance/2_on_failure_cancel_successors_python/result
--- a/tests/sources/fault_tolerance/2_on_failure_cancel_successors_python/result
+++ b/tests/sources/fault_tolerance/2_on_failure_cancel_successors_python/result
@@ -10,26 +10,36 @@
   resources_log="${target_log_folder}/resources.log"
 
   #----------------------------------------------------------------------------------
-  # Do not check standard out/err status since test must fail
-  # Do not check unit tests status since test must fail
-
-  #----------------------------------------------------------------------------------
-  # Compute result status
-  if grep -q "ERROR" "${output_file}"; then
-    echo "An ERROR occurred running the test - INVALID RESULT." | tee -a "${output_file}"
-    exit 2
+  # Check output standard out status
+  if [ -f "${output_file}" ]; then
+     result_expected="------------------------------------------------------------"
+     test_result=$(tail -1 "${output_file}")
+     if [ "${result_expected}" != "${test_result}" ]; then
+        echo "SOME ERROR WAS FOUND. CHECK ERRORS ABOVE." | tee -a "${output_file}"
+        exit 1
+     fi
+  else
+     echo "[ERROR] Output file not found" | tee -a "${output_file}"
+     exit 1
   fi
-
-  # Check that ErrorManager has raised any ERROR or FATAL message
+  # Check that ErrorManager has not raised any ERROR or FATAL message
   if [ -f "${error_file}" ]; then
     if grep -E "\\[ERRMGR\\].*(ERROR|FATAL|Shutting down COMPSs)" "${error_file}"; then
-       echo "[RESULT_CHECKER] ErrorManager raised and ERROR as expected" | tee -a "${output_file}"
-    else
-      echo "[ERROR] ErrorManager did not raise any error" | tee -a "${output_file}"
+      echo "ERROR: ErrorManager has raised a fatal error" | tee -a "${output_file}"
       exit 1
     fi
   else
-    echo "[ERROR] ErrorManager did not raise any error" | tee -a "${output_file}"
+    # Empty error file, no exceptions could have been raised
+    :
+  fi
+  # Check that the Runtime has not registered any fatal error
+  if [ -f "${runtime_log}" ]; then
+    if grep -E "ErrorManager\\].*\\[ERRMGR\\].*Error detected. Shutting down COMPSs" "${runtime_log}"; then
+      echo "ERROR: ErrorManager has registered a fatal error in the runtime.log" | tee -a "${output_file}"
+      exit 1
+    fi
+  else
+    echo "[ERROR] runtime.log not found" | tee -a "${output_file}"
     exit 1
   fi
 
@@ -40,9 +50,9 @@
   tasks=4
 
   # Checks if the file has been writen as many times as expected
-  result=$(cat /tmp/sharedDisk/onFailure1.txt)
-  if [ ${result} -ne $resultN ]; then
-    echo "ERROR: The number of writing tasks is not correct. ${#result} "
+  result=$(cat /tmp/sharedDisk/file1.txt)
+  if [ "${result}" -ne $resultN ]; then
+    echo "ERROR: The number of writing tasks is not correct. ${result} "
     exit 1
   fi
 
@@ -59,11 +69,12 @@
 
   # Check if all successors have been canceled
   output1=$(cat "${runtime_log}" | grep "Task canceled:" | wc -l)
-  if [ ${output1} -ne $(($tasks-$FILES)) ]; then
+  if [ ${output1} -ne $((tasks-FILES)) ]; then
   	echo "ERROR: All tasks have not been canceled."
   	exit 1
   fi
 
+  rm /tmp/sharedDisk/file1.txt
   #----------------------------------------------------------------------------------
   # ALL OK. Report result status
   exit 0
