added check for no release name

diff --git a/utils/scripts/update_version/main_internal_release b/utils/scripts/update_version/main_internal_release
--- a/utils/scripts/update_version/main_internal_release
+++ b/utils/scripts/update_version/main_internal_release
@@ -19,6 +19,13 @@ usage() {
   # Compute version
   version=$1
 
+   if [ -z "$version" ]; then
+     echo "ERROR: jenkins build parameter 'version' not set."
+     exit 1
+   fi
+
+
+
   # Get base version from trunk
   SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
   trunk_dir=${SCRIPT_DIR}/../../../
