Added computing units check on mpi test for PyCOMPSs (60).
git-svn-id: http://compss.bsc.es/svn/compss/framework/trunk@3052 9ab3861e-6c05-4e1b-b5ef-99af60850597

Former-commit-id: c50f54b998805488c7fbc4715f0879fd859b1999

diff --git a/tests/sources/basic/60-mpiDecorator_python/result b/tests/sources/basic/60-mpiDecorator_python/result
--- a/tests/sources/basic/60-mpiDecorator_python/result
+++ b/tests/sources/basic/60-mpiDecorator_python/result
@@ -43,6 +43,12 @@
   if ! $(cat "$monday" | grep -E -q "$mondayDate"); then
     echo "ERROR: TASK FAILED: testFunctionalUsageWithConstraint function failed." | tee -a ${output_file}
     exit 1
+  else
+    apearances=$(cat "$monday" | grep "$mondayDate" | wc -l)
+    if [ ! "$apearances" -eq "2" ]; then
+      echo "ERROR: TASK FAILED: testFunctionalUsageWithConstraint function computingNodes parameter failed." | tee -a ${output_file}
+      exit 1
+    fi
   fi
 
 
