Added test check for the master events.

diff --git a/tests/sources/tools/0_tracing_basic_python/result b/tests/sources/tools/0_tracing_basic_python/result
--- a/tests/sources/tools/0_tracing_basic_python/result
+++ b/tests/sources/tools/0_tracing_basic_python/result
@@ -56,11 +56,14 @@
   #----------------------------------------------------------------------------------
   number_of_tasks=32
   number_of_workers=1
+  number_of_master_events=47
+  number_of_master_finish_events=46  # The last compss stop does not include 0 since the runtime has been stopped and the trace generated.
 
   # Should be equal to Tracer.java definitions
   SYNC_EVENTS=8000666
   TASK_EVENTS=60000100
   WORKER_EVENTS=60000200
+  MASTER_EVENTS=60000300
 
   WORKER_RUNNING=1
 
@@ -73,14 +76,22 @@
       echo "evts_tasks: ${evts_tasks}"
       evts_tasks_end=$(grep -c ":${TASK_EVENTS}:0" "${target_log_folder}"/trace/task_tracing_kmeans.py_compss_trace_*.prv)
       echo "evts_tasks_end: ${evts_tasks_end}"
+
       evts_tasks_running=$(grep -c ":${WORKER_EVENTS}:2:" "${target_log_folder}"/trace/task_tracing_kmeans.py_compss_trace_*.prv)
       echo "evts_tasks_running: ${evts_tasks_runing}"
+
       evts_worker_running=$(grep -c ":${WORKER_EVENTS}:${WORKER_RUNNING}" "${target_log_folder}"/trace/task_tracing_kmeans.py_compss_trace_*.prv)
       echo "evts_worker_running: ${evts_worker_running}"
+
       sync_evts_init=$(grep -c ":${SYNC_EVENTS}:[1-9][0-9]*" "${target_log_folder}"/trace/task_tracing_kmeans.py_compss_trace_*.prv)
       echo "sync_evts_init: ${sync_evts_init}"
       sync_evts_end=$(grep -c ":${SYNC_EVENTS}:0" "${target_log_folder}"/trace/task_tracing_kmeans.py_compss_trace_*.prv)
       echo "sync_evts_end: ${sync_evts_end}"
+
+      master_evts_init=$(grep -c ":${MASTER_EVENTS}:[1-9][0-9]*" "${target_log_folder}"/trace/task_tracing_kmeans.py_compss_trace_*.prv)
+      echo "master_evts_init: ${master_evts_init}"
+      master_evts_end=$(grep -c ":${MASTER_EVENTS}:0" "${target_log_folder}"/trace/task_tracing_kmeans.py_compss_trace_*.prv)
+      echo "master_evts_end: ${master_evts_end}"
 
       if [ "${evts_tasks_end}" != "${evts_tasks}" ]; then
          echo "[ERROR] Start and end events counts do not match. [${evts_tasks}/${evts_tasks_end}]" | tee -a "${output_file}"
@@ -100,6 +111,17 @@
       if [ "${sync_evts_init}" != "$((4 * number_of_workers))" ] || [ "${sync_evts_end}" != "$((4 * number_of_workers))" ]; then
         echo "[ERROR] Number of start and end synchronization events are not 8 times the number of workers.
         Expected events: $((8 * number_of_workers)) != Found Events: [${sync_evts_init} + ${sync_evts_end}]" | tee -a "${output_file}"
+        exit 1
+      fi
+
+      if [ "${master_evts_init}" != "$number_of_master_events" ]; then
+        echo "[ERROR] Number of master events does not match the expected.
+        Expected events: $number_of_master_events != Found Events: ${master_evts_init}" | tee -a "${output_file}"
+        exit 1
+      fi
+      if [ "${master_evts_end}" != "$number_of_master_finish_events" ]; then
+        echo "[ERROR] Number of master finish (0) events does not match the expected.
+        Expected events: $number_of_master_finish_events != Found Events: ${master_evts_end}" | tee -a "${output_file}"
         exit 1
       fi
   fi
