Added events in tracing test.

diff --git a/tests/sources/local/tools/0_tracing_basic_python/result b/tests/sources/local/tools/0_tracing_basic_python/result
--- a/tests/sources/local/tools/0_tracing_basic_python/result
+++ b/tests/sources/local/tools/0_tracing_basic_python/result
@@ -107,8 +107,12 @@
       exit 1
     fi
 
-    if [ "${sync_evts_init}" -ne "$((4 * number_of_workers))" ] || [ "${sync_evts_end}" -ne "$((4 * number_of_workers))" ]; then
-      echo "[ERROR] Number of start and end synchronization events are not 8 times the number of workers. Expected events: $((8 * number_of_workers)) != Found Events: [${sync_evts_init} + ${sync_evts_end}]" | tee -a "${output_file}"
+    if [ "${sync_evts_init}" -ne "$((5 * number_of_workers))" ]; then
+      echo "[ERROR] Number of start synchronization events are not 5 times the number of workers. Expected events: $((5 * number_of_workers)) != Found Events: ${sync_evts_init}" | tee -a "${output_file}"
+      exit 1
+    fi
+    if [ "${sync_evts_end}" -ne "$((6 * number_of_workers))" ]; then
+      echo "[ERROR] Number of end synchronization events are not 6 times the number of workers. Expected events: $((6 * number_of_workers)) != Found Events: ${sync_evts_end}" | tee -a "${output_file}"
       exit 1
     fi
 
