[PyCOMPSs] Added support for Streams and Prefixes.
git-svn-id: http://compss.bsc.es/svn/compss/framework/trunk@3218 9ab3861e-6c05-4e1b-b5ef-99af60850597

Former-commit-id: adb6fef94af9a684c199cc27d00001c86d7e0efa

diff --git a/tests/sources/basic/58-binaryDecorator_python/result b/tests/sources/basic/58-binaryDecorator_python/result
--- a/tests/sources/basic/58-binaryDecorator_python/result
+++ b/tests/sources/basic/58-binaryDecorator_python/result
@@ -49,7 +49,12 @@
      echo "ERROR: TASK FAILED: testFileManagementIN function failed." | tee -a ${output_file}
     exit 1
   fi
-  
+
+  if grep -q "do" src/grepoutfile; then
+    echo "ERROR: TASK FAILED: testFileManagement function failed."  | tee -a ${output_file}
+    exit 1
+  fi
+
   #----------------------------------------------------------------------------------
   # Grep for unit test errors (ERROR or FAIL)
   errors=$(cat "${output_file}" "${error_file}" | grep "ERROR" | cat)
