Improved test 58 results check and homogeneized with tests 59 and 60.

diff --git a/tests/sources/basic/58-binaryDecorator_python/result b/tests/sources/basic/58-binaryDecorator_python/result
--- a/tests/sources/basic/58-binaryDecorator_python/result
+++ b/tests/sources/basic/58-binaryDecorator_python/result
@@ -10,20 +10,20 @@
 
   #----------------------------------------------------------------------------------
   # Check output standard out status
-  if [ -f "${output_file}" ]; then
+  if [ -f ${output_file} ]; then
      result_expected="------------------------------------------------------------"
-     test_result=$(tail -1 "${output_file}")
+     test_result=$(tail -1 ${output_file})
      if [ "${result_expected}" != "${test_result}" ]; then
-        echo "SOME ERROR WAS FOUND. CHECK ERRORS ABOVE." | tee -a "${output_file}"
+        echo "SOME ERROR WAS FOUND. CHECK ERRORS ABOVE." | tee -a ${output_file}
         exit 1
      fi
   else
-     echo "SOME ERROR WAS FOUND. CHECK ERRORS ABOVE." | tee -a "${output_file}"
+     echo "SOME ERROR WAS FOUND. CHECK ERRORS ABOVE." | tee -a ${output_file}
      exit 1
   fi
   # Check that ErrorManager has not generated any ERROR or FATAL message.
-  if cat "${output_file}" "${runtime_log}" | tr '\n' ' ' | grep -E -q "[ERRMGR].*(ERROR|FATAL):.*.*Shutting"; then
-    echo "ERROR: ERRMGR RAISED A FATAL ERROR. TEST FAILED." | tee -a "${output_file}"
+  if $(cat "${output_file}" "${runtime_log}" | tr '\n' ' ' | grep -E -q "[ERRMGR].*(ERROR|FATAL):.*.*Shutting"); then
+    echo "ERROR: ERRMGR RAISED A FATAL ERROR. TEST FAILED." | tee -a ${output_file}
     exit 1
   fi
 
@@ -53,6 +53,12 @@
     echo "  - GOT:      $monday" | tee -a "${output_file}"
     echo "  - EXPECTED: $mondayDate1 or $mondayDate2" | tee -a "${output_file}"
     exit 1
+  else
+    appearances=$(cat "$monday_file" | grep "$mondayDate2" | wc -l)
+    if [ ! "$appearances" -eq "1" ]; then
+      echo "ERROR: TASK FAILED: testFunctionalUsageWithConstraint function appearances check failed." | tee -a ${output_file}
+      exit 1
+    fi
   fi
 
   tuesday_file=$(grep -r -l "date -d next tuesday" "$jobs_logs")
@@ -70,27 +76,48 @@
     exit 1
   fi
 
-  hello=$(grep -r -l "HELLO, this is a simple test to grep." "$jobs_logs")
+  hellofile=$(grep -r -l "sed s/Hi/HELLO/g" $jobs_logs)
+  hello=$(grep -r -l "HELLO, this is a simple test to grep." $hellofile)
   if [[ -z "$hello" ]]; then
-     echo "ERROR: TASK FAILED: testFileManagementIN function failed." | tee -a "${output_file}"
+     echo "ERROR: TASK FAILED: testFileManagementIN function failed." | tee -a ${output_file}
     exit 1
+  else
+    appearances=$(cat "$hellofile" | grep "HELLO, this is a simple test to grep." | wc -l)
+    if [ ! "$appearances" -eq "4" ]; then
+      echo "ERROR: TASK FAILED: testFileManagementIN function appearances check failed." | tee -a ${output_file}
+      exit 1
+    fi
   fi
 
   if grep -q "do" src/grepoutfile; then
-    echo "ERROR: TASK FAILED: testFileManagement function failed."  | tee -a "${output_file}"
+    echo "ERROR: TASK FAILED: testFileManagement function failed."  | tee -a ${output_file}
     exit 1
   fi
 
-  myLs=$(grep -r -l "ls -l --hide=.*infile.* --sort=size" "$jobs_logs")
+  myLs=$(grep -r -l "ls -l --hide=.*infile.* --sort=size" $jobs_logs)
   if [[ -z "$myLs" ]]; then
-     echo "ERROR: TASK FAILED: testFilesAndPrefix function failed." | tee -a "${output_file}"
+    echo "ERROR: TASK FAILED: testFilesAndPrefix function failed." | tee -a ${output_file}
     exit 1
+  else
+      # Check how many infile are that are symlinks (start with l).
+      appearances=$(cat "$myLs" | grep "infile" | grep "^l" | wc -l)
+      if [ ! "$appearances" -eq "1" ]; then
+        echo "ERROR: TASK FAILED: testFilesAndPrefix function appearances check failed." | tee -a ${output_file}
+        exit 1
+      fi
   fi
 
-  myLs2=$(grep -r -l "ls -l --hide=.*inoutfile.* --sort=time" "$jobs_logs")
+  myLs2=$(grep -r -l "ls -l --hide=.*inoutfile.* --sort=time" $jobs_logs)
   if [[ -z "$myLs2" ]]; then
-     echo "ERROR: TASK FAILED: testFilesAndPrefixWithoutType function failed." | tee -a "${output_file}"
+     echo "ERROR: TASK FAILED: testFilesAndPrefixWithoutType function failed." | tee -a ${output_file}
     exit 1
+  else
+    # Check how many inoutfile are that are symlinks (start with l).
+    appearances=$(cat "$myLs2" | grep "inoutfile" | grep "^l" | wc -l)
+    if [ ! "$appearances" -eq "1" ]; then
+      echo "ERROR: TASK FAILED: testFilesAndPrefixWithoutType function appearances check failed." | tee -a ${output_file}
+      exit 1
+    fi
   fi
 
   #----------------------------------------------------------------------------------
@@ -98,7 +125,7 @@
   errors=$(cat "${output_file}" "${error_file}" | grep "ERROR" | cat)
   fails=$(cat "${output_file}" "${error_file}" | grep "FAIL" | cat)
   if [ "${errors}" != "" ] || [ "${fails}" != "" ]; then
-    echo "ERROR: UNIT TEST RAISED AN ERROR." | tee -a "${output_file}"
+    echo "ERROR: UNIT TEST RAISED AN ERROR." | tee -a ${output_file}
     exit 1
   fi
 
