[PyCOMPSs] Fixed bug when no type is specifed within a dictionary for a parameter. Added tests for the @binary decorator.
git-svn-id: http://compss.bsc.es/svn/compss/framework/trunk@3228 9ab3861e-6c05-4e1b-b5ef-99af60850597

Former-commit-id: aa94f731ded00563c8f178c88b5847884c4bc6a9

diff --git a/tests/sources/basic/58-binaryDecorator_python/result b/tests/sources/basic/58-binaryDecorator_python/result
--- a/tests/sources/basic/58-binaryDecorator_python/result
+++ b/tests/sources/basic/58-binaryDecorator_python/result
@@ -49,9 +49,19 @@
      echo "ERROR: TASK FAILED: testFileManagementIN function failed." | tee -a ${output_file}
     exit 1
   fi
-
   if grep -q "do" src/grepoutfile; then
     echo "ERROR: TASK FAILED: testFileManagement function failed."  | tee -a ${output_file}
+    exit 1
+  fi
+  lss=`grep -r "ls -l --hide=" $jobs_logs`
+  myLs=$(echo $lss | grep -r -l "infile --sort=size")
+  if [[ -z "$myLs" ]]; then
+     echo "ERROR: TASK FAILED: testFilesAndPrefix function failed." | tee -a ${output_file}
+    exit 1
+  fi
+  myLs2=$(echo $lss | grep -r -l "inoutfile --sort=time")
+  if [[ -z "$myLs2" ]]; then
+     echo "ERROR: TASK FAILED: testFilesAndPrefixWithoutType function failed." | tee -a ${output_file}
     exit 1
   fi
 
