Enabled tests 59 (ompss) and 60 (mpi). Validation of basic Ompss and MPI support in PyCOMPSs. Added new parameter aliases. Added binary proposals for streams.
git-svn-id: http://compss.bsc.es/svn/compss/framework/trunk@3050 9ab3861e-6c05-4e1b-b5ef-99af60850597

Former-commit-id: 96c905be8bd697c2f05c82af3a7d4da7d62c0fcf

diff --git a/tests/sources/basic/59-ompssDecorator_python/result b/tests/sources/basic/59-ompssDecorator_python/result
--- a/tests/sources/basic/59-ompssDecorator_python/result
+++ b/tests/sources/basic/59-ompssDecorator_python/result
@@ -30,6 +30,20 @@
   #----------------------------------------------------------------------------------
   # TODO: Check inout and output files consolidation
 
+  jobs_logs="${target_log_folder}/jobs"
+
+  friday=$(grep -r -l "date -d next friday" $jobs_logs)
+  fridayDate=$(date -d "next friday")
+  if ! $(cat "$friday" | grep -E -q "$fridayDate"); then
+    echo "ERROR: TASK FAILED: testFunctionalUsage function failed." | tee -a ${output_file}
+    exit 1
+  fi
+  monday=$(grep -r -l "date -d next monday" $jobs_logs)
+  mondayDate=$(date -d "next monday")
+  if ! $(cat "$monday" | grep -E -q "$mondayDate"); then
+    echo "ERROR: TASK FAILED: testFunctionalUsageWithConstraint function failed." | tee -a ${output_file}
+    exit 1
+  fi
   
   #----------------------------------------------------------------------------------
   # Grep for unit test errors (ERROR or FAIL)
