Improved test 59 results check and homogeneized with tests 58 and 60.

diff --git a/tests/sources/basic/59-ompssDecorator_python/result b/tests/sources/basic/59-ompssDecorator_python/result
--- a/tests/sources/basic/59-ompssDecorator_python/result
+++ b/tests/sources/basic/59-ompssDecorator_python/result
@@ -31,34 +31,62 @@
 
   jobs_logs="${target_log_folder}/jobs"
 
-  friday=$(grep -r -l "date -d next friday" $jobs_logs)
-  fridayDate=$(date -d "next friday")
-  if ! $(cat "$friday" | grep -E -q "$fridayDate"); then
-    echo "ERROR: TASK FAILED: testFunctionalUsage function failed." | tee -a ${output_file}
+  friday_file=$(grep -r -l "date -d next friday" "$jobs_logs")
+  fridayDate1=$(LANG=en_US date -d "next friday")
+  fridayDate2=$(date -d "next friday")
+  friday=$(grep -E "$fridayDate1|$fridayDate2" "$friday_file")
+  if [ "$friday" = "" ]; then
+    echo "ERROR: TASK FAILED: testFunctionalUsage function failed." | tee -a "${output_file}"
+    echo "  - FILE:     $friday_file" | tee -a "${output_file}"
+    echo "  - GOT:      $friday" | tee -a "${output_file}"
+    echo "  - EXPECTED: $fridayDate1 or $fridayDate2" | tee -a "${output_file}"
     exit 1
   fi
 
-  monday=$(grep -r -l "date -d next monday" $jobs_logs)
-  mondayDate=$(date -d "next monday")
-  if ! $(cat "$monday" | grep -E -q "$mondayDate"); then
-    echo "ERROR: TASK FAILED: testFunctionalUsageWithConstraint function failed." | tee -a ${output_file}
+  monday_file=$(grep -r -l "date -d next monday" "$jobs_logs")
+  mondayDate1=$(LANG=en_US date -d "next monday")
+  mondayDate2=$(date -d "next monday")
+  monday=$(grep -E "$mondayDate1|$mondayDate2" "$monday_file")
+  if [ "$monday" = "" ]; then
+    echo "ERROR: TASK FAILED: testFunctionalUsageWithConstraint function failed." | tee -a "${output_file}"
+    echo "  - FILE:     $monday_file" | tee -a "${output_file}"
+    echo "  - GOT:      $monday" | tee -a "${output_file}"
+    echo "  - EXPECTED: $mondayDate1 or $mondayDate2" | tee -a "${output_file}"
+    exit 1
+  else
+    appearances=$(cat "$monday_file" | grep "$mondayDate2" | wc -l)
+    if [ ! "$appearances" -eq "1" ]; then
+      echo "ERROR: TASK FAILED: testFunctionalUsageWithConstraint function appearances check failed." | tee -a ${output_file}
+      exit 1
+    fi
+  fi
+
+  tuesday_file=$(grep -r -l "date -d next tuesday" "$jobs_logs")
+  tuesdayDate1=$(LANG=en_US date -d "next tuesday")
+  tuesdayDate2=$(date -d "next tuesday")
+  tuesday=$(grep -E "$tuesdayDate1|$tuesdayDate2" "$tuesday_file")
+  if [ "$tuesday" = "" ]; then
+    echo "ERROR: TASK FAILED: testFunctionalUsageWithEnvVarConstraint function failed." | tee -a "${output_file}"
+    echo "  - FILE:     $tuesday_file" | tee -a "${output_file}"
+    echo "  - GOT:      $tuesday" | tee -a "${output_file}"
+    echo "  - EXPECTED: $tuesdayDate1 or $tuesdayDate2" | tee -a "${output_file}"
+    exit 1
+  elif grep "Null value obtained while loading \$CUS from environment" "${target_log_folder}"/runtime.log; then
+    echo "WARNING: TASK FAILED: testFunctionalUsageWithEnvVarConstraint function received NULL environment variable." | tee -a "${output_file}"
     exit 1
   fi
 
-  tuesday=$(grep -r -l "date -d next tuesday" $jobs_logs)
-  tuesdayDate=$(date -d "next tuesday")
-  if ! $(cat "$tuesday" | grep -E -q "$tuesdayDate"); then
-    echo "ERROR: TASK FAILED: testFunctionalUsageWithEnvVarConstraint function failed." | tee -a ${output_file}
-    exit 1
-  elif grep "Null value obtained while loading \$CUS from environment" ${target_log_folder}/runtime.log; then
-    echo "WARNING: TASK FAILED: testFunctionalUsageWithEnvVarConstraint function received NULL environment variable." | tee -a ${output_file}
-    exit 1
-  fi
-
-  hello=$(grep -r -l "HELLO, this is a simple test to grep." $jobs_logs)
+  hellofile=$(grep -r -l "sed s/Hi/HELLO/g" $jobs_logs)
+  hello=$(grep -r -l "HELLO, this is a simple test to grep." $hellofile)
   if [[ -z "$hello" ]]; then
      echo "ERROR: TASK FAILED: testFileManagementIN function failed." | tee -a ${output_file}
     exit 1
+  else
+    appearances=$(cat "$hellofile" | grep "HELLO, this is a simple test to grep." | wc -l)
+    if [ ! "$appearances" -eq "4" ]; then
+      echo "ERROR: TASK FAILED: testFileManagementIN function appearances check failed." | tee -a ${output_file}
+      exit 1
+    fi
   fi
 
   if grep -q "do" src/grepoutfile; then
@@ -68,14 +96,28 @@
 
   myLs=$(grep -r -l "ls -l --hide=.*infile.* --sort=size" $jobs_logs)
   if [[ -z "$myLs" ]]; then
-     echo "ERROR: TASK FAILED: testFilesAndPrefix function failed." | tee -a ${output_file}
+    echo "ERROR: TASK FAILED: testFilesAndPrefix function failed." | tee -a ${output_file}
     exit 1
+  else
+      # Check how many infile are that are symlinks (start with l).
+      appearances=$(cat "$myLs" | grep "infile" | grep "^l" | wc -l)
+      if [ ! "$appearances" -eq "1" ]; then
+        echo "ERROR: TASK FAILED: testFilesAndPrefix function appearances check failed." | tee -a ${output_file}
+        exit 1
+      fi
   fi
 
   myLs2=$(grep -r -l "ls -l --hide=.*inoutfile.* --sort=time" $jobs_logs)
   if [[ -z "$myLs2" ]]; then
      echo "ERROR: TASK FAILED: testFilesAndPrefixWithoutType function failed." | tee -a ${output_file}
     exit 1
+  else
+    # Check how many inoutfile are that are symlinks (start with l).
+    appearances=$(cat "$myLs2" | grep "inoutfile" | grep "^l" | wc -l)
+    if [ ! "$appearances" -eq "1" ]; then
+      echo "ERROR: TASK FAILED: testFilesAndPrefixWithoutType function appearances check failed." | tee -a ${output_file}
+      exit 1
+    fi
   fi
 
   #----------------------------------------------------------------------------------
