Fix misc errors on result scripts for python tests

diff --git a/tests/sources/basic/59-ompssDecorator_python/result b/tests/sources/basic/59-ompssDecorator_python/result
--- a/tests/sources/basic/59-ompssDecorator_python/result
+++ b/tests/sources/basic/59-ompssDecorator_python/result
@@ -28,6 +28,15 @@
   fi
 
   #----------------------------------------------------------------------------------
+  # Grep for unit test errors (ERROR or FAIL)
+  errors=$(cat "${output_file}" "${error_file}" | grep "ERROR" | cat)
+  fails=$(cat "${output_file}" "${error_file}" | grep "FAIL" | cat)
+  if [ "${errors}" != "" ] || [ "${fails}" != "" ]; then
+      echo "ERROR: UNIT TEST RAISED AN ERROR." | tee -a ${output_file}
+      exit 1
+  fi
+
+  #----------------------------------------------------------------------------------
 
   jobs_logs="${target_log_folder}/jobs"
 
@@ -118,15 +127,6 @@
       echo "ERROR: TASK FAILED: testFilesAndPrefixWithoutType function appearances check failed." | tee -a ${output_file}
       exit 1
     fi
-  fi
-
-  #----------------------------------------------------------------------------------
-  # Grep for unit test errors (ERROR or FAIL)
-  errors=$(cat "${output_file}" "${error_file}" | grep "ERROR" | cat)
-  fails=$(cat "${output_file}" "${error_file}" | grep "FAIL" | cat)
-  if [ "${errors}" != "" ] || [ "${fails}" != "" ]; then
-    echo "ERROR: UNIT TEST RAISED AN ERROR." | tee -a ${output_file}
-    exit 1
   fi
 
   exit 0
diff --git a/tests/sources/basic/71-argparse_python/result b/tests/sources/basic/71-argparse_python/result
--- a/tests/sources/basic/71-argparse_python/result
+++ b/tests/sources/basic/71-argparse_python/result
@@ -14,7 +14,7 @@
      result_expected="------------------------------------------------------------"
      test_result=$(tail -1 ${output_file})
      if [ "${result_expected}" != "${test_result}" ]; then
-        echo "SOME ERROR WAS FOUND. CHECK ERROsRS ABOVE." | tee -a ${output_file}
+        echo "SOME ERROR WAS FOUND. CHECK ERRORS ABOVE." | tee -a ${output_file}
         exit 1
      fi
   else
@@ -28,9 +28,17 @@
   fi
 
   #----------------------------------------------------------------------------------
+  # Grep for unit test errors (ERROR or FAIL)
+  errors=$(cat "${output_file}" "${error_file}" | grep "ERROR" | cat)
+  fails=$(cat "${output_file}" "${error_file}" | grep "FAIL" | cat)
+  if [ "${errors}" != "" ] || [ "${fails}" != "" ]; then
+      echo "ERROR: UNIT TEST RAISED AN ERROR." | tee -a ${output_file}
+      exit 1
+  fi
+
+  #----------------------------------------------------------------------------------
   # Compute result status
   correct=$(cat ${output_file} | grep "Argparse received the expected arguments and values")
-
 
   # Report result status
   if [ "${correct}" == "" ]; then
