Add pluto to local build, scs build and packages build

diff --git a/builders/buildlocal b/builders/buildlocal
--- a/builders/buildlocal
+++ b/builders/buildlocal
@@ -20,6 +20,7 @@
 DEFAULT_MONITOR=true
 DEFAULT_BINDINGS=true
 DEFAULT_TRACING=true
+DEFAULT_AUTOPARALLEL=false
 DEFAULT_USER=false
 DEFAULT_TARGET_DIR=/opt/COMPSs
 DEFAULT_MVN_TESTS=""
@@ -29,6 +30,7 @@ INCORRECT_PARAMETER="Error: No such parameter"
 NO_MONITOR="Warning: No monitor specified. Loading default value"
 NO_BINDINGS="Warning: No bindings specified. Loading default value"
 NO_TRACING="Warning: No tracing specified. Loading default value"
+NO_AUTOPARALLEL="Warning: No autoparallel specified. Loading default value"
 NO_TARGET_DIR="Warning: No install directory specified. Loading default location"
 
 
@@ -46,38 +48,42 @@ TMP_DIR=${SCRIPT_DIR}/tmp
 show_opts() {
   cat <<EOT
 * Options:
-    --help, -h          Print this help message
+    --help, -h                  Print this help message
 
-    --opts              Show available options
+    --opts                      Show available options
 
-    --version, -v       Print COMPSs version
+    --version, -v               Print COMPSs version
 
-    --monitor		Enable Monitor installation
-    --no-monitor 	Disable Monitor installation
-			Default: ${DEFAULT_MONITOR}
+    --monitor, -m	        Enable Monitor installation
+    --no-monitor, -M 	        Disable Monitor installation
+			        Default: ${DEFAULT_MONITOR}
 
-    --bindings		Enable bindings installation
-    --no-bindings       Disable bindings installation
-			Default: ${DEFAULT_BINDINGS}
+    --bindings, -b	        Enable bindings installation
+    --no-bindings, -B           Disable bindings installation
+			        Default: ${DEFAULT_BINDINGS}
 
-    --tracing           Enable tracing system installation
-    --no-tracing        Disable tracing system installation
-			Default: ${DEFAULT_TRACING}
+    --tracing, -t               Enable tracing system installation
+    --no-tracing, -T            Disable tracing system installation
+			        Default: ${DEFAULT_TRACING}
 
-    --nothing		Disable all previous options
-			Default: unused
+    --autoparallel, -p          Enable autoparallel module installation
+    --no-autoparallel, -P       Disable autoparallel module installation
+                                Default: ${DEFAULT_AUTOPARALLEL}
+    
+    --nothing, -N	        Disable all previous options
+			        Default: unused
 
-    --user-exec=<str>   Enables a specific user execution for maven compilation
-                        When used the maven install is not cleaned.
-			Default: ${DEFAULT_USER}
+    --user-exec=<str>           Enables a specific user execution for maven compilation
+                                When used the maven install is not cleaned.
+			        Default: ${DEFAULT_USER}
 
-    --skip-tests        Disables MVN unit tests
-                        Default: ${DEFAULT_MVN_TESTS}
+    --skip-tests                Disables MVN unit tests
+                                Default: ${DEFAULT_MVN_TESTS}
 
 * Parameters:
-    targetDir		COMPSs installation directory
-			Default: ${DEFAULT_TARGET_DIR}
-
+    targetDir		        COMPSs installation directory
+			        Default: ${DEFAULT_TARGET_DIR}
+                                            
 EOT
 }
 
@@ -113,8 +119,8 @@ display_error() {
 
 
 get_args() {
-  #Parse COMPSs Options
-  while getopts hv-: flag; do
+  # Parse COMPSs Options
+  while getopts hvmMbBtTpP-: flag; do 
     # Treat the argument
     case "$flag" in
       h)
@@ -125,6 +131,38 @@ get_args() {
         # Display version
         show_version
         exit
+        ;;
+      m)
+        # Custom monitor value
+        monitor=true
+        ;;
+      M)
+        # Custom monitor value
+        monitor=false
+        ;;
+      b)
+        # Custom bindings value
+        bindings=true
+        ;;
+      B)
+        # Custom bindings value
+        bindings=false
+        ;;
+      t)
+        # Custom tracing value
+        tracing=true
+        ;;
+      T)
+        # Custom tracing value
+        tracing=false
+        ;;
+      p)
+        # Custom autoparallel value
+        autoparallel=true
+        ;;
+      P)
+        # Custom autoparallel value
+        autoparallel=false
         ;;
       -)
 	# Check more complex arguments
@@ -166,6 +204,14 @@ get_args() {
           no-tracing)
             # Custom tracing value
             tracing=false
+            ;;
+          autoparallel)
+            # Custom autoparallel value
+            autoparallel=true
+            ;;
+          no-autoparallel)
+            # Custom autoparallel value
+            autoparallel=false
             ;;
           nothing)
             # Disables all flags
@@ -220,6 +266,11 @@ check_args() {
     tracing=${DEFAULT_TRACING}
   fi
 
+  if [ -z "$autoparallel" ]; then
+    display_warning "${NO_AUTOPARALLEL}"
+    autoparallel=${DEFAULT_AUTOPARALLEL}
+  fi
+
   if [ -z "${user_exec}" ]; then
     if [ -z "${SUDO_USER}" ]; then
       # Cannot retrieve sudo user from env
@@ -247,13 +298,14 @@ warn_and_log_parameters() {
   echo "    !! Remember to export JAVA_HOME on root"
   sleep 5
 
-  echo "- Target DIR  = ${targetDir}"
-  echo "- Monitor     = ${monitor}"
-  echo "- Bindings    = ${bindings}"
-  echo "- Tracing     = ${tracing}"
-  echo "- SCRIPT_DIR  = ${SCRIPT_DIR}"
-  echo "- SOURCES DIR = ${SOURCES_DIR}"
-  echo "- TMP_DIR     = ${TMP_DIR}"
+  echo "- Target DIR   = ${targetDir}"
+  echo "- Monitor      = ${monitor}"
+  echo "- Bindings     = ${bindings}"
+  echo "- Tracing      = ${tracing}"
+  echo "- AutoParallel = ${autoparallel}"
+  echo "- SCRIPT_DIR   = ${SCRIPT_DIR}"
+  echo "- SOURCES DIR  = ${SOURCES_DIR}"
+  echo "- TMP_DIR      = ${TMP_DIR}"
   sleep 5
 }
 
@@ -315,7 +367,7 @@ install_compss() {
 
   # RUNTIME DEPLOYMENT
   echo "- Copy Runtime deployment files"
-  #Doc
+  # Doc
   echo "--- Copy docs"
   find "${TMP_DIR}/doc/" -name "*.html" -delete
   cp -r "${TMP_DIR}"/doc/* ${targetDir}/Doc
@@ -325,16 +377,30 @@ install_compss() {
   cp "${TMP_DIR}/README.md" ${targetDir}
   cp "${TMP_DIR}/RELEASE_NOTES" ${targetDir}
 
-  #Dependencies
+  # DEPENDENCIES
   echo "--- Copy dependencies"
+  # GAT
   cp -r "${TMP_DIR}/dependencies/JAVA_GAT" ${targetDir}/Dependencies/
-  cp -r "${TMP_DIR}/files/paraver" ${targetDir}/Dependencies/
+  # Paraver CFGs
+  cp -r "${TMP_DIR}/files/paraver" ${targetDir}/Dependencies/  
+  # Extrae
   if [ "$tracing" == "true" ]; then
-    cd "${TMP_DIR}/dependencies/extrae"
+    cd "${TMP_DIR}"/dependencies/extrae
     ./install ${targetDir}/Dependencies/extrae false
     ev=$?
     if [ $ev -ne 0 ]; then
       echo "ERROR: Failed to install extrae dependency"
+      exit 1
+    fi
+    cd "${SCRIPT_DIR}"
+  fi
+  # Pluto
+  if [ "$autoparallel" = "true" ]; then
+    cd "${TMP_DIR}"/dependencies/pluto
+    ./install_pluto ${targetDir}/Dependencies/pluto
+    ev=$?
+    if [ $ev -ne 0 ]; then
+      echo "ERROR: Failed to install pluto dependency"
       exit 1
     fi
     cd "${SCRIPT_DIR}"
@@ -352,30 +418,31 @@ install_compss() {
   echo "--- Copy scripts"
   cp -r "${TMP_DIR}"/compss/runtime/scripts/* ${targetDir}/Runtime/scripts/
 
-  #Adaptors
+  # Adaptors
   echo "--- Copy adaptors"
   find "${TMP_DIR}/compss/runtime/adaptors" -name pom.xml -delete
+  find "${TMP_DIR}/compss/runtime/adaptors" -name "*.iml" -delete
   rm -r "${TMP_DIR}/compss/runtime/adaptors/commons"
   path_source=${TMP_DIR}/compss/runtime/adaptors
   path_target=${targetDir}/Runtime/adaptors
-  adaptors=$(ls ${path_source} | grep -v .*\.iml)
-  for adaptor in $adaptors; do
-    mkdir "${path_target}/$adaptor"
-    mkdir "${path_target}/$adaptor/master"
-    cp "${path_source}/$adaptor"/master/*.jar "${path_target}/$adaptor/master"
-    if [ -f "${path_source}/$adaptor/master/properties" ]; then
-      cp "${path_source}/$adaptor/master/properties" "${path_target}/$adaptor/master"
+  for adaptor in ${path_source}/*; do
+    adaptor_name=$(basename "$adaptor")
+    mkdir "${path_target}/${adaptor_name}"
+    mkdir "${path_target}/${adaptor_name}"/master
+    cp "$adaptor"/master/*.jar "${path_target}"/"${adaptor_name}"/master
+    if [ -f "$adaptor"/master/properties ]; then
+      cp "$adaptor"/master/properties "${path_target}"/"${adaptor_name}"/master
     fi
-    if [ -d "${path_source}/$adaptor/worker/" ]; then
-      mkdir "${path_target}/$adaptor/worker"
-      cp "${path_source}/$adaptor"/worker/*.jar "${path_target}/$adaptor/worker"
+    if [ -d "$adaptor"/worker/ ]; then
+      mkdir "${path_target}/${adaptor_name}"/worker
+      cp "$adaptor"/worker/*.jar "${path_target}"/"${adaptor_name}"/worker
     fi
-    if [ -f "${path_source}/$adaptor/worker/properties" ]; then
-      cp "${path_source}/$adaptor/worker/properties" "${path_target}/$adaptor/worker"
+    if [ -f "$adaptor"/worker/properties ]; then 
+      cp "$adaptor"/worker/properties "${path_target}"/"${adaptor_name}"/worker
     fi
-    if [ -d "${path_source}/$adaptor/scripts/" ]; then
-      mkdir -p "${targetDir}/Runtime/scripts/system/adaptors/$adaptor/"
-      cp -r "${path_source}/$adaptor"/scripts/* "${targetDir}/Runtime/scripts/system/adaptors/$adaptor/"
+    if [ -d "$adaptor"/scripts/ ]; then
+      mkdir -p "${targetDir}"/Runtime/scripts/system/adaptors/"${adaptor_name}"
+      cp -r "$adaptor"/scripts/* "${targetDir}"/Runtime/scripts/system/adaptors/"${adaptor_name}"
     fi
   done
 
diff --git a/builders/specs/rpm/compss-tools/build b/builders/specs/rpm/compss-tools/build
--- a/builders/specs/rpm/compss-tools/build
+++ b/builders/specs/rpm/compss-tools/build
@@ -4,6 +4,7 @@
   mode=$2
   COMPSS_VERSION=$3
 
+  SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
   package_name=compss-tools
   trunk_rel_path=../../../../
 
@@ -18,22 +19,23 @@
   echo " "
   echo "* Copying SPEC file to RPM build path..."
   echo " "
-  cp ./${package_name}_${mode}.spec tmp/SPECS/
+  cp ./${package_name}_"${mode}".spec tmp/SPECS/
 
   echo " "
-  echo "* Generating RPM package..."
+  echo "* Generating RPM package for version $COMPSS_VERSION..."
   cd tmp/
-  rpmbuild --define "_topdir $PWD" -bb --clean SPECS/${package_name}_${mode}.spec
-  if [ $? -ne 0 ]; then
-        echo "Error creating rpm";
-        exit 1;
+  rpmbuild --define "_topdir $PWD" -bb --clean SPECS/${package_name}_"${mode}".spec
+  ev=$?
+  if [ $ev -ne 0 ]; then
+        echo "Error creating rpm"
+        exit $ev
   fi
-  cd ..
+  cd "${SCRIPT_DIR}"
 
   echo " "
   echo "* Moving built RPM package to final location..."
-  mkdir -p ${trunk_rel_path}/builders/packages/${distr}/${package_name}
-  mv tmp/RPMS/${mode}/${package_name}-* ${trunk_rel_path}/builders/packages/$distr/${package_name}
+  mkdir -p ${trunk_rel_path}/builders/packages/"${distr}"/${package_name}
+  mv tmp/RPMS/"${mode}"/${package_name}-* ${trunk_rel_path}/builders/packages/"$distr"/${package_name}
 
   echo " "
   echo "* Cleaning all tmp files..."
