Add dependency management and automatic installation

diff --git a/builders/buildlocal b/builders/buildlocal
--- a/builders/buildlocal
+++ b/builders/buildlocal
@@ -22,6 +22,7 @@ DEFAULT_PYCOMPSS=true
 DEFAULT_TRACING=true
 DEFAULT_AUTOPARALLEL=true
 DEFAULT_KAFKA=true
+DEFAULT_SHMA=true
 DEFAULT_USER=false
 DEFAULT_TARGET_DIR=/opt/COMPSs
 DEFAULT_MVN_TESTS=""
@@ -34,6 +35,7 @@ NO_PYCOMPSS="Warning: No pycompss specified. Loading default value"
 NO_TRACING="Warning: No tracing specified. Loading default value"
 NO_AUTOPARALLEL="Warning: No autoparallel specified. Loading default value"
 NO_KAFKA="Warning: No Kafka module specified. Loading default value"
+NO_SHMA="Warning: No Shared Array module specified. Loading default value"
 NO_TARGET_DIR="Warning: No install directory specified. Loading default location"
 
 
@@ -80,6 +82,10 @@ show_opts() {
     --kafka, -k                 Enable Kafka module installation
     --no-kafka, -K              Disable Kafka module installation
                                 Default: ${DEFAULT_KAFKA}
+
+    --shared-array, -s          Enable Shared Array module installation
+    --no-shared-array, -S       Disable Shared Array module installation
+                                Default: ${DEFAULT_SHMA}
 
     --nothing, -N               Disable all previous options
                                 Default: unused
@@ -131,7 +137,7 @@ display_error() {
 
 get_args() {
   # Parse COMPSs Options
-  while getopts hvmMbBpPtTaAkKN-: flag; do
+  while getopts hvmMbBpPtTaAkKsSN-: flag; do
     # Treat the argument
     case "$flag" in
       h)
@@ -193,6 +199,14 @@ get_args() {
         # Custom Kafka value
         kafka=false
         ;;
+      s)
+        # Custom Shared Array value
+        shma=true
+        ;;
+      S)
+        # Custom Shared Array value
+        shma=false
+        ;;
       N)
         # Disables all flags
         tracing=false
@@ -201,6 +215,7 @@ get_args() {
         pycompss=false
         autoparallel=false
         kafka=false
+        shma=false
         ;;
       -)
 	# Check more complex arguments
@@ -269,6 +284,14 @@ get_args() {
             # Custom Kafka value
             kafka=false
             ;;
+          shared-array)
+            # Custom Shared Array value
+            shma=true
+            ;;
+          no-shared-array)
+            # Custom Shared Array value
+            shma=false
+            ;;
           nothing)
             # Disables all flags
             tracing=false
@@ -277,6 +300,7 @@ get_args() {
             pycompss=false
             autoparallel=false
             kafka=false
+            shma=false
             ;;
           user-exec=*)
             # Enables specific user mvn execution
@@ -340,6 +364,11 @@ check_args() {
     kafka=${DEFAULT_KAFKA}
   fi
 
+  if [ -z "${shma}" ]; then
+    display_warning "${NO_SHMA}"
+    shma=${DEFAULT_SHMA}
+  fi
+
   if [ -z "${user_exec}" ]; then
     if [ -z "${SUDO_USER}" ]; then
       # Cannot retrieve sudo user from env
@@ -374,6 +403,7 @@ warn_and_log_parameters() {
   echo "- Tracing        = ${tracing}"
   echo "- AutoParallel   = ${autoparallel}"
   echo "- Stream Backend = ${kafka}"
+  echo "- Shared Array   = ${shma}"
   echo "- SCRIPT_DIR     = ${SCRIPT_DIR}"
   echo "- SOURCES DIR    = ${SOURCES_DIR}"
   echo "- TMP_DIR        = ${TMP_DIR}"
@@ -550,6 +580,27 @@ install_compss() {
     fi
     cd "${SCRIPT_DIR}"
   fi
+  # Shared Array
+  export SHAREDARRAY_HOME="${TMP_DIR}"/dependencies/shared-array
+  cd "${SHAREDARRAY_HOME}"
+  shma_test_file="${SHAREDARRAY_HOME}"/shma_test_required.py
+  cat >"${shma_test_file}" <<EOF
+#!/usr/bin/python
+import sys
+try:
+    import SharedArray
+    sys.exit(0 if hasattr(SharedArray, 'create_copy') else 1)
+except ImportError:
+    sys.exit(2)
+EOF
+  ev=$?
+  if [ $ev -ne 0 ]; then
+    echo "Failed to create Shared Array test script. Abort."
+    exit $ev
+  fi
+  chmod +x "${shma_test_file}"
+  unset shma_test_file
+  cd "${SCRIPT_DIR}"
 
   # CONFIG
   echo "--- Copy configuration"
diff --git a/builders/scs/commons/buildSC_aux b/builders/scs/commons/buildSC_aux
--- a/builders/scs/commons/buildSC_aux
+++ b/builders/scs/commons/buildSC_aux
@@ -192,6 +192,30 @@
   # Streaming dependencies
   cp -r "${TMP_DIR}"/dependencies/kafka "${targetDir}"/Dependencies/
 
+  # Shared Array python module with create_copy capabilities
+  echo "---- Install Shared Array ----"
+  SHAREDARRAY_HOME="${TMP_DIR}"/dependencies/shared-array
+  cd "${SHAREDARRAY_HOME}" || exit 1
+  export SHAREDARRAY_HOME
+  shma_test_file="${SHAREDARRAY_HOME}"/shma_test_required.py
+  cat >"${shma_test_file}" <<EOF
+#!/usr/bin/python
+import sys
+try:
+    import SharedArray
+    sys.exit(0 if hasattr(SharedArray, 'create_copy') else 1)
+except ImportError:
+    sys.exit(2)
+EOF
+  ev=$?
+  if [ $ev -ne 0 ]; then
+    echo "Failed to create Shared Array test script. Abort."
+    exit $ev
+  fi
+  chmod +x "${shma_test_file}" || exit $?
+  unset shma_test_file
+  cd "${SCRIPT_DIR}" || exit 1
+
   # Restore original path
   export PATH=${originalPath}
 
diff --git a/compss/programming_model/bindings/python/install b/compss/programming_model/bindings/python/install
--- a/compss/programming_model/bindings/python/install
+++ b/compss/programming_model/bindings/python/install
@@ -39,7 +39,7 @@
     local python_complete_version
     local python_collapsed_version
 
-    PYCOMPSS_HOME="${targetDir}/$1"
+    PYCOMPSS_HOME="${targetDir}/${python_version}"
     export PYTHONPATH=$PYCOMPSS_HOME:$OLD_PYTHONPATH
     #export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-armhf
 
@@ -64,12 +64,71 @@
         exit $exitCode
       fi
 
+      # Check whether the dependency module is required
+      shma_test_script="${SHAREDARRAY_HOME}"/shma_test_required.py
+      ${python_command} "${shma_test_script}"
+      exitCode=$?
+      if [ $exitCode -ne 0 ]; then
+        need_shma=1
+        # Shared Array is either not installed or not the right version.
+        # We need to install the dependency.
+        shmaTargetDir="$( dirname $( dirname "${targetDir}" ) )"/Dependencies/SharedArray
+        export PYTHONPATH="${shmaTargetDir}":$PYTHONPATH
+        ${python_command} "${SHAREDARRAY_HOME}"/setup.py    \
+          build_ext   -b "${SHAREDARRAY_HOME}"/build  \
+          install_lib -b "${SHAREDARRAY_HOME}"/build  \
+                      --install-dir="${shmaTargetDir}"
+        exitCode=$?
+        if [ $exitCode -ne 0 ]; then
+          echo "ERROR: Failed to install Shared Array required dependency."
+          exit $exitCode
+        fi
+        cat > "${shmaTargetDir}"/__init__.py <<EOF
+#!/usr/bin/python
+#
+#  Copyright 2019      Cray UK Ltd., a Hewlett Packard Enterprise company
+#
+#  Licensed under the Apache License, Version 2.0 (the "License");
+#  you may not use this file except in compliance with the License.
+#  You may obtain a copy of the License at
+#
+#      http://www.apache.org/licenses/LICENSE-2.0
+#
+#  Unless required by applicable law or agreed to in writing, software
+#  distributed under the License is distributed on an "AS IS" BASIS,
+#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+#  See the License for the specific language governing permissions and
+#  limitations under the License.
+#
+
+# -*- coding: utf-8 -*-
+EOF
+        exitCode=$?
+        if [ $exitCode -ne 0 ]; then
+          echo "ERROR: Failed to create __init__.py file required for Shared Array module."
+          exit $exitCode
+        fi
+      else
+        need_shma=0
+        echo "Already installed for current python version. Skip."
+      fi
+
       # Do the installation
       ${python_command} "${SCRIPT_DIR}"/setup.py install --install-lib="${PYCOMPSS_HOME}" -O2
       exitCode=$?
       if [ $exitCode -ne 0 ]; then
         echo "ERROR: Cannot install PyCOMPSs for Python ${python_version}"
         exit $exitCode
+      fi
+
+      # Link to the dependencies so we find them in the pythonpath at runtime.
+      if [ $need_shma -gt 0 ]; then
+        ln -sfn "${shmaTargetDir}" "${PYCOMPSS_HOME}"
+        exitCode=$?
+        if [ $exitCode -ne 0 ]; then
+          echo "ERROR: Failed to create link to Shared Array dependency installation directory."
+          exit $exitCode
+        fi
       fi
 
       # Unify installed versions
