Added graph checking in tests result

diff --git a/tests/sources/java/1_annotation_task_groups/result b/tests/sources/java/1_annotation_task_groups/result
--- a/tests/sources/java/1_annotation_task_groups/result
+++ b/tests/sources/java/1_annotation_task_groups/result
@@ -4,54 +4,50 @@
   output_file=$1
   error_file=$2
   target_log_folder=$3
+  final_graph_expected=$4
 
   # Log files
   runtime_log="${target_log_folder}/runtime.log"
-  resources_log="${target_log_folder}/resources.log"
+  resources_log="${target_log_folder}/resources.log"                                                                                                                                                                                                                          
 
-  # Default checker (application ends with : Error running application)
+  #----------------------------------------------------------------------------------
+  # Check output standard out status
   if [ -f "${output_file}" ]; then
-     result_expected="Error running application"
-     test_result=$(tail -n 2 < "${output_file}" | head -n 1)
+     result_expected="------------------------------------------------------------"
+     test_result=$(tail -1 "${output_file}")
      if [ "${result_expected}" != "${test_result}" ]; then
-        echo "[ERROR] SOME ERROR WAS FOUND. CHECK ERRORS ABOVE." | tee -a "${output_file}"
-        exit 1
+        echo "SOME ERROR WAS FOUND. CHECK ERRORS ABOVE." | tee -a "${output_file}"
+        exit 1 
      fi
   else
      echo "[ERROR] Output file not found" | tee -a "${output_file}"
-     exit 1
+     exit 1 
   fi
-
-  # Check that ErrorManager has raised any ERROR or FATAL message
+  # Check that ErrorManager has not raised any ERROR or FATAL message
   if [ -f "${error_file}" ]; then
     if grep -E "\\[ERRMGR\\].*(ERROR|FATAL|Shutting down COMPSs)" "${error_file}"; then
-       echo "[RESULT_CHECKER] ErrorManager raised and ERROR as expected" | tee -a "${output_file}"
-    else
-      echo "[ERROR] ErrorManager did not raise any error" | tee -a "${output_file}"
-      exit 1
+      echo "ERROR: ErrorManager has raised a fatal error" | tee -a "${output_file}"
+      exit 1 
     fi
   else
-    echo "[ERROR] ErrorManager did not raise any error" | tee -a "${output_file}"
-    exit 1
+    # Empty error file, no exceptions could have been raised
+    : 
   fi
-  
-  #----------------------------------------------------------------------------------
-  # Compute result status
-  FILES=19
-  resultN=16
-
-  # Check that the Runtime has registered any fatal error
+  # Check that the Runtime has not registered any fatal error
   if [ -f "${runtime_log}" ]; then
     if grep -E "ErrorManager\\].*\\[ERRMGR\\].*Error detected. Shutting down COMPSs" "${runtime_log}"; then
-      echo "[RESULT_CHECKER] ErrorManager registered an ERROR as expected" | tee -a "${output_file}"
-    else
-      echo "[ERROR] ErrorManager did not register any error" | tee -a "${output_file}"
-      exit 1
+      echo "ERROR: ErrorManager has registered a fatal error in the runtime.log" | tee -a "${output_file}"
+      exit 1 
     fi
   else
     echo "[ERROR] runtime.log not found" | tee -a "${output_file}"
-    exit 1
+    exit 1 
   fi
+
+  #----------------------------------------------------------------------------------
+  # Compute result status
+  FILES=18
+  resultN=16
 
   # Checks if the file has been written as many times as expected
   result=$(cat /tmp/sharedDisk/taskGroups.txt)
@@ -70,12 +66,14 @@
     echo "ERROR: More tasks than expected have been executed."
     exit 1
   fi
-
-  # Check if the task has failed
-  output1=$(cat "${runtime_log}" | grep "TOTALLY FAILED" | wc -l)
-  if [ "${output1}" -ne "${FILES}" ]; then
-  	echo "ERROR: The task has not failed."
-  	exit 1
+  
+  #----------------------------------------------------------------------------------
+  # Check dot file
+  final_graph_got=${target_log_folder}/monitor/complete_graph.dot
+  graph_status=$(diff -U 0 "${final_graph_expected}" "${final_graph_got}" | grep -v ^@ | grep -v "#" | tail -n+3)
+  if [ ! -z "${graph_status}" ]; then
+    echo "[ERROR] Obtained graph file is not as expected" | tee -a "${output_file}"
+    exit 1
   fi
 
   #---------------------------------------------------------------------------------- 
diff --git a/tests/sources/python/0_annotation_commutative/result b/tests/sources/python/0_annotation_commutative/result
--- a/tests/sources/python/0_annotation_commutative/result
+++ b/tests/sources/python/0_annotation_commutative/result
@@ -4,6 +4,7 @@
   output_file=$1
   error_file=$2
   target_log_folder=$3
+  final_graph_expected=$4
 
   # Log files
   runtime_log="${target_log_folder}/runtime.log"
@@ -118,6 +119,14 @@
     exit 1
   fi
 
+    #----------------------------------------------------------------------------------
+  # Check dot file
+  final_graph_got=${target_log_folder}/monitor/complete_graph.dot
+  graph_status=$(diff -U 0 "${final_graph_expected}" "${final_graph_got}" | grep -v ^@ | grep -v "#" | tail -n+3)
+  if [ ! -z "${graph_status}" ]; then
+    echo "[ERROR] Obtained graph file is not as expected" | tee -a "${output_file}"
+    exit 1
+  fi
 
   #----------------------------------------------------------------------------------
   # ALL OK. Report result status
