Add on failure tests

diff --git a/tests/sources/fault_tolerance/2_on_failure_retry_python/result b/tests/sources/fault_tolerance/2_on_failure_retry_python/result
--- a/tests/sources/fault_tolerance/2_on_failure_retry_python/result
+++ b/tests/sources/fault_tolerance/2_on_failure_retry_python/result
@@ -10,32 +10,29 @@
   resources_log="${target_log_folder}/resources.log"
 
   #----------------------------------------------------------------------------------
-  # Check output standard out status
-  if [ -f "${output_file}" ]; then
-     result_expected="------------------------------------------------------------"
-     test_result=$(tail -1 "${output_file}")
-     if [ "${result_expected}" != "${test_result}" ]; then
-        echo "SOME ERROR WAS FOUND. CHECK ERRORS ABOVE." | tee -a "${output_file}"
-        exit 1
-     fi
-  else
-     echo "[ERROR] Output file not found" | tee -a "${output_file}"
-     exit 1
-  fi
-  # Check that ErrorManager has not raised any ERROR or FATAL message
+  # Do not check standard out/err status since test must fail
+  # Do not check unit tests status since test must fail
+
+  #----------------------------------------------------------------------------------
+
+  # Check that ErrorManager has raised any ERROR or FATAL message
   if [ -f "${error_file}" ]; then
     if grep -E "\\[ERRMGR\\].*(ERROR|FATAL|Shutting down COMPSs)" "${error_file}"; then
-      echo "ERROR: ErrorManager has raised a fatal error" | tee -a "${output_file}"
+       echo "[RESULT_CHECKER] ErrorManager raised and ERROR as expected" | tee -a "${output_file}"
+    else
+      echo "[ERROR] ErrorManager did not raise any error" | tee -a "${output_file}"
       exit 1
     fi
   else
-    # Empty error file, no exceptions could have been raised
-    :
+    echo "[ERROR] ErrorManager did not raise any error" | tee -a "${output_file}"
+    exit 1
   fi
-  # Check that the Runtime has not registered any fatal error
+  # Check that the Runtime has registered any fatal error
   if [ -f "${runtime_log}" ]; then
     if grep -E "ErrorManager\\].*\\[ERRMGR\\].*Error detected. Shutting down COMPSs" "${runtime_log}"; then
-      echo "ERROR: ErrorManager has registered a fatal error in the runtime.log" | tee -a "${output_file}"
+      echo "[RESULT_CHECKER] ErrorManager registered an ERROR as expected" | tee -a "${output_file}"
+    else
+      echo "[ERROR] ErrorManager did not register any error" | tee -a "${output_file}"
       exit 1
     fi
   else
@@ -43,16 +40,51 @@
     exit 1
   fi
 
-  #----------------------------------------------------------------------------------
-  # Grep for unit test errors (ERROR or FAIL)
-  errors=$(cat "${output_file}" "${error_file}" | grep "ERROR" | cat)
-  fails=$(cat "${output_file}" "${error_file}" | grep "FAIL" | cat)
-  if [ "${errors}" != "" ] || [ "${fails}" != "" ]; then
-      echo cat "${error_file}"
-      echo "ERROR: UNIT TEST RAISED AN ERROR." | tee -a "${output_file}"
+#----------------------------------------------------------------------------------
+  # Compute result status
+  FILES=4
+  resultN=1
+
+  # Check that the Runtime has registered any fatal error
+  if [ -f "${runtime_log}" ]; then
+    if grep -E "ErrorManager\\].*\\[ERRMGR\\].*Error detected. Shutting down COMPSs" "${runtime_log}"; then
+      echo "[RESULT_CHECKER] ErrorManager registered an ERROR as expected" | tee -a "${output_file}"
+    else
+      echo "[ERROR] ErrorManager did not register any error" | tee -a "${output_file}"
       exit 1
+    fi
+  else
+    echo "[ERROR] runtime.log not found" | tee -a "${output_file}"
+    exit 1
   fi
 
+  # Checks if the file has been written as many times as expected
+  result=$(cat /tmp/sharedDisk/file1.txt)
+  if [ ${result} -ne $resultN ]; then
+    echo "ERROR: The number of writing tasks is not correct. ${#result} "
+    exit 1
+  fi
+
+  # Checks if the failed task has been executed through the creation of a job for each
+  if [ ! -f "${target_log_folder}"/jobs/job"$resultN"_RESUBMITTED.out ]; then
+    echo "ERROR: All tasks have not completed succesfully."
+    exit 1
+  fi
+
+  if [ -f "${target_log_folder}/jobs/job$((FILES+1))_NEW.out" ]; then
+    echo "ERROR: More tasks than expected have been executed."
+    exit 1
+  fi
+
+  # Check if the task has failed
+  output1=$(cat "${runtime_log}" | grep "TOTALLY FAILED" | wc -l)
+  if [ ${output1} -ne ${FILES} ]; then
+  	echo "ERROR: The first task has not failed."
+  	exit 1
+  fi
   #----------------------------------------------------------------------------------
   # ALL OK. Report result status
   exit 0
+
+
+
