Adapting tests to look for error messages at errorlog

diff --git a/tests/sources/local/python/2_kill_processes/result b/tests/sources/local/python/2_kill_processes/result
--- a/tests/sources/local/python/2_kill_processes/result
+++ b/tests/sources/local/python/2_kill_processes/result
@@ -14,7 +14,7 @@
 
   #----------------------------------------------------------------------------------
   # Compute result status
-  if ! grep "Error running application" "${output_file}"; then
+  if ! grep "Error running application" "${error_file}"; then
     echo "[ERROR] The application did not end with the Error message" | tee -a "${output_file}"
     exit 1
   fi
