Modify deb/rpm spec files for JAVA_HOME. Modify bindings common, c-binding, python-binding install script for JAVA_HOME. Solve bug on update_trunk_version updating apache version
git-svn-id: http://compss.bsc.es/svn/compss/framework/trunk@2750 9ab3861e-6c05-4e1b-b5ef-99af60850597

diff --git a/builders/specs/deb/compss-c-binding/amd64/postinst b/builders/specs/deb/compss-c-binding/amd64/postinst
--- a/builders/specs/deb/compss-c-binding/amd64/postinst
+++ b/builders/specs/deb/compss-c-binding/amd64/postinst
@@ -7,18 +7,29 @@
     newversion=$1
 
     # Find JAVA_HOME
-    openjdk=$(dpkg --get-selections | grep -v deinstall | grep openjdk | grep headless | head -n 1 | cut -f1)
-    libjvm=$(dpkg-query -L $openjdk | grep libjvm.so | head -n 1)
-    export JAVA_LIB_DIR=$(dirname $libjvm)
-    if test "${libjvm#*/jre/lib/amd64/server/libjvm.so}" != "$libjvm"; then
-      export JAVA_HOME="${libjvm/\/jre\/lib\/amd64\/server\/libjvm.so/}"
-    elif test "${libjvm#*/jre/lib/i386/client/libjvm.so}" != "$libjvm"; then
-      export JAVA_HOME="${libjvm/\/jre\/lib\/i386\/client\/libjvm.so/}"
-    elif [ -z $JAVA_HOME ]; then
-      echo "Please define \$JAVA_HOME"
-      exit 1
+    if [ -z ${JAVA_HOME} ]; then
+      echo " - Finding JAVA_HOME installation"
+      openjdk=$(dpkg --get-selections | grep -v deinstall | grep openjdk | grep headless | tail -n 1 | cut -f1)
+      libjvm=$(dpkg-query -L $openjdk | grep libjvm.so | head -n 1)
+      if [ -z $libjvm ]; then
+        echo "ERROR: Invalid JAVA_HOME installation. No libjvm.so found"
+        exit 1
+      fi
+      JAVA_LIB_DIR=$(dirname $libjvm)
+      JAVA_HOME=${JAVA_LIB_DIR}/../../../
+    else 
+      echo " - Using defined JAVA_HOME installation: ${JAVA_HOME}"
+      libjvm=$(find ${JAVA_HOME} -name libjvm.so | head -n 1)
+      if [ -z $libjvm ]; then
+        echo "ERROR: Invalid JAVA_HOME installation. No libjvm.so found"
+        exit 1
+      fi
+      JAVA_LIB_DIR=$(dirname $libjvm)
     fi
-    echo "Using JAVA_HOME=$JAVA_HOME"
+    echo "Using JAVA_HOME=${JAVA_HOME}"
+    echo "Using JAVA_LIB_DIR=${JAVA_LIB_DIR}"                                                                                                                                           
+    export JAVA_HOME=${JAVA_HOME}
+    export JAVA_LIB_DIR=${JAVA_LIB_DIR}
 
     # Configure
     echo "   - Configure, compile and install"
diff --git a/compss/programming_model/bindings/python/install b/compss/programming_model/bindings/python/install
--- a/compss/programming_model/bindings/python/install
+++ b/compss/programming_model/bindings/python/install
@@ -3,16 +3,20 @@
   targetDir=$1
   sourcesDir=$(pwd)
 
-  #Install
+  # Install
+  PYCOMPSS_HOME=${targetDir}
   echo "Installing in $PYCOMPSS_HOME"
-  python ${sourcesDir}/setup.py install --install-lib=${targetDir}
+  python ${sourcesDir}/setup.py install --install-lib=${PYCOMPSS_HOME}
   exitCode=$?
 
-  #Clean
+  # Clean
   rm -rf ${sourcesDir}/build
 
-  #Exit
+  # Exit
   if [ $exitCode -ne 0 ]; then
-	echo "Error in Python binding package";
-	exit 1;
+    echo "Error in Python binding package"
+    exit 1
+  else
+    exit 0
   fi
+
