Update test multiple agents

diff --git a/tests/sources/local/agents/2_multiple_agents/execution b/tests/sources/local/agents/2_multiple_agents/execution
--- a/tests/sources/local/agents/2_multiple_agents/execution
+++ b/tests/sources/local/agents/2_multiple_agents/execution
@@ -336,6 +336,7 @@
     --agent_port="46101" \
     --comm="es.bsc.compss.agent.comm.CommAgentAdaptor" \
     --cpu=1 \
+    --arch="amd64" \
     "COMPSsWorker02" "Port=46202" > >(tee -a "${output_log}")  2> >(tee -a "${error_log}") 
   sleep 1
   
@@ -390,6 +391,11 @@
   CPU_COUNT=$(echo "${DESCRIPTION}" | jq '.processors[] | select(.name=="MainProcessor") | .units')
   if [ ! "${CPU_COUNT}" == "1" ]; then
     echo "Wrong number of CPU cores configured for the Agent 2. Found ${CPU_COUNT}; 1 expected." > >(tee -a "${error_log}")
+    exit 1
+  fi
+  ARCHITECTURE=$(echo "${DESCRIPTION}" | jq -r '.processors[] | select(.name=="MainProcessor") | .architecture')
+  if [ "${ARCHITECTURE}" != "amd64" ]; then
+    echo "Wrong architecture configured for Agent 2. Found ${ARCHITECTURE}; expected amd64." > >(tee -a "${error_log}")
     exit 1
   fi
 
@@ -541,7 +547,8 @@
     --agent_port="46101" \
     --comm="es.bsc.compss.agent.comm.CommAgentAdaptor" \
     --cpu=1 \
-    "COMPSsWorker03" "Port=46302" > >(tee -a "${output_log}")  2> >(tee -a "${error_log}") 
+    --arch="amd64" \
+    "COMPSsWorker03" "Port=46302" > >(tee -a "${output_log}")  2> >(tee -a "${error_log}")
   sleep 1
   
 # CHECK WHETHER THE Worker was properly set on AGENT 1
@@ -595,6 +602,11 @@
   CPU_COUNT=$(echo "${DESCRIPTION}" | jq '.processors[] | select(.name=="MainProcessor") | .units')
   if [ ! "${CPU_COUNT}" == "1" ]; then
     echo "Wrong number of CPU cores configured for the Agent 2. Found ${CPU_COUNT}; 1 expected." > >(tee -a "${error_log}")
+    exit 1
+  fi
+  ARCHITECTURE=$(echo "${DESCRIPTION}" | jq -r '.processors[] | select(.name=="MainProcessor") | .architecture')
+  if [ "${ARCHITECTURE}" != "amd64" ]; then
+    echo "Wrong architecture configured for Agent 2. Found ${ARCHITECTURE}; expected amd64." > >(tee -a "${error_log}")
     exit 1
   fi
 
@@ -677,6 +689,7 @@
     --agent_port="46101" \
     --comm="es.bsc.compss.agent.rest.master.Adaptor" \
     --cpu=1 \
+    --arch="amd64" \
     "COMPSsWorker04" "Port=46401" > >(tee -a "${output_log}")  2> >(tee -a "${error_log}") 
   sleep 1
 
@@ -733,6 +746,11 @@
   CPU_COUNT=$(echo "${DESCRIPTION}" | jq '.processors[] | select(.name=="MainProcessor") | .units')
   if [ ! "${CPU_COUNT}" == "1" ]; then
     echo "Wrong number of CPU cores configured for the Agent 2. Found ${CPU_COUNT}; 1 expected." > >(tee -a "${error_log}")
+    exit 1
+  fi
+  ARCHITECTURE=$(echo "${DESCRIPTION}" | jq -r '.processors[] | select(.name=="MainProcessor") | .architecture')
+  if [ "${ARCHITECTURE}" != "amd64" ]; then
+    echo "Wrong architecture configured for Agent 2. Found ${ARCHITECTURE}; expected amd64." > >(tee -a "${error_log}")
     exit 1
   fi
 
