Solved failed result of concurrent tests

diff --git a/tests/sources/basic/96-concurrentObjectTest/result b/tests/sources/basic/96-concurrentObjectTest/result
--- a/tests/sources/basic/96-concurrentObjectTest/result
+++ b/tests/sources/basic/96-concurrentObjectTest/result
@@ -31,8 +31,22 @@
   FILES=18
   resultN=6
 
-  # Checks if the file has been writen as many times as expected
-  result=$(cat /tmp/sharedDisk/file.txt)
+  # Checks if the first file has been writen as many times as expected
+  result=$(cat /tmp/sharedDisk/file1.txt)
+  if [ ${#result} -ne $resultN ]; then
+    echo "ERROR: The number of writing tasks is not correct. ${#result} "
+    exit 1
+  fi
+
+# Checks if the second file has been writen as many times as expected
+  result=$(cat /tmp/sharedDisk/file2.txt)
+  if [ ${#result} -ne $resultN ]; then
+    echo "ERROR: The number of writing tasks is not correct. ${#result} "
+    exit 1
+  fi
+
+# Checks if the third file has been writen as many times as expected
+  result=$(cat /tmp/sharedDisk/file3.txt)
   if [ ${#result} -ne $resultN ]; then
     echo "ERROR: The number of writing tasks is not correct. ${#result} "
     exit 1
diff --git a/tests/sources/basic/97-concurrentObject_python/result b/tests/sources/basic/97-concurrentObject_python/result
--- a/tests/sources/basic/97-concurrentObject_python/result
+++ b/tests/sources/basic/97-concurrentObject_python/result
@@ -38,12 +38,23 @@
 
   #----------------------------------------------------------------------------------
   FILES=16
-  result=$(cat /tmp/sharedDisk/file.txt)
-  if [ ${#result} -ne 8 ]; then
+  writers=8
+
+  #Checks first file to write
+  result=$(cat /tmp/sharedDisk/file1.txt)
+  if [ ${#result} -ne $writers ]; then
     echo "ERROR: Final result is not correct. ${#result} "
     exit 1
   fi
 
+  #Checks second file to write
+   result=$(cat /tmp/sharedDisk/file2.txt)
+  if [ ${#result} -ne $writers ]; then
+    echo "ERROR: Final result is not correct. ${#result} "
+    exit 1
+  fi
+
+  #Checks that all tasks have been completed
   if [ ! -f "${target_log_folder}/jobs/job${FILES}_NEW.out" ]; then
     echo "ERROR: All tasks have not completed succesfully."
     exit 1
